### ISSUE TITLE
AcceptanceHelper Question

### ISSUE THREAD

**Issue by maxchirkov** [lucatume/wp-browser#10]
I'd like to create a test sequence that could be easily re-used in different projects. I wonder if it could be created within AcceptanceHelper class. Is there a way to add methods to AcceptanceHelper that could utilize already existing WP functions in AcceptanceTester? 

For example: 
```php
$I->seeWPTestSequence1Passed($pluginSlug)
```
where `seeWPTestSequence1Passed()` would login into the WP admin, activate/deactivate plugins and perform all sorts of routine assertions.

**Comment by maxchirkov** [comment]
I figured it out. Simply create a new public method inside AcceptanceHelper with the
```php
<?php
$wp = $this->getModule('WPWebDriver');
$wp->amOnPluginsPage();
```
Where $wp is the WPWebDriver object with its all public methods.

**Comment by lucatume** [comment]
That's not a feature of WP browser as much as it is a feature of Codeception: 

Luca
