### ISSUE TITLE
Update regexp to strip out comments in SQL dump

### ISSUE THREAD

**Issue by slaFFik** [lucatume/wp-browser#104]
Your current code to remove comments in SQL file in `WPDb` is 

```php
$sql = preg_replace('%/\*(?!!\d+)(?:(?!\*/).)*\*/%s', "", $sql);
```
Codeception switched like a year ago or so to a shorter and quicker (in `Db`)

```php
// remove C-style comments (except MySQL directives)
$sql = preg_replace('%/\*(?!!\d+).*?\*/%s', '', $sql);
```

https://github.com/Codeception/Codeception/issues/3128

**Comment by lucatume** [comment]
Would you like to open a PR?

**Comment by slaFFik** [comment]
Sure, I will do that. 
One-liner only and I will become a wp-browser contributor! A bit later today :)

**Comment by lucatume** [comment]
Closing this as the PR has been merged, thanks a ton!
