### ISSUE TITLE
Grab WP Cookie issue

### ISSUE THREAD

**Issue by maxchirkov** [lucatume/wp-browser#11]
Hi Luca,

I tried using your example for re-setting cookies instead of logging user in in every single test: http://theaveragedev.com/backend-wordpress-04/ I literally copied and pasted your first 2 methods into my class (+ the namespace references), but I get this error:
```
Call to a member function getName() on a non-object 
```
And that happens on the following lines:
```php
$I->setCookie( self::$authCookie->getName(), self::$authCookie->getValue() );
$I->setCookie( self::$loginCookie->getName(), self::$loginCookie->getValue() );
```
any ideas why this would happen?

**Comment by lucatume** [comment]
Hi,

it probably depends on the fact that, currently, the same methods used in a WPBrowser based test and the ones used in a WPWebDriver acceptance test will return different kind of objects.  
Methods will expose the same API, the `grab...` methods, in WPBrowser (hence PHPBrowser) based tests and WpWebDriver (hence WebDriver) based tests but the former will return a Cookie object (implementint the afore mentioned `getName` and `getValue` methods) and the latter will return an simple array.
