### ISSUE TITLE
False positive while trying a basic login test with Chrome driver

### ISSUE THREAD

**Issue by devanonyme** [lucatume/wp-browser#112]
Hello,

I'm evaluating codeception and WP-Browser to add minimal testing to our plugin. 

I have problem with a very simple test that doesnt give the expected results.

$I = new AcceptanceTester($scenario);
$I->wantTo('perform actions and see result');
$I->wait(2);
$I->loginAsAdmin();
$I->wait(2);
$I->amOnPluginsPage();
$I->wait(2);

I get a "passed" but the login visibily fail, Chrome also display an error about the browser not supporting cookies (and Worpress probably fails the login because of that).

I actually had this error while trying the first time (windows and vvv on windows installation) and I have gone through hoops to install vvv on a desktop ubuntu to remove some variables and see what's happening with the test.

Signature: codeceptiontestingCept
Test: tests/acceptance/codeceptiontestingCept.php
Scenario --
 I wait 2
 I login as admin 
  [GET] http://local.wordpress.dev/wp-login.php
  Cookies matching pattern /^wordpress_[a-z0-9]{32}$/ : 
  Cookies matching pattern /^wordpress_logged_in_[a-z0-9]{32}$/ : {"wordpress_logged_in_4a5a5e3d7105ef3340c871f81e74ac36": "admin%7C1509836065%7Cyk35Q5ACzE3jWE2yTtNmTMRozV5Yt151EAY1rNCNeAb%7Cfaf790346f28910fe052b4527fd2f0b14c7c857f7ff21bff1a623dbc02f26b76"}
 I wait 2
 I am on plugins page 
  [GET] http://local.wordpress.dev/wp-admin/plugins.php
 I wait 2
 **PASSED**

![test_not_really_passed](https://user-images.githubusercontent.com/21067311/32354322-9a3b7700-bfff-11e7-8db6-2c2071cd4df3.png)

I tried to read what was available and have found nothing explaining clearly how to activate cookies on chrome (I guess this one is not wp-browser or even codeception specific but considering we use configurations files maybe I'm missing something).

Sorry if the question is not clear or you feel it's another part of the stack that is involved, there is alot of techno / layers involved and starting up it's a bit difficult for me to debug...

Should I stick to Firefox?

I'll continue my investigation (chrome options / capabilities, settings of selenium server, or maybe it is just the I'm on login test that is not adequate?) vagrant but if someone would have pointers that would be very appreciated.

My objective would be to be able to run the test on CircleCI and later Travis but at first I want to be able to program and see the test running visually (I will use ubuntu desktop instead of my usual windows machine so that I can reproduce the setup when the issues are solved).

**Comment by devanonyme** [comment]
More info
On Firefox, there is actually a visible fail (  [PHPUnit\Framework\Exception] Undefined index: ELEMENT).

Acceptance settings

# Codeception Test Suite Configuration
#
# Suite for acceptance tests.
# Perform tests in browser using the WPWebDriver or WPBrowser.
# Use WPDb to set up your initial database fixture.
# If you need both WPWebDriver and WPBrowser tests - create a separate suite.

actor: AcceptanceTester
modules:
    enabled:
        - WPWebDriver
        - WPDb
        - \Helper\Acceptance
    config:
        WPDb:
            dsn: 'mysql:host=localhost;dbname=wordpress_default'
            user: 'wp'
            password: 'wp'
            dump: 'tests/_data/dump.sql'
            populate: true #import the dump before the tests
            cleanup: true #import the dump between tests
            url: 'http://local.wordpress.dev'
            urlReplacement: true #replace the hardcoded dump URL with the one above
            tablePrefix: 'wp_TESTS_'
        WPWebDriver:
            browser: firefox
            url: 'http://local.wordpress.dev/'
            adminUsername: admin
            adminPassword: password
            adminPath: /wp-admin

**Comment by devanonyme** [comment]
It's maybe completely something else, I can reproduce de issue with a simple python script but the login do complete correctly if I use one of our other dev server (not my computer or a local vm)... maybe something related to vvv or the way the local adress is resolved?

import time
from selenium import webdriver

driver = webdriver.Chrome('/usr/lib/chromium-browser/chromedriver') 
driver.get('http://local.wordpress.dev/wp-login.php');
time.sleep(5) # Let the user actually see something!
user_box = driver.find_element_by_name('log')
user_box.send_keys('admin')
password_box = driver.find_element_by_name('pwd')
password_box.send_keys('password')
password_box.submit()
time.sleep(10) # Let the user actually see something!
driver.quit()

**Comment by devanonyme** [comment]
I think I have found something about localhost and cookies : https://bugs.chromium.org/p/chromium/issues/detail?id=56211

I will check that on both browser and check the implementation of amonpluginpage to to check if I can understand what’s happening, I can reopen a bug if I really see a bug there.

So you can close for now.

**Comment by devanonyme** [comment]
I confirm that changing the domain make the login complete correctly.
Looks promising!

**Comment by lucatume** [comment]
Hi,

sorry for getting back to this so late: any news?

**Comment by devanonyme** [comment]
I still have to check why there where no errors when cookies are not activated.
It's not a blocking issue anymore so it was naturally pushed down in priorities.

You can close the issue if you prefer but I can report if / when I give it a second look.

Thanks!

**Comment by lucatume** [comment]
Perfect, thanks for following up so quickly (as opposed to me).

If you find anything else let me know; happy testing.
