### ISSUE TITLE
Unable to unserialize on isolated-install.php

### ISSUE THREAD

**Issue by johnnyhuy** [lucatume/wp-browser#114]
Greetings,

I've seemed to come across an issue with the config data passed from bootstrap.php to isolated-install.php. The error appears when running my wpunit tests `vendor/bin/codecept run wpunit`, which, cascades on to other related errors. Initial error as shown:

```
PHP Notice:  unserialize(): Error at offset 5 of 879 bytes in ..\wp-content\themes\jhuy\vendor\lucatume\wp-browser\src\includes\isolated-install.php on line 8
```

My environment:

- Windows 10 Pro 1703 x64
- PHP 7.1.2

Thankfully, there's a solution by simply encoding the string to base 64 and then decode it once passed.

***src/includes/bootstrap.php***

```PHP
system( implode( ' ', [
	WP_PHP_BINARY,
	escapeshellarg( $isolatedInstallationScript ),
	escapeshellarg( base64_encode( serialize( $environment ) ) ),
	$multisite
] ) );
```

***src/includes/isolated-install.php***

```PHP
$configuration = unserialize( base64_decode( $argv[1] ) );
```

Please let me know if I'm on the right path with this.

Thanks,

**Comment by lucatume** [comment]
Thanks for reporting this and proposing a solution, much appreciated.
PRs are welcome as well.
