### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Console\Output\ConsoleOutput' not found

### ISSUE THREAD

**Issue by rahularyan** [lucatume/wp-browser#116]
Hello,
I am trying to install wp-browser but I am getting below error. Tried to re-install many times. Codeception was not already installed.  Please tell me what going on.

Thanks for help.

```PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Console\Output\ConsoleOutput' not found in C:\Users\nerdaryan\AppData\Roaming\Composer\vendor\lucatume\wp-browser\wpcept:9
Stack trace:
#0 {main}
  thrown in C:\Users\**\AppData\Roaming\Composer\vendor\lucatume\wp-browser\wpcept on line 9
```

composer.json

```
"require-dev": {
        "lucatume/wp-browser": "^1.21"
    }
```

**Comment by lucatume** [comment]
I've just tried to install and setup the suite using this sequence with no issues:
```
composer init
...
composer require --dev lucatume/wp-browser
./vendor/bin/codecept init wpbrowser
....
```

Could you please detail the steps you took and the rest of the `composer.json` file?

**Comment by rahularyan** [comment]
I am installing wp-browser globally, is that causing this issue?

**Comment by lucatume** [comment]
Generally installing Composer packages globally is not a good idea, especially when it comes to testing tools.
Try installing it locally and see if that proves to be the issue: some other globally installed package might be requiring a specific version of another package that's creating conflicts.

If you find out anything let me know.

**Comment by rahularyan** [comment]
Yes, Installing locally fixed the issue.
But when I run a test on selenium and try to login as admin using `$i->loaginAsAdmin()` always fails. I tried to login manually to test site and appears that admin login and passwords are not matching. Though I have set `admin` as username and password in all config. For now switched to phpunit-selenium for acceptance testing.

**Comment by lucatume** [comment]
there must be something not correct in your config (e.g. leading or trailing whitespaces); did you set the `adminUsername` and `adminPassword` configuration parameters to **exactly** the same parameters used in your test WordPress installation?
