### ISSUE TITLE
PHP 7 warning about incompatible declaration of ExtendedDbDriver::create

### ISSUE THREAD

**Issue by kouratoras** [lucatume/wp-browser#117]
PHP 7 throws a warning about incompatible declaration of `Codeception\Lib\Driver\ExtendedDbDriver::create`, as an argument is missing. 

```
Warning: Declaration of Codeception\Lib\Driver\ExtendedDbDriver::create($dsn, $user, $password)
should be compatible with Codeception\Lib\Driver\Db::create($dsn, $user, $password, $options = NULL)
in /vendor/lucatume/wp-browser/src/Codeception/Lib/Driver/ExtendedDbDriver.php on line 10
```

**Comment by lucatume** [comment]
Thanks for reporting the issue, I'm fixing it now.

**Comment by lucatume** [comment]
I've closed the issue as I've fixed the code on `master`; I do appreciate your PR though (I've just copy and pasted your stuff really).
