### ISSUE TITLE
How to add new methods to WPTestCase?

### ISSUE THREAD

**Issue by rahularyan** [lucatume/wp-browser#119]
Hello,
I want to add few methods to `\Codeception\TestCase\WPTestCase` but really unsure how to start with it. I checked all docs on extending modules and helpers.
I always get undefined method. My be I am doing something wrong. Can you please tell me how to add add this method:

```
public function go_to_question( $id ) {
	$this->go_to( site_url( "?post_type=question&p=$id" ) );
}
```
to:
 `\Codeception\TestCase\WPTestCase` 

I also tried adding it to _support/WpunitTester.php and build it but it says 0 methods added.

Thank you for your help.

**Comment by lucatume** [comment]
Hi there, no need to add those to the `WPTestCase` class; add those to your base test case (a class extending `WPTestCase`), e.g.:

```php
class MyBaseTest extends \Codeception\TestCase\WPTestCase {
	public function go_to_question($id){
		$this->go_to(site_url("?post_type=question&p={$id}"));
	}
}
```

Then extend that `MyBaseTest` in all your other test cases:

```php
class MyRealTest extends MyBaseTest {
	// ...your test code
}
```

Better yet: use traits to break free from the shakles of class inheritance:

```php
trait MyBaseTestMethods {
	public function go_to_question($id){
		$this->go_to(site_url("?post_type=question&p={$id}"));
	}
}
```

And: 

```php
class MyRealTest extends WPTestCase {
	use MyBaseTestMethods;
	
	// ...your test code
}
```
