### ISSUE TITLE
Is it possible to use WP_UnitTest_Factory methods in WPWebDriver

### ISSUE THREAD

**Issue by rahularyan** [lucatume/wp-browser#120]
Hello,
I am running UI test in browser using WPWebDriver and I want to know is it possible to call `WP_UnitTest_Factory` methods like `create_many`, `create_object`?

Thanks for your help.

**Comment by lucatume** [comment]
Hi there,

No need to use the factory there, the `WPWebDriver` module provides a wealth of methods like `havePostInDatabase` and `haveManyPostsInDatabase`; use the IDE inspection tools to find them out.
If you *really* need the factory from the Core suite use the `WPLoader` module with `loadOnly` set to `true` (see [here](https://github.com/lucatume/wp-browser#wploader-configuration)) and then use the `factory` method to access it.

The former is the suggested approach.

**Comment by rahularyan** [comment]
Thanks a lot. You really did a great job by creating wp-browser.

**Comment by lucatume** [comment]
You are welcome and thanks.
