### ISSUE TITLE
If codecept is interrupted during WP install the db is corrupted

### ISSUE THREAD

**Issue by Mte90** [lucatume/wp-browser#122]
After analyzing seems that when codecept is interrupted during the installation the database is started to be filled but is not finished.
In that way at next run codecept detect that the db is installed but not complete and there is an error.

Only cleaning all the tables in the database fix the issue.

**Comment by lucatume** [comment]
Thanks for reporting this: I will look into it.

**Comment by lucatume** [comment]
I was not able to reproduce this specific issue in any way; the rough solution could be to wipe the test database clean before each `WPLoader` module-using test; it could be made as a "smart" drop that would only remove the test tables (using the `table_prefix` to find them).
I will test this in a branch, my previous attempt at it was a failure, and let you know.

**Comment by Mte90** [comment]
Thank you!
For any testing I am available.
