### ISSUE TITLE
wpcept.phar

### ISSUE THREAD

**Issue by mipon** [lucatume/wp-browser#13]
Hello,

Thanks for the hard work.

What about a phar file for this extension? I guess it is easier than using it with composer.

**Comment by lucatume** [comment]
Hi,

Thank you. 

WP-Browser is not a stand alone software and would require Composer to work in any case, I'm not that knowledgeable in phar format: any good idea/lead?

Luca

**Comment by mipon** [comment]
Phar allows you to pack all the dependency into a single phar file. 

I've successfully created a phar file of your extension using [Box](https://github.com/box-project/box2).

What I did:
- Installed [Box](https://github.com/box-project/box2) and registered the `box` command on the system. 
- Checked out your repository to a local directory and downloaded all the dependencies using Composer into the directory. The structure looked like

```
    - wpcept 
        - src
        - tests
        - vendor
        - wpcept
        - wpcept.bat
        ... continues
```

- Created a Box configuration file named `box.json` in that directory with the followings

```
{
    "files" :["autoload.php"],
    "directories": ["src", "vendor"],
    "main": "wpcept",
    "output": "wpcept.phar",
    "stub": true
}
```
    
- `cd` to the directory and ran 

```
$ box build
```

It produced a file named `wpcept.phar` with the size of about 14mb. 

With the file, now I can do 

```
$ php wpcept.phar --version
```

**Comment by lucatume** [comment]
That is a fine thing!

Question: dependencies would be "frozen" in the phar file, how to cope with
daily dependencies updating? Do you know of a way to automate the phar
creation on a cron base (like 2/day)?

I'm not opposed to any idea: I am just ignorant in the matter.
ᐧ

On Fri, Mar 13, 2015 at 10:45 AM, mipon <notifications@github.com> wrote:

> Phar allows you to pack all the dependency into a single phar file.
>
> I've successfully created a phar file of your extension using Box
> <https://github.com/box-project/box2>.
>
> What I did:
>
>    - Installed Box <https://github.com/box-project/box2> and registered
>    the box command on the system.
>    - Checked out your repository to a local directory and downloaded all
>    the dependencies using Composer into the directory. The structure looked
>    like
>
>     - wpcept
>         - src
>         - tests
>         - vendor
>         - wpcept
>         - wpcept.bat
>         ... continues
>
>
>    - Created a Box configuration file named box.json in that directory
>    with the followings
>
> {
>     "files" :["autoload.php"],
>     "directories": ["src", "vendor"],
>     "main": "wpcept",
>     "output": "wpcept.phar",
>     "stub": true
> }
>
>
>    - cd to the directory and ran
>
> $ box build
>
> It produced a file named wpcept.phar with the size of about 14mb.
>
> With the file, now I can do
>
> $ php wpcept.phar --version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucatume/wp-browser/issues/13#issuecomment-78891324>.
>



-- 
Luca

**Comment by mipon** [comment]
I don't know. You may be interested in how Codeception developers are doing as Codeception also relies on some dependencies.

I think it will be a good option for the user to have an application in a static manner because if one of the dependencies has a breaking change, the application may break. If that happens and the maintainer is on a vacation or something and the repository cannot be updated, the users will have no choice but a broken application until the maintainer comes back.

Another benefit of having a phar application is that tests will supposedly run faster on CI as downloading a single file should be faster than checking out all the dependencies.

One problem I can think of doing this is licensing. If the distributing phar file includes GPL licensed programs, it may need to be licensed under GPL or a compatible license type.

**Comment by lucatume** [comment]
Ok, will look into it but not in the short time span. Good lead about Codeception though: thanks.

**Comment by mipon** [comment]
Looking forward to it.

**Comment by lucatume** [comment]
I will close this until someone comes forward with a working proposal.
