### ISSUE TITLE
Bug in WPTestCase.php _backup_hooks()

### ISSUE THREAD

**Issue by zlinke77** [lucatume/wp-browser#134]
I am receiving the following error:

Fatal error: __clone method called on non-object in /app/public/dev/tests/vendor/lucatume/wp-browser/src/Codeception/TestCase/WPTestCase.php on line 257

It's the same issue as https://github.com/lucatume/wp-browser/issues/108

I used that fix on the WPTestCase.php file and it now works

**Comment by lucatume** [comment]
What version of WordPress are you running tests for?

**Comment by lucatume** [comment]
>I used that fix on the WPTestCase.php file and it now works

Which fix? Could you link or report it here?

**Comment by zlinke77** [comment]
I'm using Wordpress 4.6.1. Here is the fix that also works for WPTestCase.php https://github.com/lucatume/wp-browser/pull/109/commits/680e1bf42155d2c6722ca0cf93b97fa73f379da5

**Comment by lucatume** [comment]
The code you linked is in wp-browser current version: [here](https://github.com/lucatume/wp-browser/blob/1.22.4/src/includes/testcase.php#L237) and [here](https://github.com/lucatume/wp-browser/blob/1.22.4/src/includes/testcase.php#L267).
So... is that working or not? I'm not sure I'm following here...

**Comment by zlinke77** [comment]
I just created a pull request https://github.com/lucatume/wp-browser/pull/136. This applies the same fix to `src/Codeception/TestCase/WPTestCase.php` that was applied to `src/includes/testcase.php` that you referenced in your previous comment.

**Comment by lucatume** [comment]
Thanks for your PR and for your patience. I had a moment of dumped core in my brain.

**Comment by zlinke77** [comment]
Than you so much for your work! wp-browser is an amazing build!! :)
