### ISSUE TITLE
something wrong with composer

### ISSUE THREAD

**Issue by javigomez** [lucatume/wp-browser#14]
I was trying to get your library and got this:

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for lucatume/wp-browser master@dev -> satisfiable by lucatume/wp-browser[dev-master].
    - lucatume/wp-browser dev-master requires badcow/lorem-ipsum dev-master -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```

**Comment by lucatume** [comment]
seems to be an issue with package resolution: try requiring the `badcow/lorem-ipsum` package before wp-browser. Poor man's patch but should work while I further investigate the issue

**Comment by javigomez** [comment]
Thanks for the fast reply ^_^

doing this works:

```
...
	"require-dev": {
      "codeception/codeception": "*",
      "badcow/lorem-ipsum": "dev-master",
      "lucatume/wp-browser": "dev-master"
``

**Comment by lucatume** [comment]
Meh,

will look into that.

**Comment by lucatume** [comment]
I've not been able to replicate and the issue seems to be gone: still getting that?

**Comment by javigomez** [comment]
Yup, still getting the same unless I add "badcow/lorem-ipsum": "dev-master", before:

![screen shot 2015-06-04 at 13 43 00](https://cloud.githubusercontent.com/assets/1375475/7983278/ea028dda-0abe-11e5-8c76-e1f93ac129c9.png)

**Comment by firejdl** [comment]
I am having the same issue.

**Comment by lucatume** [comment]
I've removed the dependency and the issue should be fixed.
