### ISSUE TITLE
PHPUnit not found

### ISSUE THREAD

**Issue by VBEnrico87** [lucatume/wp-browser#146]
Hi,

I've installed WP-browser 1.21 on a clean project folder, following the github instructions.

When I try to run the command "./vendor/bin/codecept run acceptance" I get this error message:

PHP Fatal error:  Class 'PHPUnit\Runner\Version' not found in /home/.../testing/vendor/codeception/codeception/src/Codeception/Command/Run.php on line 244

I'm using:

Linux Mint
PHP 5.0
Composer

Thanks,
Enrico

**Comment by lucatume** [comment]
Hi there, thanks for reporting the issue.
That's an issue I'm working right now to resolve, could you please post, from the `composer.lock` file, the installed versions of:

* `phpunit/phpunit`
* `codeception/codeception`
* `lucatume/wp-browser`
* `codeception/phpunit-wrapper`

Also your exact PHP version.

Thanks,

**Comment by lucatume** [comment]
As a further experiment: could you try to explicitly require version `1.22.6.1` of wp-browser?
The command is `composer require --dev lucatume/wp-browser:1.22.6.1`

**Comment by lucatume** [comment]
Hi, after much thinking I've decided to support PHP 5.6 in the v1 branch (`php-56-compat`), update your `composer.json` file to require `lucatume/wp-browser:^1.23`.
