### ISSUE TITLE
[Error] Class 'WPAjaxDieStopException' not found

### ISSUE THREAD

**Issue by rahularyan** [lucatume/wp-browser#156]
Hello @lucatume,
In newer version all ajax tests are broken which were working in earlier version.
```
[Error] Class 'WPAjaxDieStopException' not found
```

**Comment by lucatume** [comment]
Hi, thanks @rahularyan for reporting this: I will look into it, for the time being a quick fix might be to include the `/src/includes/exceptions.php` file in your tests.

**Comment by rahularyan** [comment]
Thanks,

I will try that.
________________________________

**Comment by rahularyan** [comment]
Manually included. Now working. Thanks

**Comment by lucatume** [comment]
Fixed in `2.0.5.2`
