### ISSUE TITLE
[TypeError] Argument 3 passed to PHPUnit\Framework\Assert::assertThat()

### ISSUE THREAD

**Issue by rahularyan** [lucatume/wp-browser#157]
Hello @lucatume,
I noticed one more issue today in newer version. When I test:

```$I->see( 'Posts', [ 'css' => '.nav-tab-wrapper a' ] );```

Then I get the below error:

```[TypeError] Argument 3 passed to PHPUnit\Framework\Assert::assertThat() must be of the type string, array given, called in \vendor\codeception\codeception\src\Codeception\Util\Shared\Asserts.php on line 289```

Element `.nav-tab-wrapper a` will return array as there are multiple `a` tags. So I think, it will be better if you can check for array in `$I->see`.
Thanks

**Comment by lucatume** [comment]
`$I->see` is a [Codeception](http://codeception.com/ "Codeception - BDD-style PHP testing.") method, not a wp-browser one, please open an issue on Codeception.
