### ISSUE TITLE
Startup lag time on VVV

### ISSUE THREAD

**Issue by Mte90** [lucatume/wp-browser#159]
Using VVV 2.1 (https://github.com/Varying-Vagrant-Vagrants/VVV) that access on the webserver and mysql the lag time on boot up is very very slow.

I am launching `codecept` from my debian machine that is running PHP 7.2 but is not enough to avoid issues from this point of view.

**Comment by lucatume** [comment]
This is a drag indeed; I will look into this, thanks for reporting it.

**Comment by Mte90** [comment]
Seems more a problem in VVV https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1464
