### ISSUE TITLE
Init overwrites existing .env

### ISSUE THREAD

**Issue by ptrkcsk** [lucatume/wp-browser#161]
`Codeception\Template\WpBrowser::createEnvFile()` [writes `.env` without checking if it already exists](https://github.com/lucatume/wp-browser/blob/2.1.2/src/Codeception/Template/Wpbrowser.php#L485).

First, I wonder if I'm using wp-browser as intended: Is wp-browser intended to be initialized at the root of the WP application, or individually per plugin/theme?

I work on a project for which wp-browser was initialized at the root of our WP application. If we had initialized it after the new `.env` templating feature was introduced, wp-browser would have overwritten our existing and substantial `.env`.

If it's intended for wp-browser to be initialized individually per plugin/theme, I think it's possible `.env` could already exist.

**Comment by lucatume** [comment]
Fixed in `2.1.3`, thanks for reporting it!

**Comment by ptrkcsk** [comment]
Thanks for addressing it so quickly! I'm looking forward to trying it out.

**Comment by lucatume** [comment]
Due to limits imposed by Codeception templating system I was not able to implement hte `--env-name` option, but added that as an explicit question in the guided setup.
