### ISSUE TITLE
Running endor/bin/codecept init wpbrowser in plugin fails

### ISSUE THREAD

**Issue by dingo-d** [lucatume/wp-browser#167]
I added `"lucatume/wp-browser": "*"` in my plugins `composer.json` and it installs ok, when I run `composer install`, but when I try to run

```bash
vendor/bin/codecept init wpbrowser
```

I get 

```bash
In Finder.php line 547:

The "public_html/wp-content/plugins/my-plugin/tests" directory does not exist.
```

Any idea why?

When I ran codeception bootstrap with

```bash
vendor/bin/codecept bootstrap
```

That worked fine and created the tests folder.

Should I run bootstrap first? Because there's nothing about that in the [documentation](https://codeception.com/for/wordpress)

**Comment by dingo-d** [comment]
Ok, I deleted the vendor file and `composer.lock` and installed again and it worked.

**Comment by lucatume** [comment]
I love this kind of issues (the self-solving ones).

Let me know if you need help with anything else.
