### ISSUE TITLE
Impossible to inject JS in the acceptance test

### ISSUE THREAD

**Issue by hive-4-apps** [lucatume/wp-browser#168]
I´m trying to confirm a popup. As you know it´s impossible to use the parameter `acceptPopup` with phantomjs. I saw one solution could be to execute JS like this : 
    `$js_confirm = 'window.confirm = function(){ return true; }';
    $I->executeJS($js_confirm);
    $I->executeJS("return window.confirm");`

But, inside my AcceptanceTest I don´t get the access to the `executeJS `method. How can I fix this ?

**Comment by lucatume** [comment]
Could you post your Codeception, wp-browser and PHP version?
Please provide your suite configuration as well and the Codeception one if relevant.

**Comment by hive-4-apps** [comment]
Versions :
wp-browser-commons : ^1.2.5
codeception/codeception : 2.4.0
php on WampServer : 5.6

codeception.dist.yml
---------------------------------------------------------------------------------------------------------
    
    actor: Tester
    paths:
        tests: tests
        log: tests/_output
        data: tests/_data
        helpers: tests/_support
    settings:
        bootstrap: _bootstrap.php
        colors: true
        memory_limit: 1024M
    params:
        - .env
    wpFolder: '%WP_ROOT_FOLDER%'
    extensions:
        enabled:
            - Codeception\Extension\Phantoman
            - tad\WPBrowser\Extension\Copier
        config:
            Codeception\Extension\Phantoman:
                path: '%PHANTOMJS%'
                port: 4444
                suites: ['phantomjs']
            tad\WPBrowser\Extension\Copier:
                files:
                   'tests/_data/themes/dummy': '%WP_ROOT_FOLDER%/wp-content/themes/dummy'
                   'tests/_data/plugins/mu-plugin-1': '%WP_ROOT_FOLDER%/wp-content/plugins/mu-plugin-1'
                   'tests/_data/plugins/wp-group-subscriptions': '%WP_ROOT_FOLDER%/wp-content/plugins/my-plugin'
                   'tests/_data/plugins/test': '%WP_ROOT_FOLDER%/wp-content/plugins/test'

-----------------------------------------------------------------------------------------------------------

acceptance.suite.dist.yml
-----------------------------------------------------------------------------------------------------------

    # perform tests in browser using the WebDriver or PhpBrowser.
    # If you need both WebDriver and PHPBrowser tests - create a separate suite.

    class_name: AcceptanceTester
    modules:
        enabled:
            - WPBrowser
            - WPDb
            - AcceptanceHelper
            - WPFilesystem
        config:
            WPLoader:
                wpDebug: true
                plugins: ['my-plugin/MyPlugin.php']
                activatePlugins: ['my-plugin/MyPlugin.php']
            WPBrowser:
                url: '%WP_URL%'
                adminUsername: 'admin'
                adminPassword: 'admin'
                adminPath: '/wp-admin'
            WPDb:
                dsn: 'mysql:host=%DB_HOST%;dbname=%DB_NAME%'
                user: %DB_USER%
                password: %DB_PASSWORD%
                dump: 'tests/_data/dump.sql'
                populate: false
                cleanup: false
                reconnect: false
                url: '%WP_URL%'
                tablePrefix: 'wp_'
            WPFilesystem:
                wpRootFolder: '%WP_ROOT_FOLDER%'
                themes: '/wp-content/themes'
                plugins: '/wp-content/plugins'
                mu-plugins: '/wp-content/mu-plugins'
                uploads: '/wp-content/uploads'

-----------------------------------------------------------------------------------------------------------

**Comment by lucatume** [comment]
You are using `WPBrowser` in the suite: that does not support Javascript, from [documentation](https://github.com/lucatume/wp-browser/blob/master/README.md#modules):

>WPBrowser - a PHP based, JavaScript-less and headless browser for acceptance testing not requiring JavaScript support

Use the `WPWebDriver` module instead.

**Comment by hive-4-apps** [comment]
Thank you.

**Comment by hive-4-apps** [comment]
I tried to find something in the documentation or several forums to know how to access to the method executeJS inside my acceptance tester. So the real question is how to get the current WPWebDriver ( in my case : Phantomjs ) loaded my the yml config to use the method executeJS ?

**Comment by lucatume** [comment]
wp-browser builds on [Codeception](http://codeception.com/ "Codeception - BDD-style PHP testing."), as such any Codeception guide will apply.
In particular: the `WPWebDriver` module is an extension of the `WebDriver` one: [see WebDriver module documentation](https://codeception.com/docs/modules/WebDriver) to understand.
When updating a suite module (e.g. by changing the `WPBrowser` module to `WPWebDriver`) remember to rebuild the suites using `codecept build`.

>WPWebDriver - a Guzzle based, JavaScript capable web driver; to be used in conjunction with a Selenium server, PhantomJS or any real web browser for acceptance testing requiring JavaScript support
