### ISSUE TITLE
  java.net.ConnectException: Connection refused: connect

### ISSUE THREAD

**Issue by hive-4-apps** [lucatume/wp-browser#169]
My config:

- Selenium standalone 3.13.0
- chrome driver 2.40

    WPWebDriver:
        url: '%WP_URL%'
        browser: chrome
        adminUsername: 'admin'
        adminPassword: 'admin'
        adminPath: '/wp-admin' 

When I run this test : 

    public function it_should_activate_correctly_plugin( AcceptanceTester $I )
    { 
         $I->loginAsAdmin();
         // or $I->amOnPage('/wp-login.php');
                 
    }

I got always this error : 
    
    [Facebook\WebDriver\Exception\UnknownServerException]
    java.net.ConnectException: Connection refused: connect

I missed something ?

**Comment by lucatume** [comment]
That's an issue related to your Selenium setup, it *seems* that the Selenium server is not listening on the port you have configured Codeception to call, please read more [here](https://codeception.com/11-20-2013/webdriver-tests-with-codeception.html).
I'm closing this issue as it's not related to wp-browser.
