### ISSUE TITLE
  WPBrowser could not be found and loaded

### ISSUE THREAD

**Issue by atwellpub** [lucatume/wp-browser#17]
I'm sorry this is probably not a bug. I am using github and travisci to run Codeception and having a hard time getting my composer installed CodeCeption + WPBrowser to work with an acceptance test. 

I've gotten composer to work fine running the PHPBrowser module.

I have WPBrowser installed in my vendor folder, and I've added the setup data to my acceptance.suite.yml file, is there more I need to do?

#### travis.yml
https://github.com/inboundnow/landing-pages/blob/feature/Refactoring_metabox_modules/.travis.yml#L47-L52

#### composer.json
https://github.com/inboundnow/landing-pages/blob/feature/Refactoring_metabox_modules/composer.json

#### codeception.yml:
https://github.com/inboundnow/landing-pages/blob/feature/Refactoring_metabox_modules/codeception.yml

#### acceptance.suite.yml
https://github.com/inboundnow/landing-pages/blob/feature/Refactoring_metabox_modules/tests/codeception/acceptance.suite.yml

Any guidance is welcome, maybe it will help me help others. 

Also, any recommendations on retrieving remote logs? After the travis build completes I do not have access to the output logs. My tests are passing locally but one is failing remotely and would love to look at the log.

**Comment by lucatume** [comment]
Ok,

Travis really not my plate so I can not answer most of your questions.

What I see is you are symlinking the `WPBrowser` command ([here](https://github.com/inboundnow/landing-pages/blob/feature/Refactoring_metabox_modules/.travis.yml#L50-L51)) in place of the `wpcept` one.

I will label the issue `help wanted` as I'm not the best person to answer.

**Comment by atwellpub** [comment]
I removed the symlink. I was experimenting. So I tried loading the autoload.php file in codeception's  _bootstrap.php and the console log is giving me this error;

Fatal error: Cannot redeclare codecept_debug() (previously declared in phar:///usr/local/bin/codecept/autoload.php:12) in /var/www/inboundtesting.dev/wp-content/plugins/landing-pages/vendor/lucatume/wp-browser/autoload.php on line 15

Maybe you could help me understand if I'm not supposed to call WP Browser's autoload.php file from the bootstrap?

**Comment by lucatume** [comment]
This still an issue? Care to share eventual solution?

**Comment by atwellpub** [comment]
I've lost my understanding of what was going on, but I am using this component in my travis build successfully at the moment:

Here's my Travis file:
https://github.com/inboundnow/landing-pages/blob/master/.travis.yml

Here's my Composer file:
https://github.com/inboundnow/landing-pages/blob/master/composer.json

Here's my codeception yml:
https://github.com/inboundnow/landing-pages/blob/master/codeception.yml

Here's my Codeception bootstrap:
https://github.com/inboundnow/landing-pages/blob/master/assets/tests/codeception/_bootstrap.php

If you want I think it's ok to close issue. Thank you for the follow up and attention too.

**Comment by lucatume** [comment]
Ok, I'm closing the issue but punting this for my reference about CI integration, thank YOU for your time and effort.
