### ISSUE TITLE
Is there a way to cleanup site when using WPBrowser

### ISSUE THREAD

**Issue by essekia** [lucatume/wp-browser#174]
I am running Rest API tests as acceptance tests and was wondering how I should be going about cleaning up the database after each test. For WPDB, cleanup works great.

**Comment by JDGrimes** [comment]
In one of my projects I created a custom module that (among other things) backs up the clean DB before the tests run, and then resets it after each test: https://github.com/WordPoints/dev-lib/blob/develop/wpcept/includes/Modules/WordPointsLoader.php#L295-L336

**Comment by lucatume** [comment]
Hi there,

my approach to that is to use [the `REST` module from Codeception](https://codeception.com/docs/modules/REST) and `WPDb`.
When it comes to cleaning the database between tests I need some more details: WPDb will drop all the db content and re-import the SQL dump before each test. That's fine enough to cover any case but those where the db dump has such dimensions not to allow it.
To move away from a PHP-driven solution WPDb, as an extension of Codeception DB module, allows setting [the `populator` configuration option](https://codeception.com/docs/09-Data#Db) config to, as an example, call `mysql` directly; but `populator` can really be **any** command the host running the tests understands so, at that point, possibilities are limitless.
I've found that able to cover all cases I came across.

Is there anything you found, or I wrote, that does not work for you @essekia? @JDGrimes why the custom module in place of relying on the built-in functionality or `populator`? Asking out of curiosity and to find potential improvements to the project, not to criticise.

**Comment by JDGrimes** [comment]
> @JDGrimes why the custom module in place of relying on the built-in functionality or populator? Asking out of curiosity and to find potential improvements to the project, not to criticise.

It was a few years ago when I built this, so maybe things have changed since then. I don't remember why I chose to do it the way I did off of the top of my head.

**Comment by essekia** [comment]
Yes. Thanks.
