### ISSUE TITLE
Error 500 in functional tests

### ISSUE THREAD

**Issue by lucatume** [lucatume/wp-browser#176]
From: https://github.com/lucatume/wp-browser/issues/87#issuecomment-417798339

> I am facing that issue on functional test, as I can see that is not loading wp-config-test.php file. Changing the values on wp-config with the same settings and they are working.

@Mte90 please provide more details: modules, codeception and wp-browser version, error messages and what you tried.

**Comment by Mte90** [comment]
I copied and paste the settings of `ilikethis` project and get that running.
The problem I saw with that project and his tests is that they doesn't check the output of the methods so I was trying to use other methods to check that output.
I am trying to get confidence with codeception and his documentation but the methods are autogenerated so is not clear for me how to get the methods that I need.

**Comment by lucatume** [comment]
If you are checking the output then it's an acceptance test of sorts; use the `WPBrowser` module for that.
The `WordPress` module requires some knowledge and control not only of WordPress but of the code you are testing too due to WordPress reliance on globals and side-effects.

**Comment by Mte90** [comment]
So I have a rest api that I have to see the output I have to do an acceptance with the browser? It is not too much?

I can do it with a curl call and will require less time to run.
I was thinking that functional cover this cases also on checking the output based on parameters.

**Comment by lucatume** [comment]
WPBrowser is pretty much a curl call with some logic on it.
By "acceptance" I do not mean UI but "asserting as a client with no inner knowledge of the implementation would" -- REST tests are, in this definition, "acceptance" tests. As I said [here](https://github.com/lucatume/wp-browser/issues/176#issuecomment-418364760) you can use the [REST module too](https://codeception.com/docs/modules/REST).
By "functional" I mean "asserting as a developer with inner knowledge and access to the system would".

**Comment by Mte90** [comment]
Ok so is better to use the REST module for rest apis in functional tests.

For the issue of the ticket itself maybe add an alert about the usage of the modules as you explained in functional tests can be a solution?

**Comment by lucatume** [comment]
I suggested using the REST module for an “acceptance” test but that’s just jargon. 
I’ve tried to shy away from suggesting one module over another to avoid “locking” them in the users perception; I’ve used WPBrowswe and WPWebDriver modules in functional tests with success and, in my opinion, with reason.

I’ve laid out my own, personal, take on what “functional” and “acceptance” mean but I do not want to impose that definition on anyone. 

I do agree with you that the documentation, the “thing” I never seem to be able to make time for, could be improved to better answer the questions “at which level does this module work?” and “what are some examples of how this module could be used?”.

Aside from the welcome theoretic discussion, is there any other topic to keep this issue open? If you feel not then, please, close it.

**Comment by Mte90** [comment]
For me the issue can be closed :-)
