### ISSUE TITLE
Codecept commands does nothing

### ISSUE THREAD

**Issue by essekia** [lucatume/wp-browser#178]
Hello Luca,

This is a strange one.

I have been using codeception / wpbrower in a couple of setups successfully, but there is one setup where running any command like:

```
codecept init
codecept run
```

does nothing. No error. Nothing. Just goes to the next command line. Have you seen any cases like this? I can't find anything peculiar about this setup.

1. No global composer package
2. Standard version of wpbrowser / codeception (  Tried with 2.14, 2.15 of wpbrowser with  2.4.5 )
3. I do have the packages installed in the vendor folder
4. Tried with (vendor/bin/codecept)

I have a feeling this could be silly, but could not find any cases like this in previous github issues in wpbrowser / codeception.

**Comment by essekia** [comment]
Sorry about that.

It was something silly, a composer package in fact. I removed other composer packages one by one and this was fixed when one package was removed. Thankfully, I don't need it.

**Comment by lucatume** [comment]
Now I'm curious: what was it?

**Comment by lucatume** [comment]
Guess the issue was the autoloaded main plugin file from `composer.json`, right?
