### ISSUE TITLE
All acceptance tests fail after updating to latest version of WP-Browser

### ISSUE THREAD

**Issue by maxchirkov** [lucatume/wp-browser#18]
I decided to update to the latest version of wp-browser and codeception, since my lock file hasn't been refreshed since February (was still on codeception 2.0.1). After updating, all my acceptance tests fail and I'm getting this fatal error at the end:

```
FATAL ERROR. TESTS NOT FINISHED.
Call to undefined function Codeception\Subscriber\codecept_relative_path() 
in /.../vendor/codeception/codeception/src/Codeception/Subscriber/Console.php:305
```

All screenshots in `/tests/_output/` display WordPpress standard 404 page. Any ideas on how to get it to work?

**Comment by maxchirkov** [comment]
Oh, but, I was getting this error: https://github.com/lucatume/wp-browser/issues/12#issuecomment-134643037 and the only way I was able to install the latest version is with this composer config:
```
    "require": {
        "badcow/lorem-ipsum": "^1.1"
    },
    "require-dev": {
        "lucatume/wp-browser": "master-dev"
    }
```

**Comment by lucatume** [comment]
That issue should be fixed now, I've fired up several projects just requiring wp-browser with no issues.
As per the tests that seems to be a breaking change to codeception code that's been updated rarther than WP Browser code.

Could you post one to have context?

**Comment by maxchirkov** [comment]
Here's an example of one of the tests:

```php
function it_should_activate_and_deactivate_plugin_while_membership_is_inactive(AcceptanceTester $I)
    {
        $I->loginAsAdmin();
        $I->amOnPluginsPage();

        $I->deactivateMembershipIfActive();

        $I->wantTo('activate and deactivate the plugin while Membership is Inactive.');

        $I->seePluginInstalled(self::$pluginSlug);
        $I->activatePlugin(self::$pluginSlug);
        $I->seePluginActivated(self::$pluginSlug);
        $I->deactivatePlugin(self::$pluginSlug);
        $I->seePluginDeactivated(self::$pluginSlug);
    }
```
The test fails while screenshot shows default WP front-end 404 page. This test was passing with no issues for the last year.

**Comment by lucatume** [comment]
Still having that issue?
