### ISSUE TITLE
Possible to separate my plugin from the test framework?

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-browser#183]
Hi Luca,

Is it possible to separate my plugin from the test framework, as to minimize the overhead for the final user?

All the best,
Lucas

**Comment by Luc45** [comment]
Hi,

I've come up with a solution. Let me know if you think it's a good one.

I've created another branch called "svn". In this branch, I've deleted all composer dependencies, tests folder and everything that is not strictly necessary in production.

I will develop from the master, and deploy to WordPress from this branch.
I've also created release tags based on the "svn" branch.

All the best,
Lucas

**Comment by lucatume** [comment]
Hi,

yep, that's the approach I would take. The path of separating code from the tests usually leads to the tests being abandoned.
