### ISSUE TITLE
Change action used to activate plugins?

### ISSUE THREAD

**Issue by barryhughes** [lucatume/wp-browser#20]
Hey @lucatume!

Re this [section of code](https://github.com/lucatume/wp-browser/blob/master/src/Module/WPLoader.php#L200) - if we activate plugins on `muplugins_loaded` then various bits and bobs won't yet have been initialized by WP. 

For instance, the global WP_Rewrite object hasn't yet been instantiated (can lead to problems when it's needed - even indirectly like if plugin code registers a post type upon activation). Might `wp` (or some other later point in the request) be a better action for this?

`tests_add_filter( 'wp', [ $this, 'activatePlugins' ] );`

**Comment by lucatume** [comment]
Hooking at `muplugins_loaded` is a fairly common practice and one honoring WordPress real loading sequence. To point out some authoritative test code: [posts-to-posts bootstrap file](https://github.com/scribu/wp-posts-to-posts/blob/master/tests/bootstrap.php#L12).  
Furthermore the standard WordPress component loading flow loads plugins right after mu-plugins as can be seen in the [wp-settings.php file](https://github.com/WordPress/WordPress/blob/master/wp-settings.php#L201).  
Delaying that call would mean creating artificial conditions for the plugin existing in the test environment only.
There is, though, something happening between the `muplugins_loaded` and the `plugins_loaded` hook and it might be worth exploring the possibility to have the plugins loaded in a similar fashion

```php
tests_add_filter( 'plugins_loaded', [ $this, `activatePlugins` ], PHP_INT_MIN );
```
aka "very very early in the hook".

**Comment by barryhughes** [comment]
Just to clarify, my suggestion wasn't to change when plugins are *loaded* - it was to change the hook on which they are _activated._

I'd also agree `wp` may not be the best action either (though it works) - `wp_loaded` is probably better. Here's my take on the expected sequence of events:

* `wp-load.php` bootstraps WordPress
* `wp-config.php` is included by `wp-load.php`
* `wp-settings.php` is included by `wp-config.php`
** `muplugins_loaded` fires
** `plugins_loaded` fires
** Various key objects are now instantiated (including the `$wp_rewrite` global)
** `wp_loaded` fires (at this point, we're right at the end of `wp-settings.php`)
* The next thing we are interested in is the call to `activate_plugin(...)` which is responsible for firing the `activate_{plugin}` hook

**Comment by lucatume** [comment]
It makes total sense and I think you are right.
I'm looking into it and will address this shortly, thanks for pointing it out.

**Comment by lucatume** [comment]
I've updated the code to move the plugin activation to the `wp_install` hook. This should take care of the plugin activation issue and give activating plugins the environment those need.
