### ISSUE TITLE
Suggestion: move readme.md contents to GitHub wiki

### ISSUE THREAD

**Issue by unfulvio** [lucatume/wp-browser#206]
The `readme.md` file of this project is rather large and updating very often.

Feels to me it would be more appropriate to keep it to a minimum and move its actual contents to a full fledged wiki, for better organization. 

I'd volunteer to help splitting the readme contents across GH wiki pages, if you like the idea. A possibly even better idea could be using GitHub pages, but perhaps it's unnecessary and you don't need things like JS examples. It would just make the project look more "cool" I suppose. Wiki would be easier to maintain, maybe.

If you prefer the current structure, please ignore and close this issue. Thanks.

**Comment by lucatume** [comment]
I really appreciate your offer, thanks.

I had exactly the same idea and registered a gitbook account that is, for the time being, empty while I try to make timemfor it: [https://docs.wpbrowser.academy/wp-browser/](https://docs.wpbrowser.academy/wp-browser/).
I'm currently working on a more detailed documentation and would like to work on more examples, less setup-oriented but re-organizing what's there already would not hurt anyone and would, instead, provide a base for that documentation.
Since gitbook, and pretty much any other system, consumes Markdown the first step could be "breaking" the current documentation into separate .md docs in the `/docs` folder. Leaving the table of contents in the README, as a first step, seems reasonable.
Aside from "manual" work I could also really use the feedback about the documentation (what's missing, what's difficult to read, misleading and the like).
Any help in this context is very much appreciated.

**Comment by unfulvio** [comment]
Right now I have a feeling that the readme is easier to consume for someone who is already familiar with Codeception. Sure, WP Browser is based on Codeception, but not necessarily folks are already familiar with it when they first research acceptance testing in WordPress.

I was only familiar with PHP Unit for example, and my first venture in acceptance kingdom was straight with WP Browser because I had to test for acceptance some WooCommerce plugin. Given that WordPress generally requires a whole different approach to testing in general, you may expect more people sharing my same profile. The biggest roadblock for me in getting a test suite to work was always environment setup, not so much writing tests, which is always fun and more straightforward.

With that in mind, I'd try to start off with some introduction and explaining what WP Browser does, why, what you can do with it, what you can't, how it works to solve a problem. What is required (something you explain later when moving onto setup, but perhaps even that could be organized a bit differently). The modules descriptions and scope could be expanded a bit further, along with some (non code) examples.

In the end you provide a lot of these, I feel like that simply organizing the same content into multiple pages and subdivide each page in chapters, with better formatting, headings etc, it would just make a great difference for readability.

I'd start just with that, breaking content apart, creating a page for each topic. When the page grows too big, break it down into sub pages (this pattern feels familiar lol...). And there you have an index.

**Comment by lucatume** [comment]
Documentation is my current effort focus and I’m working on it in a branch that I’ve not pushed. 
I’m setting up to auto-document the methods, along with some example usages, of each module.
To keep that work visible I will push that branch, in its current state, and link it back here. 

Setup has always been the pain point of the whole process (as is for pretty much any non trivial tdd setup) and while the general guidelines are always the same (Where is WordPress? Where is the db?) the specifics of each setup will vary.
Here’s a quick, non complete, matrix of the setups I configured and ran wp-browser on:
* environments
    - CI (e.g Travis, Circle CI, others)
    - local (php server, MAMP, WAMP, Valet, others)
    - virtual box (Homestead, VVV, others)
    - Docker as guest (run tests from the host against the container)
    - Docker as host and guest (run the tests from within the container)
* setups
   - default WP structure
   - Bedrock
   - any possible combination of folders
   - Composer-managed
   - others
* targets
   - plugin
   - theme
   - site

Combine all these and you get an idea of some of the possible combinations. 
This is not to say that a documentation about setups is useless but, having used all of those, I could use help spotting the ones that:
* are widely used
* are probably used by people trying their hands at wp-browser and/or testing for the first time.

Can you list 3 combinations you would think would have the biggest documentation impact?

There is, then, the fact that I’d like to avoid having to duplicate Codeception documentation; while repetitions might help that also take maintenance effort. 

Again: any help, especially with the perspective of someone that just started using the suite, is very welcome.

One last point that comes up every now and then is: can’t wp-browser have a discovery feature looking around and detecting it all? I guess it could provided the effort of building and maintaining it. To this day I could not make the time for it.

**Comment by lucatume** [comment]
Here's the branch I'm working on: https://github.com/lucatume/wp-browser/pull/207
Related to this PR: https://github.com/victorjonsson/PHP-Markdown-Documentation-Generator/pull/19 and https://github.com/lucatume/PHP-Markdown-Documentation-Generator/tree/feature/output-formatters

**Comment by lucatume** [comment]
Documentation has been moved to [https://wpbrowser.wptestkit.dev](https://wpbrowser.wptestkit.dev).
