### ISSUE TITLE
Cest format dependency Injection

### ISSUE THREAD

**Issue by cookiesowns** [lucatume/wp-browser#24]
We have a project currently that is built ontop of WordPress with codeception as our testing framework.

Currently we are extending each test class with our own WP_UnitTestCase module ( essentially a copy and paste ).

Unfortunately this method does not allow us to perform dependency injection as it appears the codeception framework doesn't pick up on our test case...

Will wp-browser allows us to perform dependency injection without writing test's using the NameOfClassCest ?

Or is the power of codeception's dependency injection lost for us mortals using WordPress unit testing?

**Comment by lucatume** [comment]
Could you post the test class  code?
CEST classes are meant to be used in acceptance tests: how is that related to the `WP_UnitTestCase` class?

**Comment by lucatume** [comment]
latest version of the module (`1.7.13`) modified the Codeception test case extension ot the `WP*TestCase` classes: let me know if this is still an issue.

**Comment by cookiesowns** [comment]
Will give it a go when some free time to go back to our testing framework clears up.

Does this modification allows us to the Cest dependency injection format with WP*TestCases using the WP-Browser framework?

If so that is incredible!

**Comment by lucatume** [comment]
Yes, it should. That's one of the points of the latest update. Keep me up to date as I'm very interested.

**Comment by lucatume** [comment]
Any news on this front?

**Comment by lucatume** [comment]
I'm closing the issue due to lack of activity, open a new issue when and if it shows up again
