### ISSUE TITLE
[FEATURE REQUEST]Allow to configure timeout of Process

### ISSUE THREAD

**Issue by mickaelperrin** [lucatume/wp-browser#250]
**Is your feature request related to a problem? Please describe.**
I test a code generation tool which is invoked through a WP CLI command. The process may run for more than 60s which is the default timeout of the Symfony Process object.

**Describe the solution you'd like**
https://github.com/lucatume/wp-browser/blob/8a967ff5132547775cf67c2ebf0081389ea98402/src/tad/WPBrowser/Environment/Executor.php#L50-L51
Add a configuration parameter and invoke `->setTimeout(XX)` on object, or use it directly in the constructor.

Thanks,

PS: wow 0 Issue for that kind of project, well done ;)

**Comment by lucatume** [comment]
Version `2.2.10` should include this setting, let me know if it works correctly.

> PS: wow 0 Issue for that kind of project, well done ;)

Thanks, much appreciated.
