### ISSUE TITLE
[DOC REQUEST] Create helpers that use native wordpress/plugins functions

### ISSUE THREAD

**Issue by mickaelperrin** [lucatume/wp-browser#258]
**Did you search the documentation first?**
Yes ;)

**What do you think is missing from the documentation?**
Explanations on how to write custom helpers codeception functions that use WordPress native or plugins related functions.
For example, I would like to use the function provided by woocommerce, like `wc_create_new_customer`, `wc_create_order`...

**Comment by lucatume** [comment]
Hi,

Thanks for reporting this.
In the context of integration tests, in a suite using the `WPLoader` module, if you load the plugins or themes defining the functions (e.g. woocommerce in your example) using the `plugins` and `activatePlugins` parameters, then the functions and classes will be available. 

Does this not work?
Maybe the documentation is lacking in explaining this?

**Comment by mickaelperrin** [comment]
Hi,
Thanks for the quick answer.
At the moment I tried in acceptance / functional tests, not in wpunit tests.
Should it work also in that kind of tests without any specific configuration ?

**Comment by mickaelperrin** [comment]
Some more materials:
- File: `_support/Helper/Wpunit.php`
```
<?php
namespace Helper;

class Wpunit extends \Codeception\Module {
	public function createANewCustomer() {
		\wc_create_new_customer('dev@domain.tld', 'testaccount', 'testpassword', [] );
	}
}
```

- File: `wpunit/newWooUserCest.php`
```
<?php 

class newWooUserCest
{
    public function _before(WpunitTester $I) {
    }
    
    public function tryToTest(WpunitTester $I) {
    	$I->createANewCustomer();
    }
}
``

- Config:

```
actor: WpunitTester
modules:
    enabled:
        - WPLoader
        - \Helper\Wpunit
    config:
        WPLoader:
            wpRootFolder: "%WP_ROOT_FOLDER%"
            dbName: "%TEST_DB_NAME%"
            dbHost: "%TEST_DB_HOST%"
            dbUser: "%TEST_DB_USER%"
            dbPassword: "%TEST_DB_PASSWORD%"
            tablePrefix: "%TEST_TABLE_PREFIX%"
            domain: "%TEST_SITE_WP_DOMAIN%"
            adminEmail: "%TEST_SITE_ADMIN_EMAIL%"
            title: "Test site"
            pluginsFolder: "../app/plugins"
            plugins:
                - myplugin/myplugin.php
            activatePlugins:
                - woocommerce/woocommerce.php
                - dkod-framework/dkod-framework.php
                - advanced-custom-fields-pro/acf.php
```

- Result:
1) newWooUserCest: Try to test
 Test  tests/codeception/wpunit/newWooUserCest.php:tryToTest

  [Error] Call to undefined function wc_create_new_customer()

**Comment by lucatume** [comment]
In integration tests it should work as I’ve described. 

I t he context of acceptance tests you can:
1. Setup the suite to use the `WPDb` module…
2. To load a database dump in which the plugin, or theme, you’re testing is activated and, along with it, the plugins you need to test with (e.g. WooCommerce)
3. In the suite load and configure the `WPLoader` module to only load, see https://wpbrowser.wptestkit.dev/summary/modules/wploader

The plugin functions will then be available in the acceptance suite too.

**Comment by lucatume** [comment]
In integration tests do not create a module, I’d create a trait and use its methods in a Test class extending the `WPTestCase` to setup the fixture you need in the `setUp` method.

**Comment by mickaelperrin** [comment]
Yeah, that's what I planned to do, but I just wanted to do a quick and dirty test. Should it behave differently with a custom `WPTestCase` ?

**Comment by mickaelperrin** [comment]
Are there known issues/incompatibilities with `autoload` and `WPLoader` ?

I have required `WP_CLI` has a composer dependency and the autoload is registered at the start of `wp-config.php`.

It used in the tests to determine the environment type (develop, staging, production...). So, before DB credentials are set.

 The test fails with:

```
FATAL ERROR. TESTS NOT FINISHED.
Uncaught Error: Class 'WP_CLI' not found in /src/config/environment.php:6
Stack trace:
#0 /src/library/Thms/Config/Environment.php(40): Codeception\Module\WPLoader->{closure}()
#1 /src/bootstrap.php(32): Thms\Config\Environment->which('4c414bdf7152')
#2 /src/wp-config.php(8): require_once('/src/bootstrap....')
#3 /src/www/wp-load.php(42): require_once('/src/wp-config....')
#4 /src/vendor/lucatume/wp-browser/src/Codeception/Module/WPLoader.php(433): include_once('/src/www/wp-loa...')
#5 /src/vendor/lucatume/wp-browser/src/Codeception/Module/WPLoader.php(314): Codeception\Module\WPLoader->bootstrapWP()
#6 /src/vendor/symfony/event-dispatcher/EventDispatcher.php(260): Codeception\Module\WPLoader->_loadWordpress(Object(Codeception\Event\SuiteEvent), 'suite.before', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 /src/vendor/symfony/event-dispatcher/EventDispatcher.php(235): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'suite.before', Object(Codeception\Event\SuiteEvent))
#8 /
in /src/config/environment.php:6
  WordPress status: {
      "constants": {
          "ABSPATH": "/src/www/",
          "WP_DEFAULT_THEME": "not set",
          "WP_CONTENT_DIR": "not set",
          "WP_PLUGIN_DIR": "/src/app/plugins",
          "WP_HOME": "not set",
          "WP_SITEURL": "not set",
          "WPMU_PLUGIN_DIR": "not set",
          "DB_HOST": "mysql",
          "DB_NAME": "wpunit",
          "DB_PASSWORD": "password",
          "DB_USER": "root",
          "CUSTOM_USER_TABLE": "not set",
          "CUSTOM_USER_META_TABLE": "not set",
          "DISABLE_WP_CRON": "not set"
      },
      "globals": {
          "table_prefix": "wp_ (guessed, global not set)"
      },
      "checks": {
          "Site is multisite": "no",
          "ABSPATH points to valid WordPress directory": "Yes, wp-load.php file found in WordPress root directory.",
          "Database connection works": "Yes, connection successful.",
          "Database structure as expected": "No, structure errors: no tables found for table prefix [wp_].",
          "Blog installed": "No, blog is not installed: database table [wp_options] does not contain a 'siteurl' option.",
          "Theme :": "Cannot find the 'template' option in the database.",
          "Must-use plugins health-check:": "mu-plugins directory(wp-content/mu-plugins) does not exist.",
          "Plugins health-check:": "The 'active_plugins' option was not found in the database . "
      }
  }
```

**Comment by mickaelperrin** [comment]
@lucatume Thanks, the instructions you gave me in https://github.com/lucatume/wp-browser/issues/258#issuecomment-502728153 are the way to do.

I struggle with the configuration but finally managed to bootstrap plugins before the tests start to run.

Thanks 👍

**Comment by lucatume** [comment]
Thanks for getting back to this, I’m happy to help.
