### ISSUE TITLE
[SETUP ISSUE]: Docker env for CI and testing only

### ISSUE THREAD

**Issue by g-kanoufi** [lucatume/wp-browser#271]
**Environment**
OS: [Mac, Linux]
PHP version: [7+]
Installed Codeception version: [latest]
Installed wp-browser version: [latest]
WordPress version: [latest]
Local development environment: [Local by Flywheel, Docker]

** Configuration files **
[On gist.github](https://gist.github.com/g-kanoufi/f1cd27dfaa11ebcd4a5e464be34d7772)

** Problem description **
I am having a very rough time though trying to get a testing only env that could run on CI like bitbucket pipelines.
The solution i am trying to get is using docker, but as i am very bad at docker and server things, i am getting lost there.

Would you have some basic docker-compose file to let's say create a new wp core env, load the db via the WPDB "populator" and run codecept run acceptance (as an exemple)?

This is what i tried, populator seems to work, but i can't seem to be able to connect to the db from the tests...

Also i am using the dockerfile from https://github.com/ryanshoover/docker-wp-browser, seems to be good as it set up wp and install wp-browser.

Any advice help with this will be of course very welcome.

**Comment by lucatume** [comment]
Hi, thanks for taking the time to report this.

I had never heard about the [ryanshoover/docker-wp-browser](https://github.com/ryanshoover/docker-wp-browser) project, great find; having never heard of it I've never used it so I cannot provide any insight about it.

Before I can provide any real help I need to ask you:
1. What are you trying to test? A plugin? A theme? A whole site?
2. In your gist you've shown the main Codeception (`codeception.yml`) configuration file, but not the suite files; could you add those the to gist?
3. Do you get any specific error message? 

Let me know.

**Comment by g-kanoufi** [comment]
So this is were it gets complicated, i want to mainly only acceptance test a full website as it involves a lot of custom made plugins and well the acceptance tests on the front end.
The main installation is running on LocalbyFlywheel, it's a multisite.
So what i did is grabbing one subsite db as a single install with wpmigratedb cli, so the docker testing install can be a single site install.
I then use the populator to import that already huge db.

Now all seems to be ok, but all test are failling even though there are not in the localbyflywheel env.
Sorry i hope this make sense, i will add the suite file also with on simple test file and the results.

Here is the updated gist with all files: https://gist.github.com/g-kanoufi/f1cd27dfaa11ebcd4a5e464be34d7772/edit

Thank you

**Comment by g-kanoufi** [comment]
Jus an update here.
I have been able to run tests on bitbucket pipeline all set up files are in the following updated Gist: https://gist.github.com/g-kanoufi/f1cd27dfaa11ebcd4a5e464be34d7772

One thing i miss is setting up WPWebDriver. Any addition in this sense to the gist will be super welcome :)

**Comment by lucatume** [comment]
Thanks for reporting back on this and sorry for my lack of activity: busy times.

I’va had in my plans to write a Docker-dedicated setup section in the documentation and your seems a strong reminder. .

**Comment by g-kanoufi** [comment]
Luca, yes, some doc on docker specific setup would be really awesome as it's very hard to find anything, especially for wpbrowser.
I hope my errors and files will help you for this.
