### ISSUE TITLE
[DOC REQUEST]: Add test specific users after the populator has run

### ISSUE THREAD

**Issue by g-kanoufi** [lucatume/wp-browser#276]
**Did you search the documentation first?**
I did

**What do you think is missing from the documentation?**
I wonder how would i be able to add specific users, after the populator run.
Should it be in the _before section of any test file? Or in the bootstrapActions? 

**Do you have any examples of what you'd like to see added to the documentation?**
What i would like to do, is actually just add 2 users with 2 different roles before the acceptance test are run. Best would be to be able to use WPClI for this.

**Comment by lucatume** [comment]
My answer is based on the assumption you're working in an acceptance test, using the `WPDb` module to import a site dump.
You mention `bootstrapActions` which is a parameter of the `WPLoader` module, that parameter is not relevant here but keep in mind [the `WPLoader` module should be used in `loadOnly` mode when used with `WPDb` module](https://wpbrowser.wptestkit.dev/summary/modules/wploader#wploader-to-only-bootstrap-wordpress).

To add users in your tests you can use [the `WPDb::haveUserInDatabase` method](https://wpbrowser.wptestkit.dev/summary/modules/wpdb#haveuserindatabase):

```php
```

**Comment by lucatume** [comment]
If you need to add the test users just **once**, before any test runs and after populator ran, then you can add the users in your dump too.

**Comment by g-kanoufi** [comment]
Sorry about missing WPDb::haveUserInDatabase method.
This is great but how can i get now the created user generated password to be able to login with that user.

Thank you.

**Comment by Luc45** [comment]
@g-kanoufi Paste this in your dump.sql:

```
##
# Super-admin with username "test" and password "test"
##
INSERT INTO `YOUR_USERS_TABLE_HERE`
(user_login,user_pass,user_nicename,user_email,user_url,user_registered,user_activation_key,user_status,display_name,spam,deleted)
VALUES('test','$P$BfJp61CSKLHgE9zs7ctfk7IU3xz.OM0','test','test@example.com','','2019-07-10 15:01:04.000','',0,'test',0,0);
```

Remember to replace `YOUR_USERS_TABLE_HERE`.

At your YML configuration file, you can also let the test itself use that admin user:

```
adminUsername: test
adminPassword: test
```

With this, you will be able to stop the test at a breakpoint and log-in to the WordPress dashboard with test/test

**Comment by lucatume** [comment]
> Sorry about missing WPDb::haveUserInDatabase method.
> This is great but how can i get now the created user generated password to be able to login with that user.
> 
> Thank you.

In my example I’m setting the password to `secret`, you can set the password to any value and just keep track of it. 
@Luc45 provided another approach too.

**Comment by g-kanoufi** [comment]
Luc, Lucas, thanks for all those info. 
Let me explain what is the final scenario that i would like to achieve.

The sql dump is auto-generated on a cron schedule and is the exact copy of staging site, so there is no use to add the users via SQL into the dump.
The YML admin user needs to stay as it is.
Once the populator has run, i want to test for the admin screen view for different user roles( check for the admin menu presence or not).
For this i would like to be able to use test only users with different role and be able to login with eavh one of those.

The test scenario are set already, my question is would there be a way to do this, by using wp-cli at some point or any other trick.

Hope this make more sense.

Thank you all for your help.

**Comment by Luc45** [comment]
@g-kanoufi In this scenario, it's what @lucatume said.

```php
/*
*  @see \Codeception\Module\WPDb::haveUserInDatabase
*  @see \tad\WPBrowser\Generators\User::generateUserTableDataFrom
*/
$editor_id = $I->haveUserInDatabase('test_editor', 'editor', [ 'user_pass' => '123pass' ]);
$I->loginAs('test_editor', '123pass');
```

**Comment by g-kanoufi** [comment]
Ok, so thank you for all your help, this is what i did in case this can help anyone there:

As we have the prod db dump generated automatically, i have added a new sql file with my modifications, like adding tests only users and tweeking some options and just call that second sql file in the populator as follow:

```
populator: 'mysql -u %DB_USER% --password=%DB_PASSWORD% -h %DB_HOST% %DB_NAME% < ./tests/_data/mdb_dump.sql && mysql -u %DB_USER% --password=%DB_PASSWORD% -h %DB_HOST% %DB_NAME% < ./tests/_data/additional_data.sql'
```
Where mdb_dump.sql is generated every day and untouched and additional_data.sql is our modifications.

This works perfectly.

Hope this can help. Thanks again.
