### ISSUE TITLE
[FEATURE REQUEST] Allow factories to be used when WPLoader's loadOnly is set to false

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-browser#278]
**Is your feature request related to a problem? Please describe.**
I try to use `WPLoader` factories when `loadOnly` is set to false, but they are not available.

**Describe the solution you'd like**
Modify `\Codeception\Module\WPLoader::_loadWordpress` line 313:

Before:
```
if (! empty($this->config['loadOnly'])) {
    $this->bootstrapWP();
} else {
    $this->installAndBootstrapInstallation();
}
```

After:
```
if (! empty($this->config['loadOnly'])) {
    $this->bootstrapWP();
} else {
    $this->installAndBootstrapInstallation();
    $this->factoryStore = new FactoryStore();
    $this->factoryStore->setupFactories();
}
```

Currently `factoryStore` is being added at `bootstrapWP`, which is not called if `loadOnly` is false.

Modifying the code as seen above I was able to use the factories with `loadOnly` false.

**Comment by lucatume** [comment]
Could you provide an example of how you would use this? I kinda know but am curious to a possible new idea.

**Comment by Luc45** [comment]
I am implementing a Builder Pattern that tries to be compatible with as many suites as possible. The idea is that you can use the same builder to build complex objects both in acceptance and integration tests, or any other suite, provided they have the necessary modules that Builder needs.

The Builder itself benefits from using factories to create posts, attachments and other stuff it might need to build a complex object. Let's suppose I want to do the following:

```
$I->build->car->
    with_category('sedan')->
    with_color('black')->
    with_photo('sedan.png');
```

`$I->build->car` would call `CarBuilder::build()`, which could look like this:

```
class CarBuilder implements BuilderInterface {

    /** @var \Codeception\Module\WPLoader */
    protected $wp;

    /** @var \WP_Post */
    protected $car;

    public function __construct( \Codeception\Module\WPLoader $wp ) {
        $this->wp = $wp;
    }

    public function build(): BuilderInterface {
        $this->car = $this->wp->factory()->post()->create_and_get(
            'post_type' => 'car',
        );

        return $this;
    }
}
```

As you can see, it uses `WPLoader::factory()` to build the post, for convenience.

In our original example, another usage for that would be `with_attachment('sedan.png')`, which would benefit from `WP_UnitTest_Factory_For_Attachment`, etc.

From my limited understanding of wp-browser, I don't see an issue on allowing `WPLoader` with `loadOnly` false to use the factories, thus this request.

**Comment by Luc45** [comment]
If you'd like an in-depth view of the Builder pattern implemented, see this documentation I wrote for it: https://pastebin.com/tHDc56h7 (link expires in 1 week)

**Comment by lucatume** [comment]
@Luc45 very interesting code indeed.
I feel like the Factory that comes (and would come with) the `WPLoader` module would already do a lot of that argument juggling, but agree that its array-based approach might not be the most readable one.
To better explain what I mean you can already do this:
```php
// In the context of a module we might be in a `WPUnitTestCase` or an acceptance test so look around.
$factory = method_exists(get_class($this), 'factory') ? static::factory() : $this->factory;

$car $factory->post->create([
  'tax_input' => ['category' => ['sedan']],
  'meta_input' => [
    'color' => 'black',
    '_thumbnail_id' => $factory->attachment->create_upload_object('sedan.png')
  ]
]);
```

Again: I feel yours is a valid addition that would empower more "ablative" APIs; thanks.
I will update this issue when I have news.
