### ISSUE TITLE
WPAJaxTestCase.php

### ISSUE THREAD

**Issue by LeRondPoint** [lucatume/wp-browser#28]
I've been tearing my hair out all day for this stupid "bug" so I thought of logging it somewhere.

It happens that the WPAjaxTestCase file name has a capital 'J' so you might want to check that out if you get a "File not found" error like I did!

**Comment by lucatume** [comment]
You are so right; me being on Mac means file names are case insensitive: sorry for the time loss.
I've pushed a new version to fix it.

**Comment by LeRondPoint** [comment]
Cool, hopefully this can save others some frustration!
