### ISSUE TITLE
Bad output for multiple consecutive Ajax 'calls'

### ISSUE THREAD

**Issue by LeRondPoint** [lucatume/wp-browser#29]
Hi,
I found a bug when calling multiple Ajax calls in a single test.  My tests consists of one Ajax call to get a list of accounts and then use that list to retrieve other properties, again via Ajax calls.  The problem I get is that the second call's _last_response contains the text of the first test.  This is due to the appending of the previous value in

```
	public function dieHandler( $message ) {
		$this->_last_response .= ob_get_clean();
```

Emptying the _last_response at the beggining of _handleAjax fixes this bug but maybe it should be a simple '='?  I'm not sure why you append in dieHandler.

```
	protected function _handleAjax($action) {
		$this->_last_response = NULL;

```

**Comment by LeRondPoint** [comment]
See PR#30 for fix

**Comment by lucatume** [comment]
I've closed the PR not out of spite but to open one that deals with my code only and not the one that's in `src/includes`.
Could you paste a piece of the code you are testing to have a context?

**Comment by LeRondPoint** [comment]
This is a case I often have because I like regrouping all my exception/error handling for a given case in a single test.  Arguably not the best practice but usually they look something like this:

```
	public function testExperimentSaveFailures()
	{
		global $experiments_model;
		
		$testExperiment = $experiments_model->createPendingExperimentModel('SaveAjaxTest', $this->validAccountId, $this->validPropertyId, $this->validViewId);
		
		try
		{
			// No experiment Id
			$this->_handleAjax('save_experiment');
		}
		catch(WPAjaxDieContinueException $e)
		{
			$response = json_decode($this->_last_response);
			
			$this->assertNotNull($response);
			$this->assertNotEmpty($response->error);
		}
		
		$_POST['experimentId'] = $testExperiment->getDBId();
		
		try
		{
			// No name
			$this->_last_response = NULL;
			$this->_handleAjax('save_experiment');
		}
		catch(WPAjaxDieContinueException $e)
		{
			$response = json_decode($this->_last_response);
			
			$this->assertNotNull($response);
			$this->assertNotEmpty($response->error);
		}

...

```

**Comment by lucatume** [comment]
These should be, in strict TDD terms, all be different test cases.
If one of the tests is not throwing the test will pass; I'd separate them and use `$this->setExpectedException` in each. This way you are making sure an exception is thrown when you expect it to. Something like this:

	public function testExperimentSaveFailsWithNoID() {
	       	global $experiments_model;

       		$testExperiment = $experiments_model->createPendingExperimentModel('SaveAjaxTest', $this->validAccountId, $this->validPropertyId, $this->validViewId);

		$this->setExpectedException('WPAjaxDieContinueException');

		$this->_handleAjax('save_experiment');

		$response = json_decode($this->_last_response);

            	$this->assertNotNull($response);
            	$this->assertNotEmpty($response->error);
	}

and replicate for each.
I'm not keen on introducing such a method but I'm open to a contextualised and well done PR.

**Comment by LeRondPoint** [comment]
Sure this is another approach but it's besides the point.  I see no reason why a functional test should not have multiple Ajax calls in a single test.

I can just create my own helper to fix this simple problem but others might also want it...

**Comment by lucatume** [comment]
> I'm not keen on introducing such a method but I'm open to a contextualised and well done PR.

Well: make it and open a PR!
