### ISSUE TITLE
[BUG] Doesn't ignore foreign key constraints when dropping tables

### ISSUE THREAD

**Issue by TimothyBJacobs** [lucatume/wp-browser#292]
**Environment**
OS: Mac
PHP version: 7.3
Installed Codeception version: v3.1.0  
Installed wp-browser version: 2.2.19
WordPress version: 5.2  
Local development environment: Local
WordPress structure and management: Default

**Codeception configuration file**  
Default generation.

**Suite configuration file**
Default generation.

**Describe the bug**
If you have foreign key constraints setup, when `isolated-install.php` drops all the known tables, it may error with a `Cannot delete or update a parent row: a foreign key constraint fails` error.

**Expected behavior**
For foreign key constraints to be ignored when dropping tables.

**Comment by lucatume** [comment]
Hi @TimothyBJacobs,

Thank for reporting the issue **and** providing a fix for it, wow.

I will take a look at the PR as soon as I can and merge it.

Again, thanks for your contribution.
