### ISSUE TITLE
[FEATURE REQUEST] Add allow-root as a WP CLI option or way to switch user

### ISSUE THREAD

**Issue by TimothyBJacobs** [lucatume/wp-browser#295]
**Is your feature request related to a problem? Please describe.**
When running tests in the bitnami docker WP image, WP CLI needs to be run as the daemon user. However, to gain access to the root WordPress folder you need to be root. 

If you run WP CLI as the root user, you get the "are you sure" warning instructing you to add `--allow-root` or switch to the correct user.

**Describe the solution you'd like**
Add `allow-root` to `WPCLI::$options` or provide a way for the generated command in WP Cli to have `sudo -u USER -- ` prepended to the generated command.

**Describe alternatives you've considered**
I'm currently subclassing WPCLI to add `allow-root` to the allowed options.

**Comment by TimothyBJacobs** [comment]
Happy to PR either of these.

**Comment by lucatume** [comment]
@TimothyBJacobs thanks for this report.

I'm working to fix this in the PR #298 .

The idea is to support an `allow-root` configuration parameter in the `WPCLI` module configuration.
