### ISSUE TITLE
[FEATURE REQUEST] Add WP CLI method to get raw output

### ISSUE THREAD

**Issue by TimothyBJacobs** [lucatume/wp-browser#297]
**Is your feature request related to a problem? Please describe.**
When executing a WP CLI command that returns an id, or count, or similar "single" value, needing to use `cliToArray` can be unergonomic.

**Describe the solution you'd like**
A method like `cliToString` that returns the raw output string.

**Describe alternatives you've considered**
Always providing a custom split function that just wraps the output in an array.

**Additional context**
This is what I've added to a subclass.

```php
public function cliOutput( $userCommand ) {
	$this->initPaths();

	$command = $this->buildCommand( $userCommand );

	$this->debugSection( 'command', $command );
	$output = $this->executor->execAndOutput( $command, $status );
	$this->debugSection( 'output', $output );

	$this->evaluateStatus( $output, $status );

	return $output;
}
```

**Comment by lucatume** [comment]
This seems a good addition to the module, thanks.

I will add this in the same PR (#298) where I'm tackling the other issues you reported (thanks again!).
