### ISSUE TITLE
[FEATURE REQUEST] WP CLI Strict Args Mode

### ISSUE THREAD

**Issue by TimothyBJacobs** [lucatume/wp-browser#299]
**Is your feature request related to a problem? Please describe.**
Add support for strict arg mode to distinguish between global and local parameters.

**Describe the solution you'd like**
For me to be able to pass `strict` as a config option to the WP CLI module. When in this mode, the global parameters would be placed before the user command and `WP_CLI_STRICT_ARGS_MODE=1 ` would be prefixed to the final built command.

**Describe alternatives you've considered**
I haven't been able to figure out an alternate way to do this.

**Additional context**
Prior to #298 I've been using:

The only change in `mergeCommandOptions` was to flip the final concatenation.

```php
protected function mergeCommandOptions( $userCommand ) {
	$commonOptions = [
		'path' => escapeshellarg( $this->config['path'] ),
	];

	$lineOptions = [];

	$nonOverriddenOptions = [];
	foreach ( $this->options as $key ) {
		if ( $key !== 'require' && false !== strpos( $userCommand, '--' . $key ) ) {
			continue;
		}
		$nonOverriddenOptions[] = $key;
	}

	foreach ( $nonOverriddenOptions as $key ) {
		if ( isset( $this->config[ $key ] ) ) {
			$commonOptions[ $key ] = escapeshellarg( $this->config[ $key ] );
		}
	}

	foreach ( $commonOptions as $key => $value ) {
		$lineOptions[] = $value === true ? "--{$key}" : "--{$key}={$value}";
	}

	return implode( ' ', $lineOptions ) . ' ' . $userCommand;
}

protected function buildCommand( $userCommand ) {
	$built = parent::buildCommand( $userCommand );
	$built = 'WP_CLI_STRICT_ARGS_MODE=1 ' . $built;

	return $built;
}
```

Not sure yet how I'd go about doing this after #298.

**Comment by lucatume** [comment]
@TimothyBJacobs thanks for reporting this.

I was just looking at the issue number going down... I missed by 10'.

Good idea, thanks, coming soon.

**Comment by lucatume** [comment]
Added in `2.2.22`, see [doc](https://wpbrowser.wptestkit.dev/summary/modules/wpcli#environment-configuration).

**Comment by TimothyBJacobs** [comment]
Thanks so much @lucatume, this looks perfect!
