### ISSUE TITLE
[BUG] Broken Codeception 3 support

### ISSUE THREAD

**Issue by JanJakes** [lucatume/wp-browser#306]
It seems Codeception 3 support was removed from `composer.json` by mistake in https://github.com/lucatume/wp-browser/commit/be75f4245315600789793e72594ad185c755d112.

**Comment by lucatume** [comment]
@JanJakes thanks for reporting this and for pointing out the commit, much appreciated.

I've fixed in master and am testing it out.

**Comment by lucatume** [comment]
Fixed in `2.2.25`.
