### ISSUE TITLE
[BUG] WP-CLI broken when argument contains spaces

### ISSUE THREAD

**Issue by JanJakes** [lucatume/wp-browser#310]
**Environment**
OS: Linux
PHP version: 7.3
Installed Codeception version: 2.5.2
Installed wp-browser version: 2.2.25
WordPress version: 5.2

**Problem:**
When using title with spaces such as:
```
$post_title = 'Post for ALC newsletter testing';
$I->cliToArray("post create --format=json --porcelain --post_title='$post_title'");
```

I get `Codeception\Exception\ModuleException: WPCLI: Error: Too many positional arguments: ALC newsletter testing'` error.

The error does not occur on `2.2.20`. It may be caused by a combination of the two following commits :

1. https://github.com/lucatume/wp-browser/commit/66d514e41720802db8fc0edecf97198999f601af where `buildCommandLine()` was added.
2. https://github.com/lucatume/wp-browser/commit/7f8a028ec4bdff2e2a1082f8052f1c5075d5dec1 where `buildCommandLine()` is used.

The `buildCommandLine()` seems to break arguments that contain spaces (such as `--post_title='Post for ALC newsletter testing'`) because it's using `explode` on spaces ([here](https://github.com/lucatume/wp-browser/blob/master/src/tad/WPBrowser/utils.php#L26)).

**Comment by lucatume** [comment]
@JanJakes thanks for reporting the issue.

I think you're right in your diagnosis and the commits you pointed out are probably the origin.
While I work to fix the issue you can pass the arguments in the array format and that parsing will be avoided.

```php
$post_title = 'Post for ALC newsletter testing';
$I->cliToArray(['post', 'create', '--format=json', '--porcelain', "--post_title=$post_title"]);
```

Let me know if that is a good work-around for the issue.

**Comment by JanJakes** [comment]
@lucatume I simply downgraded to `2.2.20` but the array workaround works as well, thanks!

**Comment by lucatume** [comment]
I'd use the array format always, even after the issue is fixed: this is the format supported and used by the Symfony Process component and the one that, in the long run, will have the least problems.
