### ISSUE TITLE
[BUG] WPCLI with output on stderr raises exception (return code is 0)

### ISSUE THREAD

**Issue by JanJakes** [lucatume/wp-browser#312]
In recent versions (tested on `2.2.27`) a command that outputs a simple warning to stderr (like that a plugin was already activated) makes the command fail (when `throw` set to true). It's probably thrown [here](https://github.com/lucatume/wp-browser/blob/master/src/Codeception/Module/WPCLI.php#L373).

It seems there used to be a similar behavior before but for some reason, it didn't work (didn't throw the exception).

Now, there's a significant difference between a failed command (returning non-zero code) and a command that writes to stderr. For many commands it's actually a normal practice - to write info to stderr while content to be piped is written to stdout.

If I use `throw: true` I can't detect whether the command failed or just outputted something because I cannot get the return code. If I use `throw: false` I get the return code but not the error message.

Should those two things really be under a single option? They seem to be quite different.

**Comment by JanJakes** [comment]
@lucatume I marked this a bug since it's quite a BC break. Will have to downgrade to `2.20.0` atm since we do have some warnings on stderr. I noticed there has been quite a few BC breaks recently in patch versions.

On an unrelated note - [this](https://github.com/lucatume/wp-browser/releases/tag/2.2.21) release has a wrong name, probably a typo (`2.2.1` instead of `2.2.21`).

**Comment by lucatume** [comment]
@JanJakes I understand how this could be a bug.
The irony of it is that it's now due to a previous one that would prevent exceptions from being thrown on failing commands.

I lean toward certain fixtures and results in testing and prefer an exception being thrown if the command fails for any reason, but I understand how that might not be everyone's path.

I'm implementing this API:

```php
tryTo( function(){
}
```

**Comment by JanJakes** [comment]
@lucatume For instance, we have a test that expects something not being visible when WooCommerce is not active. In our tests it's not active by default but doing this `$I->cli('plugin deactivate woocommerce');` explicitely seems cleaner and more readable. This will output a warning `Warning: Plugin 'woocommerce' isn't active.`, not a big deal but now converted to exceptions.

While what you suggest seems to be more universal, one may want to ignore stderr warnings for all tests. What about adding an option such as `throw_on_stderr`? It could also default to `true` as well as `throw` does, also seems easy to implement.

**Comment by lucatume** [comment]
I see your point, thanks for providing more information.
While I see the value in a `throw_on_stderr` setting I also see how it could become a hindrance as the suite scales.
It all comes down to how the `WPCLI` module is used in tests, but how, provided that configuration parameter and its `false` value, would you handle this?

```php
// It's ok to fail.
$I->cli('plugin deactivate woocommerce');

// It's not ok to fail, if this silently fails the rest of the assertions are moot.
$I->cli('theme activate nope');

// We should not be here.
$I->amOnPage('/');
$I->seeElement('body.nope-theme');
```

I appreciate how this is personal preference, yet I'd rewrite the above with this:

```php
tryTo(function()use($I){
  $I->cli('plugin deactivate woocommerce');
});

// Bail if we fail here.
$I->cli('theme activate nope');

$I->amOnPage('/');
$I->seeElement('body.nope-theme');
```

**Comment by JanJakes** [comment]
@lucatume I agree with you, my point is there is a significant difference between a _failed_ command and a command that just outputs something to _stderr_. The difference is so fundamental that the authors of the commands decided to still return `0` and just output some info.

I'm not saying we should ignore _failed_ commands. I'm saying we should not conver successful commands to _failed_ ones.

By throwing the exception you're modifying the behavior that was implemented by the authors. See this as a shell script:
```
set -e
wp plugin deactivate woocommerce
wp theme activate nope
```

Even with `set -e` (exit on error) such script would not exit and would succeed. The _only_ thing that would happen would be a visible warning that the plugin is not active. That's all.

Now, what happens when you write this using `$I->cli()`? It will all fail although the command didn't fail at all. That's the behavior-modification I'm talking about. Command return code is what makes it successful or failed, not what it writes to any output.

**Comment by lucatume** [comment]
@JanJakes thanks for clarifying further.

Your point is a valid one; I will update the behavior to throw, if `throw` is `true`, on a not `0` exit status, rather than as a result of a check on the content of `stderr`.

I will update this issue with the PR when ready.

**Comment by JanJakes** [comment]
@lucatume Thanks! That said, there may be valid use cases when warnings show something is not completely OK. Warning such as that plugin was not active is harmless but if I'm not mistaken I've seen other warnings like invalid post ID when I passed wrong or empty string to `--post_id=...` (I think it was just a warning).

So my point is - yes, respecting command return value is good but maybe someone would like to be even stricter, I don't know.

**Comment by lucatume** [comment]
I would let my over-engineering attitude out of the discussion for now and trust the good folks that created and maintain wp-cli: if, to their judgment, an error is fine while still keeping the `0` status code it's fine enough for me too.

If anyone requests, in the future, stricter checkings, then I'll deal with that.

Thanks to you for the long merry-go-round discussion.
