### ISSUE TITLE
WPDb pupulate works in a weird way

### ISSUE THREAD

**Issue by homejunction** [lucatume/wp-browser#32]
Hi Luca,

Can WPDb pre-population of the DB work with WPLoader together?

I want to import dump of my test WP db and run some tests against it. I can't do that when WPLoader is not included, I'm getting this error:

```
[PHPUnit_Framework_Exception] Use of undefined constant WP_TESTS_FORCE_KNOWN_BUGS - assumed 'WP_TESTS_FORCE_KNOWN_BUGS'
```
When I include both modules: WPDb and WPLoader, I can see that my dump get's imported some time during the test, but then it gets dropped by WPLoader in favor of clean setup.

Any ideas?

**Comment by homejunction** [comment]
I worked all day without being able to figure it out. And, of course, as soon as I posted this question here, I figured out a solution.

The solution is to run `$this->getModule('WPDb')->_initialize();` in `Module::_beforeSuite()`. It works. 

Thanks!

**Comment by LeRondPoint** [comment]
I started working on a WPBootstrap module yesterday that is compatible with WPDb.  Essentially, it bootstraps an existing WP installation.  It works for my needs as we speak but I'll need to add some tests eventually to make sure it works in all cases.
