### ISSUE TITLE
codecept: command not found[SETUP ISSUE]

### ISSUE THREAD

**Issue by apurbajnu** [lucatume/wp-browser#327]
**Environment**
OS: [e.g. WSL (windows subsystem/ubuntu18.04)]
PHP version: [e.g. 7.3]
Installed Codeception version: [e.g. 2.5.0]
Installed wp-browser version: [e.g. 2.2.1]
WordPress version: [e.g. 5.2]
Local development environment: [e.g. PHP built-in server, Valet, MAMP, Local by Flywheel, Docker]
WordPress structure and management: [e.g. default, Bedrock, other]

**Did you use the `codecept init wpbrowser` command?**
Yes 
 What step should I take next?

**Comment by lucatume** [comment]
@apurbajnu if the `codecept` command is not in your path, then you will get that message.

To solve either add `vendor/bin` to your path (google for the specific instructions for you setup) or use:
```bash
vendor/bin/codecept init wpbrowser
```

See [the documentation](https://wpbrowser.wptestkit.dev/summary/getting-started/configuration) for more information.
