### ISSUE TITLE
Help me test my package

### ISSUE THREAD

**Issue by szepeviktor** [lucatume/wp-browser#330]
Hello @lucatume!

Could you help me a bit to start testing this package?
https://github.com/szepeviktor/wordpress-persistent-admin-notices
Basically

- you can add
- and remove admin notices
- we could test the HTML on the admin page
- and the site transient

ps. I have no problem installing WP in CI

**Comment by lucatume** [comment]
@szepeviktor could you be more specific about where you’re stuck or having issues?

**Comment by szepeviktor** [comment]
@Luc45 I do not know what kind of setups are, actually I'm totally lost.

**Comment by lucatume** [comment]
Did you try [here](https://wpbrowser.wptestkit.dev/summary/getting-started)?

**Comment by lucatume** [comment]
@szepeviktor any news on this front?

**Comment by szepeviktor** [comment]
I think I have to spend hours until I deeply understand it.
Maybe I'll contribute additional docs.

**Comment by lucatume** [comment]
> I think I have to spend hours until I deeply understand it.
> Maybe I'll contribute additional docs.

In my experience, there's usually an initial block that makes it look more difficult.
