### ISSUE TITLE
[BUG] Cannot create user with capitalized username

### ISSUE THREAD

**Issue by TimothyBJacobs** [lucatume/wp-browser#332]
**Environment**
OS: Mac
PHP version: 7.3.8
Installed Codeception version: 3.1.0
Installed wp-browser version: 2.2.31
WordPress version: 5.3
Local development environment: LbF
WordPress structure and management: default

**Describe the bug**
`User::generateUserTableDataFrom()` always converts the passed username into a slugified version. This means if I want to create a user with a username like `MyUser`, I can't since it will always be transformed to `my-user`.

This ensures the username is valid for the other generated information, but is stricter than WP core.

**Expected behavior**
To be able to insert the user with the expected username.

Perhaps a strict parameter that can be disabled?

**Comment by lucatume** [comment]
@TimothyBJacobs Thanks (again) for reporting this issue. I think the behavior could be revisited to allow for the same kind of usernames WP Core would allow.

Next!
