### ISSUE TITLE
[FEATURE REQUEST] Allow specifying additional capabilities in haveUserCapabilitiesInDatabase

### ISSUE THREAD

**Issue by TimothyBJacobs** [lucatume/wp-browser#337]
**Is your feature request related to a problem? Please describe.**
I have to manually construct the meta key to grant specific capabilities to users.

```php
$I->haveUserMetaInDatabase( $uid1, $capsKey, serialize( [
	'administrator'  => 1,
	'manage_options' => false,
] ) );
```

**Describe the solution you'd like**
To be able to make an API call like the following which would set the role and include the capabilities.

```php
$I->haveUserCapabilitiesInDatabase( $uid, 'administrator', [
	'manage_options' => false,
] );
```

**Describe alternatives you've considered**
I'm currently manually calling `haveUserMetaInDatabase`.

**Additional context**
It'd be great if this could also be called via `haveUserInDatabase`. For instance.

```php
$uid = $I->haveUserInDatabase( 'my-user', 'administrator', [
	'capabilities' => [
		'manage_options' => false,
	],
] );
```

Happy to submit a PR if this seems like a good idea. Kinda blocked by #336.

**Comment by lucatume** [comment]
@TimothyBJacobs this could go in together w/ the fix for #336.

Once I have a fix for #336 I will review this one and come back with some more code context to see if the proposed API, as it is, is a good fit.

Thanks for opening the issue.

**Comment by lucatume** [comment]
@TimothyBJacobs while working to fix #335 I've extended the `WPDb::haveUserInDatabase` and `WPDb::haveUserCapabilitiesInDatabase` methods to accept more structured roles and caps.

The API, due to back-compat requirements, is not exactly the one you had envisioned as the 3rd parameter of the `haveUserInDatabase` method is a non-role related meta overrrides (you can still hack aroudn with it, though).

Both methods will accept now more complex arrays:

```php
// Create an editor user.
$I->haveUserInDatabase('luca', 'editor');

// Create an editor that can edit themes.
$I->haveUserInDatabase('luca', ['editor', 'edit_themes']);

// Create an admin that cannot manage options.
$I->haveUserInDatabase('luca', ['administrator' => true, 'manage_options'=> false]);

// Create a user w/ a number of roles and caps in diff. sites.
$I->haveUserInDatabase('luca', [
	1 => 'editor',
	2 => ['editor', 'edit_themes],
	3 => ['administrator' => true, 'manage_options' => false],
	4 => [
		'subscriber' => true,
		'edit_themes'=> true,
		'editor' => true,
		'publish_posts' => false
	]
    ]
);
```

**Comment by lucatume** [comment]
And the same structure can be used for the `WPDb::haveUserCapabilitiesInDatabase` method.

**Comment by TimothyBJacobs** [comment]
Looks great to me! Thank you!
