### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by dwenaus** [lucatume/wp-browser#34]
I'm getting this fatal error:

PHP Fatal error:  Call to a member function all() on a non-object in /srv/www/rg/multisite/htdocs/wp-content/plugins/programs-tests/vendor/lucatume/wp-browser/src/Codeception/Module/WPLoader.php on line 139
PHP Stack trace:
PHP   1. {main}() /srv/www/rg/multisite/htdocs/wp-content/plugins/programs-tests/vendor/lucatume/wp-browser/wpcept:0

I'm trying to run $ vendor/bin/wpcept run unit

**Comment by lucatume** [comment]
Hi,

thanks for opening an issue.
Please take the time to:

* update the Codeception and WPBrowser to the latest version
* describe the machine the tests are running on
* in general supply all the details that could help
* describe what you tried first

**Comment by dwenaus** [comment]
I was using codeception version 2.0. Works great now, thanks :)
