### ISSUE TITLE
[FEATURE REQUEST] Add "themesFolder" parameter to WPLoader module

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-browser#342]
**Is your feature request related to a problem? Please describe.**
We use a custom WordPress directory structure and would like the flexibility to determine `themesFolder` as we do with `pluginsFolder`.

**Describe the solution you'd like**
Add a parameter to `WPLoader` module for `themesFolder` which, when calling `get_stylesheet_directory();` or `get_template_directory();` on integration tests will return the path specified in `themesFolder`. Perhaps it could behave like `pluginsFolder` does, where if you add a relative path it will consider `wpRootFolder` as root.

Example configuration and folder structure:
```yml
WPLoader:
    wpRootFolder: /application/www/wp
    pluginsFolder: ../wp-content/plugins
    themesFolder: ../wp-content/themes
```

```
/application/www/wp (where WordPress live)
/application/www/wp-content/plugins (where my plugins live)
/application/www/wp-content/themes (where my themes live)
```

**Describe alternatives you've considered**
I am currently calling this on my integration tests that depend on the value of `get_stylesheet_directory()` and `get_template_directory()`:

```php
add_filter( 'template_directory', function ( $template_dir, $template, $theme_root ) {
	return '/application/www/wp-content/themes/core';
}, 10, 3 );

add_filter( 'stylesheet_directory', function ( $stylesheet_dir, $stylesheet, $theme_root ) {
	return '/application/www/wp-content/themes/core';
}, 10, 3 );
```
It works. But I was considering if it would make sense to add `themesFolder` for consistency, as already `pluginsFolder` exists.

Thanks!

**Comment by lucatume** [comment]
@Luc45 there is currently no way, in WordPress, to change the location of the `/themes` directory via constant as it exists, instead, for plugins.

I see how this could provide some value by filtering the `theme_root` path.

I'm labeling this as an enhancement.
