### ISSUE TITLE
[FEATURE REQUEST] Symlinker Extension mode extend for uploads dir

### ISSUE THREAD

**Issue by sjacomeit** [lucatume/wp-browser#344]
**Is your feature request related to a problem? Please describe.**
We used WordPress in a docker setup with symlinked uploads directory in /wp-content. On the WP Installation the directory will found and all uploaded files could find / uploaded. But all WPUnit tests will failed because wp_upload_dir() returns as basepath a wrong path to the upload dir.

**Describe the solution you'd like**
Maybe to use the extension Symlinker for extend the mode param for "upload" to desolve the symlink of the uploads directory.

**Describe alternatives you've considered**
Don't have one.

**Additional context**

**Comment by lucatume** [comment]
Hi @sjacomeit, thanks for reporting this.

Could you provide a minimal setup (the relevant files) to reproduce this?

**Comment by sjacomeit** [comment]
For example:

The original uploads directory are /dir/to/nfs/upload/uploads where the year directories are created.

Our WordPress are under /dir/to/htdocs/wordpress and there are the directory wp-content.

The "uploads" directory will symlinked /dir/to/htdocs/wordpress/wp-content.

If we use on wpunit the function wp_upload_dir() on 'basedir' we got the directory /dir/to/htdocs/wordpress/wp-content/uploads instead of /dir/to/nfs/upload/uploads (which will returned if we print 'basedir' wp_upload_dir() on WP backend over the Apache). 

Do you understand where our problem is?

**Comment by lucatume** [comment]
@sjacomeit I understand some parts of the issue, but not the complete picture. To work on anything I will need a minimal working example of any relevant configuration files. 

Could you provide that?

What is the current solution or workaround you’ve adopted, if any?

**Comment by sjacomeit** [comment]
Its ok, we have found another solution and save the entries in a database instead of csv file now.

**Comment by lucatume** [comment]
Thanks for taking the time to report back, if anything else comes up, let me know.
