### ISSUE TITLE
[DOC REQUEST] WPRest test case example

### ISSUE THREAD

**Issue by kidunot89** [lucatume/wp-browser#347]
**Did you search the documentation first?** yes

**What do you think is missing from the documentation?**
An **WPRestApiTestCase** example that tests a custom WP REST endpoint.
Testing both the endpoint's existence and response data.

**Do you have any examples of what you'd like to see added to the documentation?**
No, because I don't know how it's done and that's the problem. :man_shrugging:

**Comment by lucatume** [comment]
HI @kidunot89,

thanks for taking the time to open the issue and provide the required information. 

I recognize the documentation there is missing and this could use coverage.

I will keep this issue updated with news.

**Comment by lucatume** [comment]
Mmm,

so the notifications came in in time order and I replied before my session showed the "closed" tag, @kidunot89 any reason you closed the issue?

**Comment by kidunot89** [comment]
@lucatume Because I was able to find an example in the documentation [here](https://wpbrowser.wptestkit.dev/levels-of-testing#integration-tests). That example, along `RestApiTestCase` class definition. I was able to easily implement what I needed.

**Comment by lucatume** [comment]
@kidunot89 (I just realized your handle is "I kid you not" and it's a smart one),

thanks for replying. 

I will keep the suggestion, though, as it's a piece of documentation that is missing and that has been required in the past.

Happy testing,
