### ISSUE TITLE
[FEATURE REQUEST] Support Codeception 4.0

### ISSUE THREAD

**Issue by GaryJones** [lucatume/wp-browser#349]
**Is your feature request related to a problem? Please describe.**

The `composer.json` for wp-browser doesn't support [Codeception 4.x](https://codeception.com/changelog). The latest version at the time of writing is 4.1.4, so it's been around for a while.

**Describe the solution you'd like**

Update [this line](https://github.com/lucatume/wp-browser/blob/8c4b6428f220dd159df0855f06c75957a6c5859b/composer.json#L26) to allow installation of wp-browser with Codeception 4.x.

**Additional context**

I've not used wp-browser before, so I don't know if there are any breakages in Codeception 4 that causes issues for wp-browser.

**Comment by lucatume** [comment]
@GaryJones,

Thanks for taking the time to open the issue.
I've been refactoring code in wp-browser lately and am working to make the testing stable to move to support Codeception 4.0.
Know it's the next feature I want to cover and that it's on my radar.

From my local tests, it works "most" of the times, but not completely. It will require some work, but should not require a ton of it.

I will keep this issue updated with progress and, soon, a branch and PR to track the work.
