### ISSUE TITLE
WPLoader loading options

### ISSUE THREAD

**Issue by lucatume** [lucatume/wp-browser#35]
Continues from https://github.com/lucatume/wp-browser/pull/33#issuecomment-185908613

@LeRondPoint WPBootstrapper is meant to be used in acceptance tests to have access to, and work on, the WP installation that's being hit by the acceptance tests.

[Your](https://github.com/LeRondPoint/wp-browser/blob/WPBootstrap/src/Codeception/Module/WPBootstrap.php) seems to be a middle ground between calling `wp-load.php` straight and using the WPLoader module and its opinionated and destructive approach.
If I can have a firmer grasp on what you would like to do with it and in which tests you would like to use it maybe we could simply work out an option for the WPLoader module to have it work as intended.

Something in the league of 

```yaml
modules:
    config:
        WPLoader:
            startBlank: false
```

Let me make a first tentative call on your intentions:

> As a tester I want to be able to bootstrap a WordPress installation **without** resetting it to a blank state and access WPLoader-like unit/functional test cases and methods in my unit and functional tests.

Please correct me below and let's make this work.

**Comment by LeRondPoint** [comment]
My need actually arises from the conflict between WPLoader and WPDb.  I have a series of unit and functional tests that worked fine with WPLoader and I also have some acceptance tests that rely on WPDb to setup WP in a start state for my tests (admin user set, plugin activated, test page created, possibly some test data, etc.).  These tests have no need for WPLoader as it is done using the DB dump.

When I try to run all these tests in a single batch in jenkins, the acceptance tests failed because of a PDOException.  Hence I needed a bootstrapper that worked for both setups.

I'm not sure about using a User Story for such a case.  In my opinion it is a technical limitation or a bug since it occurs in different suites...

**Comment by LeRondPoint** [comment]
P.S. I can give you access to my private BitBucket repo if desired

**Comment by lucatume** [comment]
>My need actually arises from the conflict between WPLoader and WPDb.

Are those hitting the same database?

**Comment by LeRondPoint** [comment]
Yes for the time being

**Comment by lucatume** [comment]
And you tried using WPLoader on one and WPDb on another?
WPLoader will destroy the database it works on so this is a common case and a common pattern.

**Comment by LeRondPoint** [comment]
I understand that there can be a limitation within a single suite but the problem I have is that the limitation is over a single run.

No I haven't tried using 2 databases.  To me this is a workaround, not a solution.
Why doesn't WPLoader cleanup after each suite?

**Comment by lucatume** [comment]
Because a WordPress instance is installed before each test is run and all of it is wiped out after that; since I'm reusing the Core developed suite to power WPLoader I'm not keen on modifying it to accommodate for the comfort of the single database solution and walk the path of a long and costly re-adaptation of it with each release.

To me having two databases is not a workaround, it's keeping concerns separated; the fact that Codeception allows for different types of tests to be run as one does not mean the same approach I would take using PHPUnit to do unit testing and Cucumber to do acceptance does not apply: I would be using a separate database for each. But again this is my approach and should/will not fit every one.

If you really want to use WPDb on the same database WPLoader ran on then create a dump that will take care of re-creating any missing table too; I've not walked this way though and cannot properly advise. 

Please report any findings that might help the development if you come across any and again I'm very open to PRs that might help the development.

**Comment by LeRondPoint** [comment]
Hi,
I am using a dump for the acceptance tests, it's "loading" this dump (dumping the old DB) that causes the PDOException I think.  Why, I have no clue...  Maybe you could light my latern?

Again, I understand you not wanting to make modifications in the Core.  I'm trying to find a solution that would fit more than my immediate needs and would not impose "arbitrary" restrictions like the use of different DBs.

**Comment by JDGrimes** [comment]
@LeRondPoint I'm not sure exactly what you're looking for, but I'm currently working with [a custom module](https://github.com/WordPoints/hooks-api/blob/master/tests/codeception/_support/Modules/WordPointsLoader.php) that gives me accesses to the database being used in the WebDriver tests while the acceptance tests are running. Maybe that is a help to you?

**Comment by lucatume** [comment]
@JDGrimes your code shows some mileage and it's very similar to the idea behing the WPBootstrapper module but clearly more refined, are you interested in some joined work?
If "no" no hard feelings but let me know if you ever detach it from your repo as a standalone module: I'd be happy to link to it in the readme file.

**Comment by JDGrimes** [comment]
@lucatume I'm still polishing on the module, and I think it would be easiest for me to finish tweaking it where it is. But you are welcome to copy it and start hacking away, if you'd like.

I probably will eventually be putting it into its own repo, right now it is just still in the early stages. When I do that I'll be sure to let you know.

P.S.—Right now I am trying to get my acceptance tests to run on Travis CI, but it isn't working yet. Do you have any experience with running Codeception acceptance tests on Travis CI?

**Comment by LeRondPoint** [comment]
@JDGrimes I have no problem loading the DB using the WPDb module from @lucatume and my [WPBootstrap module ](https://github.com/LeRondPoint/wp-browser/blob/WPBootstrap/src/Codeception/Module/WPBootstrap.php)

The problem Is that I used some parts of the Core code that could change in the future and maintenance might be problematic.

**Comment by lucatume** [comment]
@JDGrimes ok, I'm blatantly copying your function to deactivate updates as it's really useful and a thing I had not taken into consideration at all.
Whatever comes out of the module I will look for it, thanks.

>P.S.—Right now I am trying to get my acceptance tests to run on Travis CI, but it isn't working yet. Do you have any experience with running Codeception acceptance tests on Travis CI?

I've not set up a Travis server to do it but two companies I work with did, any particular issue? Care to open an issue proper to track it in context?

**Comment by JDGrimes** [comment]
@lucatume See #36.
