### ISSUE TITLE
[FEATURE REQUEST] Prevent "Administration email verification" from interfering with tests

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-browser#358]
**Is your feature request related to a problem? Please describe.**
Yes. I'm trying to run an acceptance test, but it shows me this screen after a succesful login:

![image](https://user-images.githubusercontent.com/9341686/78394852-c6f0da80-75c2-11ea-8c8f-83b1064d4029.png)

**Describe the solution you'd like**
https://wordpress.stackexchange.com/questions/353167/disable-the-administration-email-address-verification-new-in-5-3

**Additional context**
I'm willing to submit a PR for this. I'm opening an issue instead just because I can't do it now. Feel free to tackle it, if time allows.

Thank you,
Lucas

**Comment by lucatume** [comment]
I see how this could come in handy.

In essence one should filter the `admin_email_check_interval` filter and return `0`.
Per WP Core comment in the code:

```php
			/**
			 * Filters the interval for redirecting the user to the admin email confirmation screen.
			 *
			 * If `0` (zero) is returned, the user will not be redirected.
			 *
			 * @since 5.3.0
			 *
			 * @param int $interval Interval time (in seconds). Default is 6 months.
			 */
			$admin_email_check_interval = (int) apply_filters( 'admin_email_check_interval', 6 * MONTH_IN_SECONDS );
```

It's a bit tricky to do this in the context of an acceptance test, where one cannot add filters and actions in the test PHP thread and have them have an effect in the PHP thread handling the requests generated by the tests, but it would open the door to a number of other quality-of-test-life improvments.

**Comment by Luc45** [comment]
While I understand what you're saying and agree it would be awesome to have something like that, I think that, for this specific case, perhaps a filter on WPDb before import (like wp-browser already does with the site_url) might be a good option as well.

**Comment by Luc45** [comment]
The way I've been solving this is just changing this value on dump.sql:

`UPDATE wp_options SET option_value='2533080438' WHERE option_name=admin_email_lifespan`

It won't ask for email confirmation, well, at least until 2050.

**Comment by lucatume** [comment]
This is an actually cleaner idea and easier to implement.

Thanks for sharing.

Coming soon, I'd say.
