### ISSUE TITLE
[BUG] haveUserInDatabase does not set nickname

### ISSUE THREAD

**Issue by TimothyBJacobs** [lucatume/wp-browser#359]
**Environment**
OS: Mac
PHP version: 7.3
Installed Codeception version: 3.1.1
Installed wp-browser version: 2.2.31
WordPress version: 5.4
Local development environment: Docker
WordPress structure and management: default

**Describe the bug**
`haveUserInDatabase` does not set the `nickname` for a user. This means if you then try to update the user via the WP Admin, you'll get an error asking to enter a nickname.

`wp_insert_user` [defaults the nickname to the username](https://github.com/WordPress/wordpress-develop/blob/3abe80eea1b1afb571ad52557def05265d9ffbe8/src/wp-includes/user.php#L1681).

**To Reproduce**
```
$I->haveUserInDatabase( 'sally', 'subscriber' );
$I->loginAs( 'sally', 'sally' );
$I->amOnAdminPage( 'profile.php' );
$I->submitForm( '#your-profile', [ 'pass1' => '12345', 'pass2' => '12345' ], 'submit' );
$I->see( 'Profile updated.' );
```

**Expected behavior**
For the nickname to be auto-generated from the username.

**Additional context**
I'm working around the issue by changing my `haveUserInDatabaseCall`.

```
$I->haveUserInDatabase( 'sally', 'subscriber', [ 'meta' => [ 'nickname' => 'sally' ] ] );
```

**Comment by lucatume** [comment]
Thanks @TimothyBJacobs for reporting this. 
Since I have a PR open and this is pretty bad, I will try to squeeze this in there.

I will update this issue w/ news.

**Comment by TimothyBJacobs** [comment]
Thanks for the speedy fix @lucatume!

**Comment by lucatume** [comment]
> Thanks for the speedy fix @lucatume!

Thanks to you for reporting issues with such detail every time, it helps me immensely.
