### ISSUE TITLE
Running WebDriver tests on Travis CI

### ISSUE THREAD

**Issue by JDGrimes** [lucatume/wp-browser#36]
I've been trying to get my WebDriver tests running on Travis CI. See WordPoints/hooks-api#92 and WordPoints/dev-lib#46. What I'm trying to do is set up a PHP server during the Travis build, so that the acceptance tests can be run against whatever version of WordPress and PHP and the plugin that are being tested. So what I basically have is the site running at `localhost:8888` during the Travis build. Then I'm attempting to run the acceptance tests with that as the site URL. The problem I've run into is that the acceptance tester isn't able to log in:

```
1) Failed to save a points reaction in savePointsReactionCept (tests/codeception/acceptance/savePointsReactionCept.php)

 Step  I login as admin 

 Fail  Field by name, label, CSS or XPath element with '#user_login' was not found.

Scenario Steps:

 2. $I->loginAsAdmin() at tests/codeception/_support/AcceptanceTester.php:34

 1. $I->loadSessionSnapshot("admin") at tests/codeception/_support/AcceptanceTester.php:30
```

I'm sure this is due to an issue with how I'm configuring the local server or something, but I'm kind of stuck. I was wondering if maybe somebody out there has already done this and could tell me how they got it to work.

**Comment by lucatume** [comment]
An update on this: I've not forgotten and am trying to get up to speed with Travis CI.
Really not by field but getting there.

**Comment by JDGrimes** [comment]
Thanks for the update @lucatume. I am still working on trying to figure this out myself, though I haven't had a chance to debug it any further for the last few months. If I do find a way to make this work I'll definitely post back here for the benefit of others.

**Comment by lucatume** [comment]
Closing this as stalled. Will re-open if still an issue.

**Comment by JDGrimes** [comment]
I've got WebDriver tests running on Travis CI. Here is a demo: https://github.com/JDGrimes/wp-browser-travis-demo

**Comment by lucatume** [comment]
Thanks!
Digging the code.
I'm closing the issue but will get back to you: it would be nice to link your repository on the README and on Codeception guide.
