### ISSUE TITLE
activatePlugin() won't work on WordPress 4.5 

### ISSUE THREAD

**Issue by dimitrismitsis** [lucatume/wp-browser#37]
As the title suggests the activatePlugin() won't work on WordPress 4.5 because the #ID has been removed from the <table row>

Thank you for all your work!
Cheers!

**Comment by lucatume** [comment]
Thanks for pointing it out; issue was fixed in version [1.10.5](https://github.com/lucatume/wp-browser/compare/1.10.4...1.10.5)
