### ISSUE TITLE
[FEATURE REQUEST] airplane-mode by default

### ISSUE THREAD

**Issue by lucatume** [lucatume/wp-browser#370]
Following along the line of #363, tests, both integration and acceptance, should not fire any external HTTP request unless whitelisted to do so.

This would be active in the `WPLoader` module and in the modules that work in acceptance mode (probably the `WPDb` one by pre-filling all transients or using an extension to position a plugin like [airplane-mode](https://github.com/norcross/airplane-mode) in the WordPress installation mu-plugins directory.

Whatever the form, WordPress installations should be completely isolated in the context of tests.

**Comment by Luc45** [comment]
Generating a dump: 500kb
Size of the dump after deleting two rows in the database for `_transient_feed_MD5_HASH`: 50kb

These transient feeds are WordPress Events and News that shows in the wp-admin panel.

An airplane solution would prevent these from being fetched during tests and being populated as transients again, but the cleanup of the generated dump would have to be manual, right?

**Comment by lucatume** [comment]
I've not considered reducing the database dump file size in this ticket, but I guess it would be a side-effect of it.
I'm working to find the best way to handle this (a plugin activated at run-time? a mu-plugin? side-loaded code?).
The main objective remains to ensure that, during tests, the WordPress installation under test will not make any external HTTP request and, with it, wait for its results.

**Comment by lucatume** [comment]
This has been partly tacked in later releases, closing.
