### ISSUE TITLE
[BUG] Update vlucas/phpdotenv to 4.1+

### ISSUE THREAD

**Issue by Veraxus** [lucatume/wp-browser#371]
PhpDotEnv has been updated from v3 to v4, which slightly changes initialization by forcing you to choose between mutable and immutable initializations. This version of PhpDotEnv is now required by some other very prominent packages like SimpleSAMLphp, which unfortunately makes wp-browser incompatible with them if you are trying to keep up with security updates.

**Comment by lucatume** [comment]
@Veraxus thanks for reporting the issue.

I will look into this and will, probably, remove the `vlucas/phpdotenv` requirement from the package to avoid similar issues in the future.
