### ISSUE TITLE
[BUG] Call to undefined method ReflectionParameter::getType() on php 5.6

### ISSUE THREAD

**Issue by karser** [lucatume/wp-browser#372]
Hello. I upgraded to wp-browser from 2.3 to 2.4.5 and I started getting this error for php 5.6:
```
Fatal error: Call to undefined method ReflectionParameter::getType() in vendor/lucatume/wp-browser/src/tad/WPBrowser/Events/EventDispatcherAdapter.php on line 370
```
Here is the travis build https://travis-ci.org/github/trackmage/trackmage-wordpress-plugin/builds/675929752

If v2.4 doesn't support php 5.6 then specify it in composer.json please.

**Environment**
OS: [e.g. Windows, Mac, Linux]  
PHP version: 5.6
Installed Codeception version: 3
Installed wp-browser version: 2.4.5
WordPress version: 4.9

**Comment by lucatume** [comment]
@karser  Thanks for reporting the issue.

wp-browser should support PHP 5.6 without issues, so that is a bug that will get priority on the rest.
