### ISSUE TITLE
[Error] Class 'WebDriverBy' not found after updating codeception to 4.1.4

### ISSUE THREAD

**Issue by kjnanda** [lucatume/wp-browser#375]
Hi @lucatume,

After I update the packages I am facing this issue. 

one of my codeception file has below code: 

<pre>$optionDivColor = $I->executeInSelenium(function(\Facebook\WebDriver\Remote\RemoteWebDriver $webdriver) {
   return $webdriver->findElement(\Facebook\WebDriver\WebDriverBy::cssSelector('.rtm-media-options '))->getCSSValue('color');
   });
</pre>

Using the above code, I am trying to get the `css property` of the mentioned class and then I am fetching the color of it. 

This is working fine with codeception `2.5.4` where I have not updated the packages but after updating the dependencies, I get the following message for `/facebook/webdriver` package:

**`This package is abandoned and no longer maintained. The author suggests using the php-webdriver/webdriver package instead.`**

So I updated my my composer.json file and below is the code of my composer.json file.

<pre>
{
    "require-dev": {
        "lucatume/wp-browser": "*",
        "codeception/module-webdriver": "*",
        "codeception/module-asserts": "*",
        "php-webdriver/webdriver": "*"
    }
}
</pre>

------

This is the screenshot of the issue I am facing. 

![javalnanda_krupa___Krupa_GitHub_Projects_rtMedia_tests_codeception_and_New_Issue_·_lucatume_wp-browser](https://user-images.githubusercontent.com/15173772/80454122-297d9200-8947-11ea-82e3-e48e79d002e0.png)

-----

Can you please help me how can I resolve this? Or what is missing from my end?

Many Thanks,
Krupa

**Comment by lucatume** [comment]
Hi @kjnanda,

I'm not the maintainer of Codeception and the `WebDriver` package and the method you're trying to use is part of Codeception code, not wp-browser.

And while a dependency might not be maintained, as the `facebook/webdriver` is, it might still work. What if you do not require the `php-webdriver/webdriver` library at all?

Please open this issue on Codeception repository as Codeception developers will provide a better answer than I could.

**Comment by kjnanda** [comment]
Okay,
Thanks
