### ISSUE TITLE
[QUESTION] Integration test not accessing hooked methods?

### ISSUE THREAD

**Issue by dingo-d** [lucatume/wp-browser#381]
**Environment**
OS: MacOS Catalina 10.15.4
PHP version: 7.2.30
Installed Codeception version: 4.1.4
Installed wp-browser version: 2.4.5
WordPress version: 5.4.1  
Local development environment: VVV for acceptance tests, Valet+ for integration tests
WordPress structure and management: default

I want to run an integration test to see if my scripts and styles are loaded correctly. This is the part I'm trying to test out

https://github.com/dingo-d/woo-solo-api/blob/feature/2.0.0-update/src/Assets/EnqueueResources.php#L39-L44

My test looks like this:

```php
<?php

declare(strict_types=1);

namespace Tests\Integration\Enqueue;

use Codeception\TestCase\WPTestCase;
use IntegrationTester;
use MadeByDenis\WooSoloApi\Assets\EnqueueResources;

class EnqueueTest extends WPTestCase
{
	/**
	 * @var IntegrationTester
	 */
	protected $tester;

	public function setUp()
	{
		parent::setUp();
	}

	public function tearDown()
	{
		parent::tearDown();
	}

	public function testAssetsAreEnqueued()
	{
		(new EnqueueResources())->register();

		set_current_screen('woocommerce_page_solo_api_options');

		$scripts = get_echo('wp_print_scripts');

		error_log( print_r( $scripts, true ) );
	}
}

```

I register my hooks, and I expect this to call `enqueueStyles` and `enqueueScripts` methods. When I run the test, the register method gets called (I do `error_log` inside the `register` method, plus it's green in the coverage), but none of the hook callbacks get triggered.

How come? What am I missing? The code works, because I can see my scripts and styles being loaded in the plugin page.

**Comment by Luc45** [comment]
I think you might want to look at a functional test. Something like:

```php
public function should_enqueue_script_on_plugin_page( FunctionalTester $I ) {
	$I->loginAsAdmin();
	$I->amOnAdminPage('my-plugin-page.php');
	$I->seeInSource('my-file.css');
}

public function should_not_enqueue_script_outside_plugin_page( FunctionalTester $I ) {
	$I->loginAsAdmin();
	$I->amOnPluginsPage();
	$I->dontSeeInSource('my-file.css');
}
```

Integration are good to test that, given a certain input, a certain class will provide a certain output. When you are trying to test something that depends on the context (like being on a specific page), it might be a good idea to try a functional or acceptance test.

**Comment by dingo-d** [comment]
Yeah, but I want to write unit and integration tests first since they are much faster than acceptance and functional tests.

Plus this is testing the integration of my plugin with WordPress, so it kinda makes sense to do. 

For instance, I can test (and did) my REST integration tests: https://github.com/dingo-d/woo-solo-api/blob/feature/2.0.0-update/tests/integration/Rest/RestEndpointTest.php

So the code from the plugin is properly adding a new endpoint. 

I'm just a bit puzzled as to why the test isn't going through the enqueue callbacks 🤷‍♂️

**Comment by Luc45** [comment]
> Yeah, but I want to write unit and integration tests first since they are much faster than acceptance and functional tests.

Yes, Functional is slower than Integration.

If you can test what you want to test with Integration, great! If you can do so with Unit, even better!

But, when you are testing something that depends on the context of the request that's taking place, this seems out of the scope for integration tests.

> Plus this is testing the integration of my plugin with WordPress, so it kinda makes sense to do.

![image](https://user-images.githubusercontent.com/9341686/81005878-02323380-8e25-11ea-929f-6ac0c4c361d4.png)

In the context of WordPress, integration tests (or wpunit tests) are those that load the WordPress environment for you, so you can use functions defined by WordPress. Think about ISOLATION LAYERS. The more isolated and independent your tests are, the faster they will run.

- **Unit**: Pure PHP. You are not using WordPress actions in your code.
- **Integration** (or **wpunit**, which is the same thing): PHP + the WordPress environment, so you can run functions defined by WP in your tests and in the code you're testing. This is the most common kind of test in WordPress.
- **Functional**: Send GET/POST requests and run assertions on the response or on what's on the database after these requests have been sent.
- **Acceptance**: Emulate a browser and do the same as Functional, with the difference that you interact in the page as a user would, by clicking stuff, etc.

The higher the abstraction layer, the higher the isolation layer, the slower the tests, because you need to emulate more stuff to prepare the environment for your tests.

Anyway, I think that what you are trying to test fits a Functional. I could be wrong, if I am, I hope someone can correct me. If you want to get creative, you sure can test this in an Integration suite, it just doesn't feel natural to do so, because in a real request, the context that you crafted for your integration test can be different, and that makes it unreliable with what really happens during a request.

**Comment by dingo-d** [comment]
In my current integration test, the one where I actually make a call towards an API is definitely out of the scope of my integration test I agree 😄 

Usually, I mock these (which probably means I'll redo [this](https://github.com/dingo-d/woo-solo-api/blob/feature/2.0.0-update/src/Rest/Endpoints/AccountDetails.php#L43-L58) code so that I can mock it) and I'm just testing that the REST functionality works as intended (like the first one where I'm checking if the endpoint was registered). 

Writing the REST _functionality_ here I see why these would be functional tests 😄 

My idea, when writing integration tests, is to see that the code I added (by hooking to filters or actions) actually works as intended (my script is enqueued, my endpoint is registered). It can be a PITA to do in WP (I know from experience), and to be sure that I'm not breaking any of the intended functionality later on.

I'm leaving functional and acceptance tests for last because they do take the longest to run (plus I need to write acceptance criteria first 😬).

> PS: Nice way of testing REST. I will try that approach at some point.

Thanks 🙂

**Comment by Luc45** [comment]
>  It can be a PITA to do in WP

Yes, it is. It's a painful road to take, one of the hardest endeavors a programmer can commit himself to, especially in the WordPress environment, but it's totally worth it.

About the REST stuff, I think it's worth to note that wp-browser doesn't come with the [REST module](https://codeception.com/docs/modules/REST) by default, which is the module that allows you to test REST endpoints. I've just opened an [issue](https://github.com/lucatume/wp-browser/issues/382) for a feature request to add a REST suite with this module. I'm sure Luca has considered this already, I'm hoping to get some meaningful insight on this.

**Comment by lucatume** [comment]
> I register my hooks, and I expect this to call `enqueueStyles` and `enqueueScripts` methods. When I run the test, the register method gets called (I do `error_log` inside the `register` method, plus it's green in the coverage), but none of the hook callbacks get triggered.
> 
> How come? What am I missing? The code works, because I can see my scripts and styles being loaded in the plugin page.

@dingo-d sorry for the late reply; I've followed the discussion a bit, but wanted to address the original question. I'm reporting the test code you provided and adding comments in line. Let me know if that helps clarify.

```php
public function testAssetsAreEnqueued()
	{
		// At this stage the test method runs on a fresh and clean WordPress installation.
		// So: here WordPress has already initialized and ready to run. 
		// In tests WordPress is running in headless mode: scripts and styles will NOT be enqueued. 
		
		// This method hooks (probably) on the `wp_enqueue_(scripts|styles)` action.
		(new EnqueueResources())->register();
		
		// There is no code here that is firing the two actions, though.

		set_current_screen('woocommerce_page_solo_api_options');

		$scripts = get_echo('wp_print_scripts');

		error_log( print_r( $scripts, true ) );
	}
```

So, @lucas45 suggestion to use a different kind of test is a good one. Testing HTML output is usually not the scope of integration tests like this unless your code completely contains the rendering of the page, or a part of it, in some render method. 

I'm labeling this not as a bug, but as a question.

Let me know if this helps you.

**Comment by dingo-d** [comment]
This helps a bit, but my intention was to check if the enqueued scripts and styles will be registered in WordPress. I know that WP stores all this in some global so I could check it there.

I was looking at this core test: https://github.com/WordPress/wordpress-develop/blob/master/tests/phpunit/tests/dependencies/scripts.php#L42-L58

On another project (that is built in a similar way) I have something like

```php
public function testAssetsAreEnqueued()
{
    global $wp_styles;
    (new EnqueueResources())->register();

    set_current_screen('woocommerce_page_solo_api_options');

    $this->assertContains( EnqueueResources::CSS_HANDLE, $wp_styles->queue );
    $this->assertArrayHasKey( 'wp-pointer', $wp_styles->registered );
}
```

And this works on that project, as the enqueue will add the enqueued script in the `$wp_styles`, and I can find my handle there.

But I'm running that setup on the wp-cli generated plugin test scaffold, so that may be different than the setup in wp-browser.

I just tried this now (while writing):

```
public function testAssetsAreEnqueued()
{
    global $wp_styles, $wp_scripts;
    set_current_screen(OptionsSubmenu::WOO_PAGE_ID);

    (new EnqueueResources())->register();

    (new EnqueueResources())->enqueueScripts(OptionsSubmenu::WOO_PAGE_ID);
    (new EnqueueResources())->enqueueStyles(OptionsSubmenu::WOO_PAGE_ID);

    $this->assertContains(EnqueueResources::CSS_HANDLE, $wp_styles->queue);
    $this->assertContains(EnqueueResources::JS_HANDLE, $wp_scripts->queue);
    $this->assertArrayHasKey('wp-pointer', $wp_styles->registered);
}
```

And this works 🤷‍♂️ 

And the coverage is green, so I think I didn't write the test in the correct way I guess.

Thanks for the help @lucatume and @Luc45 !
