### ISSUE TITLE
[FEATURE REQUEST] Add a REST suite by default

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-browser#382]
**Is your feature request related to a problem? Please describe.**
Yes, I want to be able to test REST endpoints. I can't dispatch a GET/POST request to a REST endpoint with WPBrowser module or similar, which we have now.

**Describe the solution you'd like**
I would like to suggest a suite dedicated for REST tests, with Codeception [REST module](https://codeception.com/docs/modules/REST) doing the job of dispatching and reading responses. Possibly with WPDb and a commented out WPFileSystem (exactly like the Functional one, except with REST instead of WPBrowser).

I think this suite should not have WPBrowser module, since they both dispatch and read responses, there are some method names that are similar, and can cause confusion on the user. They use different transport methods (like different Guzzle instances or something like that), and a user might try to read from the response of WPBrowser using `$I->seeResponseCodeIsSuccessful();`, which is a method from the REST module, and be frustrated and blaming Luca on why it isn't working.

**Comment by lucatume** [comment]
@Luc45 when you say "I would like to suggest a suite" you mean that you think it should be initialized on init?

The REST module from Codeception does require the `PHPBrowser` module, so I would use the `WPBrowser` one.

I see value in having this initialized along, for example, the `WPLoader` module in `loadOnly: true` mode to add some sugar methods for, say, authentication in the REST API.

I'm open to exploration here.

**Comment by Luc45** [comment]
>  you mean that you think it should be initialized on init?

Yes, I think this suite is common enough to be initialized on `init`, and since it requires a Codeception module that isn't bundled by default with WPBrowser, it makes it harder for people to figure out how to create such suite. My intention with this suggestion is to make it easier for folks to run REST tests.

> The REST module from Codeception does require the PHPBrowser module, so I would use the WPBrowser one.

Indeed, I had forgot that, thanks!

> I see value in having this initialized along, for example, the WPLoader module in loadOnly: true mode to add some sugar methods for, say, authentication in the REST API.

That makes sense and is similar to how Functional behaves, which is good for consistency.

**Comment by lucatume** [comment]
This looks like a good idea to me, along with some examples about how to run a WP REST API test and (as an acceptance test) that would include authentication.

Next feature run.

**Comment by lucatume** [comment]
Version 4 will, by default, scaffold an integration (WPLoader) and end-to-end (WPDb, WPFilesystem, WPWebDriver, WPLoader in `loadOnly: true` mode) suite, do you think scaffolding a REST API suite along these would still have value?
