### ISSUE TITLE
[DEPRECIATION NOTICE] Class not properly autoloaded - composer notice

### ISSUE THREAD

**Issue by dingo-d** [lucatume/wp-browser#383]
When running `composer install` on a project I got the following issues mentioned that will impact the usage when Composer v2 comes out (I run optimize autoload after install)

```bash
Deprecation Notice: Class tad\WPBrowser\Configuration\Configuration located in
./vendor/lucatume/wp-browser/src/tad/WPBrowser/Environment/Configuration.php
does not comply with psr-4 autoloading standard.
It will not autoload anymore in Composer v2.0. in phar:///usr/local/Cellar/composer/1.10.5/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
```

I didn't look at it in details, but just wanted to let you know 🙂

**Comment by lucatume** [comment]
@dingo-d Thanks for reporting this, I will fix. this in the next version.
