### ISSUE TITLE
wpcept issues

### ISSUE THREAD

**Issue by crebacz** [lucatume/wp-browser#39]
Hello sir--

The wpcept file in the latest version appears to be pointing to some non-existent classes.  First of all, it seems to have shifted from the Symfony Console Application to a custom Codeception\Application which cannot be found. Similarly, I noticed it is calling a number of new custom commands that do not appear in the Commands directory.

**Comment by lucatume** [comment]
Yep,

very much so: I've mixed dev stuff by mistake. Thanks for pointing  that out.
Should be fixed in version `1.10.9`, closing.
