### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by homejunction** [lucatume/wp-browser#40]
All of a sudden tests starting to fail this morning with the following error:

Parse error: syntax error, unexpected 'require_once' (T_REQUIRE_ONCE), expecting identifier (T_STRING) in /vendor/lucatume/wp-browser-commons/src/tad/WPBrowser/Filesystem/Filesystem.php on line 8

**Comment by lucatume** [comment]
You are using the `master` branch of WPBrowser I guess.

That branch is not a release branch and should not be used in production testing as it could be broken: release branch like `~1.10` should be required instead.

The error per se is a typo I've corrected in the latest `master` version.

**Comment by homejunction** [comment]
Thank you!

**Comment by homejunction** [comment]
Just FYI, I was using the same composer code that you have in your instructions. May be it needs to be updated:
`"require-dev":
    {
      "lucatume/wp-browser": "master@dev"
    }`

**Comment by lucatume** [comment]
Very much so! Thanks again for pointing it out, what a gaffe...
