### ISSUE TITLE
[BUG] Acceptance Test method haveFriend is not available

### ISSUE THREAD

**Issue by arall** [lucatume/wp-browser#403]
**Environment**
OS: Mac / Linux
PHP version: 7.2 / 7.4
Installed Codeception version: 4.1.4
Installed wp-browser version: 2.5.2
WordPress version: [e.g. 5.4]  
Local development environment: Vagrant
WordPress structure and management: default 

**Describe the bug**
Looks like the method `haveFriend` from [Codeception](https://codeception.com/docs/03-AcceptanceTests#Multi-Session-Testing) is not available.

For example:
```php
<?php

$I->loginAsAdmin();
$I->amOnAdminPage('/');
$I->see('Welcome to WordPress!');

$nick = $I->haveFriend('nick');
$nick->does(function(AcceptanceTester $I) {
    $I->loginAsAdmin();
    $I->amOnAdminPage('/');
    $I->see('Welcome to WordPress!');
});
```
Will show the following error:
```
[RuntimeException] Call to undefined method AcceptanceTester::haveFriend 
```

Is there any other way to test multiple sessions?

**Comment by lucatume** [comment]
HI @arall, thanks for taking the time to report this and open an issue.

Are you using, in the acceptance test, the `Friend` trait as [described in Codeception documentation](https://codeception.com/docs/03-AcceptanceTests#multi-session-testing)?

Could you post your suite setup code?

**Comment by arall** [comment]
Ooops, that was it. Sorry, my fault. Thanks for pointing to it!

**Comment by lucatume** [comment]
No worries, I ran into the same issue myself multiple times, I have a first-hand experience of it.

Happy testing!
