### ISSUE TITLE
[FEATURE REQUEST] Reset globals $wp_scripts and $wp_styles between each test

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-browser#409]
**Is your feature request related to a problem? Please describe.**
I want to test code that changes the globals `$wp_scripts` and `$wp_styles`, such as the functions `wp_deregister_style()`, `wp_deregister_script()`, `wp_enqueue_style()` or `wp_enqueue_script()`.

However, since they are globals, their state is affected from one test to the other.

I would like to ask if it would be desirable to minimize this "global state limitation" of WordPress by resetting it to their original state between each test?

**Describe alternatives you've considered**
```php
private $original_wp_scripts;
private $original_wp_styles;

public function setUp() {
	// Before...
	parent::setUp();

	// Your set up methods here.
	global $wp_scripts;
	global $wp_styles;

	if ( is_null( $this->original_wp_scripts ) ) {
		$this->original_wp_scripts = clone $wp_scripts;
	}

	if ( is_null( $this->original_wp_styles ) ) {
		$this->original_wp_styles = clone $wp_styles;
	}
}

public function tearDown() {
	// Your tear down methods here.
	global $wp_scripts;
	global $wp_styles;

	$wp_scripts = $this->original_wp_scripts;
	$wp_styles  = $this->original_wp_styles;

	// Then...
	parent::tearDown();
}
```

**Comment by Luc45** [comment]
I can look into opening a PR for this if it's desirable.

I just var dumped `$GLOBALS` on shutdown to see what kind of globals I've got, and there were 211 globals in that specific request...

<details><summary>List of globals on "shutdown"</summary>

1. Airplane_Mode_Core
2. GLOBALS
3. PHP_SELF
4. _COOKIE
5. _ENV
6. _FILES
7. _GET
8. _POST
9. _REQUEST
10. _SERVER
11. __composer_autoload_files
12. __container_9395ecaf0b07fdbb
13. _wp_additional_image_sizes
14. _wp_admin_css_colors
15. _wp_default_headers
16. _wp_deprecated_widgets_callbacks
17. _wp_post_type_features
18. _wp_registered_nav_menus
19. _wp_sidebars_widgets
20. _wp_theme_features
21. _wp_using_ext_object_cache
22. allowedentitynames
23. allowedposttags
24. allowedtags
25. attachment
26. attachment_id
27. author
28. author__in
29. author__not_in
30. author_name
31. authordata
32. block_core_latest_posts_excerpt_length
33. blog_id
34. cache_results
35. cat
36. category__and
37. category__in
38. category__not_in
39. category_name
40. comment
41. comments_per_page
42. compress_css
43. compress_scripts
44. concatenate_scripts
45. content_width
46. current_screen
47. current_user
48. currentday
49. currentmonth
50. custom_background
51. custom_image_header
52. day
53. debug_bar
54. editor_styles
55. embed
56. error
57. feed
58. fields
59. hour
60. id
61. ignore_sticky_posts
62. is_IE
63. is_IIS
64. is_NS4
65. is_apache
66. is_chrome
67. is_edge
68. is_gecko
69. is_iis7
70. is_iphone
71. is_lynx
72. is_macIE
73. is_nginx
74. is_opera
75. is_safari
76. is_winIE
77. jetpack_packages_classes
78. jetpack_packages_files
79. l10n
80. l10n_unloaded
81. lazy_load_term_meta
82. locale
83. m
84. menu_order
85. meta_key
86. meta_value
87. minute
88. month
89. month_abbrev
90. monthnum
91. more
92. multipage
93. name
94. no_found_rows
95. nopaging
96. numpages
97. order
98. p
99. page
100. page_id
101. paged
102. pagename
103. pagenow
104. pages
105. pass_allowed_html
106. pass_allowed_protocols
107. post
108. post__in
109. post__not_in
110. post_name__in
111. post_parent
112. post_parent__in
113. post_parent__not_in
114. post_type
115. post_type_meta_caps
116. posts
117. posts_per_page
118. preview
119. product
120. product_search_form_index
121. qm_class
122. qm_dir
123. query_string
124. request
125. required_mysql_version
126. required_php_version
127. s
128. second
129. sentence
130. shortcode_tags
131. show_admin_bar
132. sidebars_widgets
133. single
134. storefront
135. storefront_version
136. subpost
137. subpost_id
138. suppress_filters
139. table_prefix
140. tag
141. tag__and
142. tag__in
143. tag__not_in
144. tag_id
145. tag_slug__and
146. tag_slug__in
147. tag_templates
148. tb
149. template
150. template_getter
151. timestart
152. tinymce_version
153. title
154. tribe-common-info
155. update_post_meta_cache
156. update_post_term_cache
157. update_schema
158. user_ID
159. user_email
160. user_identity
161. user_level
162. user_login
163. user_url
164. userdata
165. w
166. wc_order_types
167. wc_product_attributes
168. wc_queued_js
169. weekday
170. weekday_abbrev
171. weekday_initial
172. woocommerce
173. wp
174. wp_actions
175. wp_admin_bar
176. wp_cockneyreplace
177. wp_current_filter
178. wp_customize
179. wp_db_version
180. wp_did_header
181. wp_embed
182. wp_filesystem
183. wp_filter
184. wp_header_to_desc
185. wp_local_package
186. wp_locale
187. wp_locale_switcher
188. wp_object_cache
189. wp_plugin_paths
190. wp_post_statuses
191. wp_post_types
192. wp_query
193. wp_registered_sidebars
194. wp_registered_widget_controls
195. wp_registered_widget_updates
196. wp_registered_widgets
197. wp_rest_auth_cookie
198. wp_rewrite
199. wp_roles
200. wp_scripts
201. wp_smiliessearch
202. wp_styles
203. wp_taxonomies
204. wp_the_query
205. wp_theme_directories
206. wp_user_roles
207. wp_version
208. wp_widget_factory
209. wpdb
210. wpsmiliestrans
211. year

</details>

I don't know if it makes sense to try to reset some key globals like `$wp_scripts` and `$wp_styles` between each test, or reset `$GLOBALS` except some of them, such as `SERVER`, `POST`, etc. Part of me tells me it's good for isolation. Another part of me tells me this is a Pandora box that we might not want to open... But, after all, I think it's the price we pay to test WordPress.

**Comment by lucatume** [comment]
This seems like a feature that is kind of a "given", so making it more robust would not hurt.

A PR is very much welcome, but it would make sense to, probably, do this same check on *all* super-globals and reset them all to the state they have before each test.
The code already has part of it, but it's not been updated in a bit and might not be so up-to-date.

**Comment by Luc45** [comment]
Do you think it would make sense to explore `backupGlobals="true"` in PHPUnit XML configuration?

https://phpunit.readthedocs.io/en/9.0/fixtures.html#global-state

**Comment by lucatume** [comment]
The reason for the setting to `false` by default is that at, the time, it did create a number of issues. 
It could be worth revisiting, though.
One issue I'm aware of is that closures will not correctly be serialized (it will happen during the initial backup) and that will throw a fatal.
I use closures to set up some pre-conditions myself and a change to `$backupGlobals = true` would break back-compatibility with existing projects.
I think, to solve the original issue, a first, less impactful, approach would be a curated list of globals that have to be reset.
