### ISSUE TITLE
WP installation removes custom DB tables/fields

### ISSUE THREAD

**Issue by jbrinley** [lucatume/wp-browser#41]
One of the big differences between the WP boostrap in WPLoader and that in the WordPress phpunit test suite is that the latter runs `install.php` in a separate process. I've been running into problems of late with plugins that add custom DB tables and fields, because WPLoader runs it in the same process.

Example: You have a plugin that adds a table on `init`. This happens when `install.php` includes `wp-settings.php`. Then all the tables are removed and re-installed farther down the file. At this point, `init` has already run, and the `require_once rtrim( ABSPATH, '/\\' ) . '/wp-settings.php';` in `bootstrap.php` isn't going to do anything. Any tests that expect the table to be there will fail.

I'm currently working around this by:

1. Importing a correct database
2. Modifying `bootstrap.php` to removed the `require 'install.php';`
3. Further modifying `bootstrap.php` to add `$table_prefix = WP_TESTS_TABLE_PREFIX;` (otherwise you get an error when `wp-settings.php` loads)

Would it be possible to add a flag to the config to skip the install? Or perhaps check if WP is already installed and skip installation if it is? Or run the installation in a separate process as WordPress does?

**Comment by lucatume** [comment]
First idea that comes to mind and the path of less resistance is to use the `bootstrapActions` parameter in `WPLoader` config to run the action in charge of creating the tables and to hook the table creation method to a test action.
E.g.

```php
add_action( 'init', [ $tables, 'maybe_create_tables' ] );

// probably not in production code but in a tests config file
add_action( 'test_init_alias', [ $tables, 'maybe_create_tables' ] );
```

and in `WPLoader` configuration file:

```yaml
bootstrapActions:
    - test_init_alias
```

Running the installation in a separate process is not an impossible task though and I might explore it but I'd like to try easier solutions first.

**Comment by lucatume** [comment]
An update on this: I've pushed a first draft code to the https://github.com/lucatume/wp-browser/tree/enhance/separated-process-install branch.
For the time being it does little but replicate what the core testing suite does but that's a start.
Will iterate on this.

**Comment by jbrinley** [comment]
Yes, this works (almost).

I had to make one change in isolated-install.php. After the defines loop (lines 10-12), I added:

```php
$table_prefix = WP_TESTS_TABLE_PREFIX;
```

Otherwise all the tables are created with no prefix.

**Comment by lucatume** [comment]
Thanks for pointing it out; I've pushed a commit to the branch to fix that.

I've left the code in a branch as I've not yet taken the time to verify all the functionalities; what's that "almost" about?

**Comment by jbrinley** [comment]
> what's that "almost" about?

Just the table prefix comment.

Also, I note that a custom `WP_CONTENT_DIR` doesn't carry through to the install. That's probably fine, but it does mean that custom tables created by plugins aren't deleted when the core tables are deleted. That works well for my purposes, but I'm not sure if it's a feature or a bug.

**Comment by lucatume** [comment]
Ok, thanks.

I will look into the `WP_CONTENT_DIR` issue as the expected behaviour is to carry over (I guess).

**Comment by lucatume** [comment]
Refreshing the issue: how is this going?

**Comment by lucatume** [comment]
Closing the issue due to lack of activity, should this not be resolved I will re-open.
