### ISSUE TITLE
[DOC BUG] Site TLS certificate issue?

### ISSUE THREAD

**Issue by dingo-d** [lucatume/wp-browser#418]
When going to https://wpbrowser.wptestkit.dev/ I get an error in Chrome 

![Screenshot 2020-06-04 at 13 31 01](https://user-images.githubusercontent.com/8638515/83751746-a64b0c80-a667-11ea-819b-55abaede79e6.png)

**Comment by lucatume** [comment]
It seems like this was a fluke of the hosting provider (GitBook) as it was down all day for me and just came back online.

It's now showing correctly w/ a valid certificate.

Thanks!
