### ISSUE TITLE
[BUG] activateFurtherPlugins didn't work on init setup

### ISSUE THREAD

**Issue by cliffordp** [lucatume/wp-browser#424]
**Environment**
OS: Mac
PHP version: 7.4.6
Installed Codeception version: 4.1.6
Installed wp-browser version: 2.6.2
Local development environment: Local (Lightning)

**Describe the bug**
I ran `vendor/bin/codecept init wpbrowser` to initially setup WP Browser for my plugin. When it [asked me which other plugins should be activated](https://github.com/lucatume/wp-browser/blob/2.6.2/src/Codeception/Template/Wpbrowser.php#L445), it did not actually add them to my config (see screenshot).

**Expected behavior**

**Screenshot**
![image](https://user-images.githubusercontent.com/1812179/86082331-1aa57f80-ba5d-11ea-9610-5dffba3a8f83.png)

**Comment by lucatume** [comment]
@cliffordp thanks for taking the time to report the issue and provide details.
I will look into this and update this issue with news when I have some.

**Comment by lucatume** [comment]
Fixed in version `2.6.3`, thanks again for reporting this.
