### ISSUE TITLE
[BUG] Notice: Undefined index: value in "...\vendor\lucatume\wp-browser\src\tad\WPBrowser\env.php" on line 49

### ISSUE THREAD

**Issue by overclokk** [lucatume/wp-browser#427]
**Environment**
OS: Windows 
PHP version: 7.2
Installed Codeception version: 4.1.6  
Installed wp-browser version:  2.6.3
WordPress version: latest 
Local development environment: XAMPP
WordPress structure and management: default

**Output**
`Notice: Undefined index: value in E:\xampp\htdocs\moduli\wp-content\plugins\finder\vendor\lucatume\wp-browser\src\tad\WPBrowser\env.php on line 49`

**To Reproduce**
I found this issue with an .env file that I use for many similar project, this is the .env file generated by an old version of WPBrowser, as you can see I have empty value in "password" fields:

```
TEST_SITE_DB_DSN="mysql:host=localhost;dbname=test"
WP_ROOT_FOLDER="/tmp/wordpress"
TEST_SITE_WP_ADMIN_PATH="/wp-admin"
TEST_SITE_DB_NAME="test"
TEST_SITE_DB_HOST="localhost"
TEST_SITE_DB_USER="root"
TEST_SITE_DB_PASSWORD=""
TEST_SITE_TABLE_PREFIX="wp_"
TEST_DB_NAME="wploader"
TEST_DB_HOST="localhost"
TEST_DB_USER="root"
TEST_DB_PASSWORD=""
TEST_TABLE_PREFIX="wp_"
TEST_SITE_WP_URL="http://wp.localhost"
TEST_SITE_WP_DOMAIN="wp.localhost"
TEST_SITE_ADMIN_EMAIL="admin@wp.localhost"
TEST_SITE_ADMIN_USERNAME="admin"
TEST_SITE_ADMIN_PASSWORD="password"
```

I see that now in the .env file generate by the latest WPBorwser values are not surrounded by quotation marks:

```
# Example
TEST_SITE_DB_DSN=mysql:host=localhost;dbname=test
WP_ROOT_FOLDER=/tmp/wordpress
TEST_SITE_WP_ADMIN_PATH=/wp-admin
TEST_SITE_DB_NAME=test
TEST_SITE_DB_HOST=localhost
TEST_SITE_DB_USER=root
TEST_SITE_DB_PASSWORD=
..... # the rest of the file
```
For now I just solved by removing the quotation marks from the empty fields but I notice that in https://github.com/lucatume/wp-browser/blob/e9797f2fc919ffe246b66ecfef517b895ed158e6/src/tad/WPBrowser/env.php#L49 there is no check if `$m['value']` is set.

**Comment by lucatume** [comment]
@overclokk thanks for reporting the issue and taking the time to provide the details. I will look into this and update this issue with the news. 

From the look of it, it looks like something I _should_ have covered in tests but did not. I use an empty password value as well and did not run into any issue so far.

**Comment by overclokk** [comment]
The problem I found is not the empty password itself but the `""`

This does not work: `TEST_DB_PASSWORD=""`

This works: `TEST_DB_PASSWORD=`

**Comment by Luc45** [comment]
I've faced the same issue. Removing quotes worked for me as well.
