### ISSUE TITLE
Questiot: How can I add an image to a post?

### ISSUE THREAD

**Issue by adc-nsaraiva** [lucatume/wp-browser#434]
First of all I just want to say that this is an awesome project. Congrats for the great work!

So I was trying to associate an image to a post for testing purposes and I haven't found a way to do that through any method.

I noticed that in the past you had methods like this one:
`$I->haveFileAttachedToPostInDatabase`

But now I can't find any other than this `$I->haveAttachmentInDatabase`

So is there any way to do this now?

Cheers and sorry if I posted this question in the wrong place

**Comment by lucatume** [comment]
Hi @adc-nsaraiva,

thanks for the support and the feedback.

I had removed the method due a faulty implementation and never added a replacement for it.
I've included two new methods in release `2.6.7`, update and you should be able to do this:

```php
$attachmentId = $I->haveAttachmentInDatabase(codecept_data_dir('some-image.png'));
$postId = $I->havePostInDatabase();
$I->havePostThumbnailInDatabase($postId, $attachmentId);
```

See [documentation](https://wpbrowser.wptestkit.dev/modules/wpdb#havepostthumbnailindatabase).

Happy coding!
