### ISSUE TITLE
[BUG] PhpOption and env() issues when updating

### ISSUE THREAD

**Issue by BrianHenryIE** [lucatume/wp-browser#439]
I updated from 2.4.2 to 2.6.9 on a project and some tests stopped working.

`Class 'PhpOption\Option' not found`

on

`$I->amOnPluginsPage();`

fixed by 

`composer require phpoption/phpoption --dev`

And

`Class 'Dotenv\Environment\Adapter\EnvConstAdapter' not found`  

on

`$smtp_server = env( 'SMTP_SERVER' );`

fixed with 

`$smtp_server = $_ENV[ 'SMTP_SERVER' ];`

I had accidentally submitted this bug report as I was taking notes, but then figured it out myself so don't actually need help! Might be useful for someone searching.

**Environment**
OS: Mac
PHP version: 7.4
Installed wp-browser version: 2.6.9
WordPress version: 5.5
Local development environment: MacOS Apache
WordPress structure and management: default

**Comment by lucatume** [comment]
@BrianHenryIE thanks for taking the time to open the issue and correctly guessing it might help someone else. I will flag this as "wontfix" and leave this open for a bit to capture others looking for a similar issue.

Thanks and happy coding.
