### ISSUE TITLE
Compatibility with Trellis and other setups with custom directory structure

### ISSUE THREAD

**Issue by sformisano** [lucatume/wp-browser#44]
Hi folks,

just learned about wp-browser today. I tried playing with it through a wordpress bedrock instance on a vagrant trellis box (if you're not familiar with these projects https://roots.io )

The first issue I stumbled upon is the WPLoader ensureWpRoot method
https://github.com/lucatume/wp-browser/blob/master/src/Codeception/Module/WPLoader.php#L156-160

Many setups today ( including the wordpress bedrock one ) treat WordPress as a dependency and then have a separate wp-content directory elsewhere, where all the instance code lies.

Like I said Bedrock is one such setup, so this is what happens:

* if I give the correct root project directory, the ensureWpRoot method fails as wp-settings.php is under the wp subdirectory

* if I try to give it the path to the wp subdirectory, the wp-content directory inside the wp directory is not the one that should be referenced as it only holds the default content (remember, the *real* wp-content directory is elsewhere, in this specific instance, it's the /project-root/web/app directory)

I have not looked extensively into the wp-browser codebase - do you guys think this is something that could be addressed easily?

The first hint that comes to mind is that maybe rather than looking for wp-settings.php to ensure we're in a wp project root, one could be trying to load the index.php file and seeing if doing that defines the standard wp constants plus eventually any custom ones.

In the trellis case, the index.php file loads the usual files in chain plus the bedrock specific one:

wp-blog-header.php > wp-load.php > wp-config.php > /config/application.php

the /config/application.php is where bedrock defines the CONTENT_DIR/WP_CONTENT_DIR/WP_CONTENT_URL constans and so on...

The trellis/bedrock setup is a good environment and I'm sure more and more devs will either adopt it or follow similar patterns to have both wp core and plugins managed as dependencies.

Supporting this kind of environment may be something worth looking into.

Thoughts?

**Comment by lucatume** [comment]
Hi, thanks for reaching out.

WPLoader will cover, out of the box, most installations but not all. That's why an additional `configFile` parameter is provided. I'm currently out and cannot look into your issue extensively before Monday but can point you to [an article I wrote about Bedrock](http://theaveragedev.com/setting-wpbrowser-bedrock/) that could help. 

Keep me posted.

**Comment by lucatume** [comment]
Refreshing this issue: how is this going?

**Comment by sformisano** [comment]
Hey Luca, I am once again using wp-browser for another plugin and I went through the awesome command line setup walkthrough, everything seems to work quite smoothly so far. For anyone using Trellis in unison with Bedrock just be sure to allow external connections from your mysql inside your vagrant box.

Just thought I'd let people know that wp-browser seems to do fine with bedrock now if they stumble on this thread.

Cheers.

**Comment by lucatume** [comment]
Thanks for the tip. I will add this to the README as soon as I get back to work.
