### ISSUE TITLE
Update package symfony/filesystem for compatibility with Symfony 

### ISSUE THREAD

**Issue by wppunk** [lucatume/wp-browser#440]
**Environment**
OS: Linux
PHP version: 7.4
Installed Codeception version: 4.1
Installed wp-browser version: latest
WordPress version: 5.5
Local development environment: Local by Flywheel
WordPress structure and management: default

Could you upgrade a `symfony/filesystem` package for compatibility with my packages:

`composer.json`:
```
"require": {
    "symfony/dependency-injection": "^5.1",
    "symfony/config": "^5.1"
}
"require-dev": {
    "codeception/codeception": "^4.1",
    "codeception/module-asserts": "^1.2",
    "codeception/module-db": "^1.0",
    "codeception/aspect-mock": "^3.1",
    "codeception/module-webdriver": "^1.1"
}
```

**Comment by lucatume** [comment]
Thanks @wppunk for taking the time to open the issue.

I'm starting a branch to test out what the dependency update would entail; it might be less straight-forward than intended since wp-browser has to keep being compatible with PHP 5.6 and Codeception 2.5+.

I will keep you posted in this issue.

**Comment by wppunk** [comment]
@lucatume Recently we have been testing all our projects on PHP7.4 and we provide support for PHP 5.5 using [PHPCompatibility](https://packagist.org/packages/phpcompatibility/php-compatibility) library inside coding standard.

Downgrade helped me. 

`composer.json`:
```
"require": {
    "symfony/dependency-injection": "^4.0",
    "symfony/config": "^4.0",
    "symfony/filesystem": "3.4.9",
    "symfony/process": "4.4.9"
}
"require-dev": {
    "codeception/codeception": "^4.1",
    "codeception/module-asserts": "^1.2",
    "codeception/module-db": "^1.0",
    "codeception/aspect-mock": "^3.1",
    "codeception/module-webdriver": "^1.1",
    "lucatume/wp-browser": "^2.6"
}
```

If it is not possible to raise the PHP version, then you can close the question. But it would be awesome if there was an opportunity to update.

**Comment by lucatume** [comment]
@wppunk I'm currently not planning on updating the minimum required PHP version and am sticking with what Codeception supports.
I've merged a PR to remove the block on the `symfony/filesystem` dependency, though, in `2.6.10` that might solve your problem here.

Let me know if that version does solve the issue, run `composer update lucatume/wp-browser` to pull the latest version of it.

**Comment by wppunk** [comment]
@lucatume Thank you, works just awesome.

**Comment by lucatume** [comment]
Excellent, thanks for confirming.

I will close the issue, then.
