### ISSUE TITLE
[DOC REQUEST] Manually reset WPDB sql dump at start of test

### ISSUE THREAD

**Issue by halmos** [lucatume/wp-browser#446]
**Did you search the documentation first?**
Yes

**What do you think is missing from the documentation?**
The documentation describes how to use config settings for WPDb `populate` and `cleaunp` settings. It also describes the `importSqlDumpFile` command, but i don't think this is available from within a wpunit test suite. 

**Do you have any examples of what you'd like to see added to the documentation?**

I understand that the WPDB config `cleanup` setting allows for the db to be reset after each test. In my experience doing so substantially slows down the testing process. Instead, I would like to only reset the DB after each test file runs (and in this way, have control over what data is available in a suite of tests), or, otherwise, see if I can use the `importSqlDumpFile` command to manually reset the db as needed. As far as I am able to tell, this command is not available from within the wpunit test suite (i.e I cannot access `$I` from within wpunit tests), is that correct ? 

I'm not sure if this an issue with the documentation or if what I want to do is not possible, but any assistance would be appreciated. 

Many thanks...

**Comment by JohnDeeBDD** [comment]
Suggestion: Have your acceptance tests clean up after themselves. i.e. if you make a post, delete it at the end of the test. A passing acceptance test should undo whatever artifacts it creates as part of the test. That way, you can set populate: true, and cleanup: to false, which is much faster. This will run the SQL dump ONCE per run - at the start of the suite. This has negative and positive side effects. The negative side is that there can be random artifacts mixing from other tests - true. Something can go wrong in one test, and potentially mess up another test. This makes them not actual unit tests, which as far as I'm concerned: who cares? I don't see that as a negative! Besides, I also run a unit suite separately. Look, WordPress is brittle. That's life. I find that running acceptance tests and forcing them to clean up after themselves makes the whole suite more robust.

**Comment by lucatume** [comment]
HI @halmos,

in the context of "WordPress Unit" tests, the one using the `WPLoader` module with the `loadOnly` setting set to `false` (the standard configuration of the `wpunit` suite, then you should not use the `WPDb` module at all.

The `WPDb` module *and* the `WPLoader` one (again with `loadOnly: false` or not set) will *both* try to set up the database before the tests: the first dropping the current contents and reimporting a SQL dump file (or files), the second setting up a clean and empty WordPress installation from scratch.

In the context of "WordPress unit tests" (really integration tests), I would not use the `WPDb` module at all.

Could you try and describe what you're trying to do and what tests you're trying to run?

**Comment by halmos** [comment]
Thank you both for your assistance. I do in fact have the `WPLoader`'s `loadOnly` set to `true` so that I can load a unit test DB with the WPDb module. This allows us to easily create and modify complex db fixture scenarios for our wpunit tests. We make extensive use of ACF, so manually adding all the necessary post meta in the test suite is not very practical and also results in a situation where it is possible that the test data and the real-world acf post meta keys do not align, but still result in passing tests) . 

I have been taking the same approach as @JohnDeeBDD in the past, but I think it would lead to less fragile testing if I could better control the state of the test DB. For example, if a test fails due to error, then any cleanup I would normally take may not execute. In this situation, the state of the DB would be unknown for subsequent test files.

For this reason, I think it would be very helpful to have a bit more control of how and when the test DB is reloaded. 

Thanks again for all your hard work on this project.

**Comment by lucatume** [comment]
@halmos thanks for clarifying your use case, not an uncommon one and not an outlandish request.

Could you provide some example code of the API (functions, methods and the like) you would envision having at your disposal to provide this? I'm asking as it's easier, for me, to start working "from the end" and know the API I would have to, ideally, fulfill for something to be useful and usable.

My gut feeling would be a trait to provide methods that could be used by any test case class in the test methods.
Example:

```php

use tad\WPBrowser\Traits\WithSqlDumps;

class MyWPUnitTest extends WP_UnitTestCase {
    use WithSqlDumps;

    // In this test the fixture is complex enough to be handled in a transaction.
    public function test_something_with_complex_sql_fixture(){
        // From the WithSqlDumps trait.
        $fixture = $this->importSql( codecept_data('sql/complex-fixture-1.sql'));
    
       $this->assertSomething('foo');

       // Roll-back the transaction.
       $fixture->rollback();
    }
    
    public function test_something_with_simple_sql_fixture(){
        // From the WithSqlDumps trait.
        $fixture = $this->importSql( codecept_data('sql/simple-fixture-1.sql'));
       // Commit the fixture.
       $fixture->commit();

       $this->assertSomething('foo');

      // Since this is a simple fixture, the rollback is a curated one by the dev team.
      wp_delete_post(23, true);
      wp_delete_post(89, true);
    }
}
 ```

I think the transactional-by-default nature of the feature is a requirement to allow clean rollbacks, the downside is the loss of introspectability. The whole handling of errors is not outlined in my example, but that's meant as the start of a conversation.

Let me know what you think and what you think could be better or different.

Question: is the auto-cleanup of inserted rows performed by the `Db` module, and by extension by the `WPDb` module, not enough? I guess not, but want to confirm.

Finally: thanks for the appreciation, goes a long way.

**Comment by halmos** [comment]
Hi @lucatume,

The approach shown in the example code would certainly offer a lot of control. How do you imagine the `$fixture` object interacts with the WPDb module? or are they orthogonal? Could you explain further how the `commit()` functions? 

The existing WPDb auto-cleanup function is indeed a possible solution for my current needs - but unfortunately it also significantly slows down my tests. For that reason, I was hoping to have more control to perform the cleanup only at the end of each test file rather than after each test method. 

With that said, the ability to swap fixture DBs between tests - as in your example above - would definitely be a cool feature and would allow for a lot of new testing strategies!

**Comment by lucatume** [comment]
> The approach shown in the example code would certainly offer a lot of control. How do you imagine the `$fixture` object interacts with the WPDb module? or are they orthogonal? Could you explain further how the `commit()` functions?
>

The trait would provide an API to import a SQL dump in the current database, however, the current database state came to be in its current state. It would not assume the existence of the `WPDb` module or its use.
The `commit()` method would commit the transaction to the database; by default, the mode should be a transaction.
 
> The existing WPDb auto-cleanup function is indeed a possible solution for my current needs - but unfortunately it also significantly slows down my tests. For that reason, I was hoping to have more control to perform the cleanup only at the end of each test file rather than after each test method.

I think you're confusing the `cleanup` setting with the "remove rows inserted during tests" operation the `Db*` modules will perform: if during your tests you're only inserting rows, then those will be removed at each test end. Insertions only, though, not updates or deletions.

> With that said, the ability to swap fixture DBs between tests - as in your example above - would definitely be a cool feature and would allow for a lot of new testing strategies!

The problem is that loading per-test SQL fixtures can only be done if those swaps happen in a transaction that is rolled back at the end of the test. Or if someone puts together a really curated custom cleanup function like the [one leveraging events](https://wpbrowser.wptestkit.dev/events-api) and uses it to either remove the inserted lines or restore the DB to a state using a smaller SQL dump that will only reset the used tables.

@halmos before moving further with anything, though: could you provide an example of the test code you're trying to write and the relevant suite configuration file (`<suite>.suite.yml` or `<suite>.suite.dist.yml`)?

**Comment by halmos** [comment]
I'm afraid I don't have the necessary expertise with sql to advise on the best approach for the api or managing its state during unit tests. Perhaps what I am looking to do is already available by way of the testing transaction api (?). 

FWIW, here's my modified `wpunit.suite.yml`:

```yml
actor: WpunitTester
modules:
  enabled:
    - WPDb
    - WPLoader
    - \Helper\Wpunit
  config:
    WPDb:
      dsn: "%TEST_SITE_DB_DSN%"
      user: "%TEST_SITE_DB_USER%"
      password: "%TEST_SITE_DB_PASSWORD%"
      dump: "tests/_data/local.sql"
      populate: true
      cleanup: false
      waitlock: 10
      url: "%TEST_SITE_WP_URL%"
      urlReplacement: false
      tablePrefix: "%TEST_SITE_TABLE_PREFIX%"
    WPLoader:
      loadOnly: true
      wpRootFolder: "%WP_ROOT_FOLDER%"
      dbName: "%TEST_DB_NAME%"
      dbHost: "%TEST_DB_HOST%"
      dbUser: "%TEST_DB_USER%"
      dbPassword: "%TEST_DB_PASSWORD%"
      tablePrefix: "%TEST_TABLE_PREFIX%"
      domain: "%TEST_SITE_WP_DOMAIN%"
```

and here is a simple test method that modifies a some user meta that was originally set up by ACF:

```php
// test adding ACF user meta
public function testAddAutoInstitutionUpdatesExisting(): void {
        $User = wp_set_current_user( Fixtures::$users['unaffiliated_customer'] );
        $User_Store = artxt\v1\stores\Store::factory( $User->ID, 'user' );
        $User_Store->addAutoInstitution( Fixtures::$institutions['uni'], 'ip', '+1 days' );
        $auto_institutions = $User_Store->getAutoInstitutionsData();
        $this->assertEquals( 1, count( $auto_institutions ) );
        $this->assertEquals( '+1 days', $auto_institutions[0]['expiration'] );

        //  --->>> would like to roll back changes to DB here <<<---- 
}

// test removing ACF user meta
 public function testRemoveAutoInstitution(): void {
        $User = wp_set_current_user( Fixtures::$users['unaffiliated_customer'] );
        $User_Store = artxt\v1\stores\Store::factory( $User->ID, 'user' );
        $User_Store->removeAutoInstitution( Fixtures::$institutions['test'] );
        $auto_institutions = $User_Store->getAutoInstitutionsData();
        $this->assertEquals( 1, count( $auto_institutions ) );
        $this->assertEquals( Fixtures::$institutions['uni'], $auto_institutions[0]['post_id'] );
}
```

I think a full db reset at prescribed points in the test would be most useful for our current needs. In particular, it would be quite useful for any cleanup to occur regardless of whether that test errors or fails, leaving the test in a known state. 

For that reason, my initial thought would be that each test file could conditionally set the state of the DB. By either 1) importing a fixture sql dump (which would offer most granular control) or, 2) just reset the WBDb  back the dump file (which at least would allow for control of timing of reset). Ideally this would be performed at either start of a test method by way of the `setup()` / `tearDown()` methods or at the start of test group using `wpSetUpBeforeClass()` / `wpTearDownAfterClass` or within the test method itself. 

Thanks for your thoughts on this. In  the meantime I will read up on the `start_transaction()` and `commit_transaction()` test methods, but my initial understanding is that that approach would not allow me to rollback data removal...

**Comment by lucatume** [comment]
@halmos I have to dig a bit and try out some things, the transaction methods should help you here.

One question: could you post the full body of the test case you've taken those test methods from? I guess it's an extension of the `WPTestCase` class but would like to be sure.

**Comment by halmos** [comment]
Hi, 
I'm not able to post the entire test file for security reasons, but it is indeed an extension of `WPTestCase`

**Comment by lucatume** [comment]
I understand, no worries and thanks anyways.

Please, confirm I'm getting this right: 

1. You would like to run *integration* tests (or "WordPress unit tests") not starting from a clean slate (as the `WPLoader` would normally do), but from a known database fixture.
2. In *some* test methods you would like to layer, on top of that known starting database fixture, some additional SQL to define more states.
3. The fixture applied in 2 should not persist across tests, but only apply to the tests methods where used.

I'm trying to get the ducks in a row to understand the problem correctly to see what room there is for improvement.

**Comment by halmos** [comment]
Hi, 

1. Correct
2. to clarify, I don't require the option to load an additional SQL dump as a layer over the setup fixture DB (loaded by the WPDb module for example), but I do need to be able to use the Wordpress API such that modifications to the fixture DB allow for introspection. 
3. Correct

**Comment by lucatume** [comment]
Thanks for confirming, I will look into this and see what comes out.

**Comment by halmos** [comment]
thank you! - wp-browser has made developing and testing WP so much more deterministic. Your efforts are greatly appreciated.

**Comment by lucatume** [comment]
Thanks for the appreciation, goes a long way.
