### ISSUE TITLE
[BUG] recurseRemoveDir leaves behind empty directories.

### ISSUE THREAD

**Issue by TimothyBJacobs** [lucatume/wp-browser#447]
**Environment**
OS: Mac
PHP version: 7.3.18
Installed Codeception version: 3.1.1
Installed wp-browser version: 2.6.10
WordPress version: 5.5
Local development environment: Docker
WordPress structure and management: Default

**Describe the bug**
Calling the `recurseRemoveDir()` function leaves behind empty directories.

**Expected behavior**
For the directory to be emptied and deleted.

**Additional context**
I think this was broken in https://github.com/lucatume/wp-browser/commit/6319e9a120373727bb70794a7900a870ac3f2684.

This fixes the issue for me.

```php
function recurseRemoveDir( $target ) {
	if ( ! file_exists( $target ) ) {
		return true;
	}

	$iterator = new \FilesystemIterator( $target, \FilesystemIterator::SKIP_DOTS );
	foreach ( $iterator as $file ) {
		if ( is_dir( $file->getPathname() ) ) {
			if ( ! recurseRemoveDir( $file->getPathname() ) ) {
				return false;
			}
		} elseif ( ! unlink( $file->getPathname() ) ) {
			return false;
		}
	}

	if ( ! rmdir( $target ) ) {
		return false;
	}

	return true;
}
```

**Comment by lucatume** [comment]
@TimothyBJacobs thanks for taking the time to report the issue and provide a fix, I will look into this and update this issue as soon as I can get to it.

**Comment by TimothyBJacobs** [comment]
thanks for the fix @lucatume!
