### ISSUE TITLE
Question: enabling wpcept command

### ISSUE THREAD

**Issue by spectrus** [lucatume/wp-browser#46]
Hi, 

I can't seem to enable the `wpcept` command. I am able to have `WPBrowser` and `WPRequests` enabled in, say, acceptance.suite.yml (`codecept build` executes without errors), but it feels like I'm missing an obvious step. Do I need to enable all the modules? Do I need to do something outside of the suites' `.yml` files? In `codeception.yml` perhaps?

**Comment by lucatume** [comment]
You should not need to do anything: the `bin` instruction in WPBrowser `composer.json` file should take care of that.
Some questions to help me debug the issue:

1. have you installed Codeception globally or locally to the project?
2. are you on a *nix machine or Windows?

**Comment by spectrus** [comment]
1. Installed globally with "Install PHAR globally" instructions on [codeception.com/quickstart](http://codeception.com/quickstart)
2. Mac OS X 10.11.5

Yes, I see the 'bin' param in `composer.json`, not sure why it's not kicking in. I ran `composer require --dev lucatume/wp-browser` in a plugin root folder (`/wp-content/my-plugin`). Is there a special way to bootstrap Codeception (before configuring it as per your instructions)?

**Comment by lucatume** [comment]
The `wpcept` command is installed in the `vendor` folder and you can run it using:

```bash
./vendor/bin/wpcept
```

I've added the `vendor/bin` path to the `$PATH` to be able simply write `wpcept`

**Comment by spectrus** [comment]
But of course!.. I somehow assumed it was going to happen magically. The following line in `.bash_profile` enables me to run the command from inside any directory containing the `composer.json` that includes this project:

> export PATH="./vendor/bin:$PATH"

Thank you very much! Closing this.
