### ISSUE TITLE
Add a logOut() method to WPBrowserMethods

### ISSUE THREAD

**Issue by gabe-connolly** [lucatume/wp-browser#462]
It would be helpful to have an easy to use method of logging out a user during testing.  There is a default loginAsAdmin() method and also the ability to login as a specific user, but no ability to logout without configuring a more involved set of test steps that relies on the specific theme UI for a site (i.e. does the theme have an easy to access login/logout link).

**Comment by lucatume** [comment]
@gabe-connolly Thanks for reporting the issue and providing a PR, released in `2.6.14`.
