### ISSUE TITLE
[FEATURE REQUEST] Compatibility with Composer 2

### ISSUE THREAD

**Issue by gbiorczyk** [lucatume/wp-browser#468]
Hi,

Hello everyone. Thanks for your work, I appreciate it very much.

I would like to adapt my composer.json to Composer 2. For testing purposes I have created a very simple composer.json file:
```
{
  "name": "gbiorczyk/my-package",
  "require-dev": {
    "composer/composer": "^2.0"
  }
}
```

And then I execute the following command:
```
composer require lucatume/wp-browser
```

And I have such errors:
```
Using version ^2.6 for lucatume/wp-browser
./composer.json has been updated
Running composer update lucatume/wp-browser
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - lucatume/wp-browser[2.6.0, ..., 2.6.9] require symfony/filesystem ^3.0 -> found symfony/filesystem[v3.0.0, ..., v3.4.46] but the package is fixed to v5.1.8 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - lucatume/wp-browser[2.6.10, ..., 2.6.16] require symfony/process >=2.7 <5.0 -> found symfony/process[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.46, v4.0.0, ..., v4.4.16] but the package is fixed to v5.1.8 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires lucatume/wp-browser ^2.6 -> satisfiable by lucatume/wp-browser[2.6.0, ..., 2.6.16].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Do you plan on compatibility with Composer 2? If so, when can this be expected? I will be very grateful for your answer!

With best wishes,
Mateusz Gbiorczyk

**Comment by lucatume** [comment]
Hi @gbiorczyk,

thanks for the compliments, much appreciated. 

I've not yet tried out, due to lack of time, the use of Composer `2.0` and I've consistently rolled back to version `1.0` where I'm using it as there are a number of packages that have not been updated to it yet.

I'm not committing to any dates, but I will work on this when I have time to spare.

**Comment by lucatume** [comment]
I've started working on this, I've found some issue around `wp-browser` dependency on the `wp-cli/wp-cli-bundle`, `symfony/filesystem` and `symfony/process` packages.
I'm currently exploring the possibility of reducing, ideally removing, the dependency on those packages completely.
I will update this issue with news.

**Comment by alexkuc** [comment]
This might be helpful to others. In case you have composer v2 installed globally, you can override it by using project-specific setting:

```json
    "require-dev": {
        "lucatume/wp-browser": "^2.6",
        "composer/composer": "^1.0"
    },
```

**Comment by lucatume** [comment]
@alexkuc thanks for sharing the tip.

I'm currently working on the update and that will become version `3` of wp-browser.

Will update this ticket when that is out.

**Comment by lucatume** [comment]
And this is done.
