### ISSUE TITLE
[DOC BUG] WPDB->dontSeeOptionInDatabase()

### ISSUE THREAD

**Issue by alexkuc** [lucatume/wp-browser#477]
**wp-browser version**
`^3.0`

**Link**
https://wpbrowser.wptestkit.dev/modules/wpdb#dontseeoptionindatabase

**Issue**
Docs give the following example:

```php
$I->dontSeeOptionInDatabase('posts_per_page');
```

When I run that,  I get error

```
[TypeError] Argument 1 passed to Codeception\Module\WPDb::dontSeeOptionInDatabase() must be of the type array, string given
```

When I look at the function

https://github.com/lucatume/wp-browser/blob/336ed61f0ea3000c300f521f19a13c7c9f7f2c3e/src/Codeception/Module/WPDb.php#L303-L310

I can see that this function accepts array with a possible array key `option_value`

So now this code works

```php
$I->dontSeeOptionInDatabase([
  'option_value' => 'posts_per_page',
]);
```

Through trial 'n' error I found that this also works

```php
$I->dontSeeOptionInDatabase([
  'option_name' => 'posts_per_page',
]);
```

**Comment by lucatume** [comment]
@alexkuc thanks for reporting the issue/inconsistency. 

I think the way to go would be to format the parameters the same way the [seeOptionInDatabase](https://wpbrowser.wptestkit.dev/modules/wpdb#seeoptionindatabase) method does, with name and value or just name.

For back-compatibility purposes, I will try to keep the current behavior based on an array of criteria.

**Comment by alexkuc** [comment]
@lucatume 

I think a simple PR to update the docs would be sufficient for the time being. I think can I find some time to do that. What do you think?

**Comment by lucatume** [comment]
@alexkuc I'm fixing the issue and normalizing both ways of using the methods to support name and value tuples and an array of criteria. That seems a bit more consistent and would keep back-compatibility.

Thanks for the offer, though (sorry for the late reply, I was out).
