### ISSUE TITLE
Different databases for different modules

### ISSUE THREAD

**Issue by alexkuc** [lucatume/wp-browser#479]
When using `WPBrowser` and `WPDb`, unless you use the same database for Wordpress installation and Codeception suite, you can run into funny issues such as:

- `wpdb` scaffolds entries
- trying to access the same entries via `WPBrowser` leads to issues where entries are not there

So as per my understanding, `WPBrowser` is essentially a `PHPBrowser` adapted specifically for Wordpress usage. As such, `WPBrowser` will use settings from `wp-config.php` (this is indirectly inferred as `WPBrowser` access Wordpress via `url` parameter). `WPDb` access database directly via `dsn`, `user`, `password` parameters.

As such I have a question:

- why allow separate databases? is there any concrete example to demonstrate a use case where you need to have separate databases for these modules? (my aim here is to understand why and how I can use it)

**Comment by alexkuc** [comment]
Extra info:

Up to this point, I was using a single Wordpress installation both, to develop code and run test suites. But then I had to create data fixtures using `WPDb` and had to point both modules to the same database. To avoid losing any temporary development data, I set up a new separate Wordpress instance purely for running tests. So now I have `website.local` which I use for debugging and development and `website.test` which I use exclusively for Codeception/WPBrowser. So I was wondering if there was any easy way to avoid having two Wordpress installations.

Why I prefer coded data fixtures as opposed to MySQL dump:

- ease of maintenance (coded fixtures are much easier to update/modify than MySQL dump)
- documentation (coded fixtures tell "the story" for themselves as opposed to MySQL dump)
- git friendliness (commit history is more readable for coded fixtures as opposed to MySQL dump)

**Comment by lucatume** [comment]
@alexkuc,

The reason why you *can* point `WPDb` to a different database from the one used by the WP installation that is serving the `WPBrowser` module requests is twofold:

1. You are running more complex tests and need the flexibility.
2. It's not easy to consistently pick up the correct DB coordinates from the WordPress installation.

Between the `WPDb` and `WPBrowser` modules, only one (`WPDb`) is actually using a database directly. The `WPBrowser` module, as you correctly state, is just an extension of the `PhpBrowser` one and it's not using the database: it's using the WordPress installation to make requests to it.

`WPDb` supports 1+ databases, not just one. I've set up, using [environments](https://codeception.com/docs/07-AdvancedUsage#Environments) and some localhost port juggling, test suites where  I am comparing results of the same cal made to different versions of the served sites, each with its own database.

If you think, then, that it's not easy and solid to try and read the database configuration from the site `wp-config.php` when the setup is not the `wp-config.php` default one, then you understand why the `WPDb` module will require the db coordinates.

**Comment by lucatume** [comment]
> So I was wondering if there was any easy way to avoid having two Wordpress installations.
Did you try this? https://wpbrowser.wptestkit.dev/tutorials/automatically-change-db-in-tests

I, myself, prefer using code fixtures over db ones. Try to add use [WPLoader in loadOnly mode](https://wpbrowser.wptestkit.dev/modules/wploader#wploader-to-only-bootstrap-wordpress): if you have good APIs supporting your code and good models, that will get you far.

E.g. I'd rather write this:

```php
public function test_product_default_price_is_free(AcceptanceTester $I){
    $product = Products::create('test_product','shirts');

    $I->amOnPage('/products/' . $product->ID);
    $I->seeElement('.product__price', ['value' => 0]);
}
```

Than have to set up a db fixture that contains that product already. It depends on what control you have on the code. If you can put a nice CRUD API in place and use it in your tests, all the better.

Hope this helps.

**Comment by alexkuc** [comment]
Thank you very much @lucatume for pointing me to that link. It helped me a lot! I have put together a more flexible code so I will post it below it case it helps someone else:

```php
# load default database
if (!isset($_SERVER['HTTP_TEST_SITE_RUNNING'])) {
  define('DB_NAME', 'dropbox.local');
}

# load special database when running WPBrowser (Codeception)
if (isset($_SERVER['HTTP_TEST_SITE_RUNNING'])) {
  $dsn = explode(';', $_SERVER['HTTP_TEST_SITE_DSN']);
  foreach ($dsn as $value) {
    if (stripos($value, 'dbname') !== false) {
      $dbname = explode('=', $value)[1];
      define('DB_NAME', $dbname);
      break;
    }
  }
}
```

So instead of hardcoding the value in `wp-options.php`, the value is passed by `WPBrowser` (header `TEST_SITE_DSN`) from which `dbname` is extracted.

Since the issue is resolved, I will mark it as closed.

**Comment by lucatume** [comment]
@alexkuc thanks for getting back to the issue and posting your solution, much appreciated.

Happy coding!
