### ISSUE TITLE
wpcli has no sub-modules

### ISSUE THREAD

**Issue by alexkuc** [lucatume/wp-browser#485]
**Environment**
OS: Mac
PHP version: 7.4
Installed Codeception version: 4.1.15
Installed wp-browser version: 3.0.5.1
WordPress version: 5.4
Local development environment: MAMP Pro
WordPress structure and management: default

I am using wp-cli but it has no sub-modules for some reason.

Repository: https://github.com/alexkuc/wpbrowser-issue-485

Here is the output:

```bash
Codeception PHP Testing Framework v4.1.15
Powered by PHPUnit 9.5.1 by Sebastian Bergmann and contributors.

[1mMysuite Tests (1) [22m----------------------------------------------------------------------------------
Modules: [32m\Helper\Mysuite, WPCLI[39m
----------------------------------------------------------------------------------------------------
[35;1mTestCest:[39;22m Try to test
Signature: [32mTestCest:tryToTest[39m
Test: [32mtests/mysuite/TestCest.php:tryToTest[39m
[33mScenario --[39m
[1m I [22mcli ["help"]
[36m  [WPCLI command] ["help"][39m
[36m  [WPCLI command with configuration options] ["help"][39m
[36m  [WPCLI command with environment] [][39m
[36m  [WPCLI output] NAME
  
    wp
  
  DESCRIPTION
  
    Manage WordPress through the command-line.
  
  SYNOPSIS
  
    wp <command>
  
  SUBCOMMANDS
  
    cli               Reviews current WP-CLI info, checks for updates, or views defined aliases.
    dist-archive      Create a distribution archive based on a project's .distignore file.
    help              Gets help on WP-CLI, or on a specific command.
  
  
  
  GLOBAL PARAMETERS
  
    --path=<path>
        Path to the WordPress files.
  
    --url=<url>
        Pretend request came from given URL. In multisite, this argument is how the target site is
        specified.
  
    --ssh=[<scheme>:][<user>@]<host|container>[:<port>][<path>]
        Perform operation against a remote server over SSH (or a container using scheme of "docker",
        "docker-compose", "vagrant").
  
    --http=<http>
        Perform operation against a remote WordPress installation over HTTP.
  
    --user=<id|login|email>
        Set the WordPress user.
  
    --skip-plugins[=<plugins>]
        Skip loading all plugins, or a comma-separated list of plugins. Note: mu-plugins are still
        loaded.
  
    --skip-themes[=<themes>]
        Skip loading all themes, or a comma-separated list of themes.
  
    --skip-packages
        Skip loading all installed packages.
  
    --require=<path>
        Load PHP file before running the command (may be used more than once).
  
    --[no-]color
        Whether to colorize the output.
  
    --debug[=<group>]
        Show all PHP errors and add verbosity to WP-CLI output. Built-in groups include: bootstrap,
        commandfactory, and help.
  
    --prompt[=<assoc>]
        Prompt the user to enter values for all command arguments, or a subset specified as
        comma-separated values.
  
    --quiet
        Suppress informational messages.
  
    Run 'wp help <command>' to get more information on a specific command.[39m
[36m  [WPCLI  status] 0[39m
[32;1m PASSED [39;22m

----------------------------------------------------------------------------------------------------


Time: 00:00.835, Memory: 8.00 MB

[30;42mOK (1 test, 0 assertions)[0m

```

What am I doing wrong? Why wp-cli has no sub-modules like plugin or theme?

**Comment by alexkuc** [comment]
When I try to run sub-modules like plugin or theme, here is the output I get:

```bash

  [ModuleException] WPCLI: wp-cli terminated with status [1] and output [Error: 'plugin' is not a registered wp command. See 'wp help' for available commands.]

```

**Comment by alexkuc** [comment]
Derp, so I found the solution: https://github.com/wp-cli/wp-cli/issues/4900#issuecomment-411637413

I would recommend updating [docs for wp-cli plugin](https://wpbrowser.wptestkit.dev/modules/wpcli) as they do not mention that I need to explicitly require wp-cli as a dependency.

In particular, this wording is confusing:

```
The module will use its own version of wp-cli, not the one installed in the machine running the tests to grant isolation from local settings.
```

The way I understood it is that wp-cli dependency is not required as `The module will use its own version of wp-cli`

If you agree, I could make a PR for this.

**Comment by lucatume** [comment]
Hi @alexkuc,

your project should not require wp-cli as a dependency, but its modules. 

In the project [composer.json file](https://github.com/lucatume/wp-browser/blob/master/composer.json#L30) I'm requiring the `wp-cli/wp-cli` package, but I'm not requiring the `wp-cli/wp-cli-bundle` package.
The `wp-cli/wp-cli-bundle` package will include *all* wp-cli modules and that could not be what one needs, a refinement over requiring the `wp-cli/wp-cli-bundle` package might requiring only specific commands (e.g. the `wp-cli/shell-command` one if that is the only one that is required.

I agree the wording and clarity of the documentation could be updated to reflect that and will do that, thanks for pointing it out. 

I will let you know when that is done here in this issue to get some feedback about it.

**Comment by lucatume** [comment]
@alexkuc,

the [documentation update](https://wpbrowser.wptestkit.dev/modules/wpcli#fixing-not-a-registered-command-issue) should take care of this, let me know if that reads clear enough to you.

**Comment by alexkuc** [comment]
@lucatume 

This is perfect, thank you!
