### ISSUE TITLE
[DOC BUG]

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [lucatume/wp-browser#491]
**wp-browser version**
For what version of wp-browser is this for? [e.g. 2.2.2]

**Link**
https://wpbrowser.wptestkit.dev/modules/wploader#usage-in-integration-or-wordpress-unit-tests

**Issue**
In this "public funcion test_posts($post_id)" line of code the 'funcion' should be 'function'.

**Comment by lucatume** [comment]
@ChiragGupta-CEDCOSS thanks for reporting this, I will proceed to the fix asap.
