### ISSUE TITLE
[FEATURE REQUEST] Fake data

### ISSUE THREAD

**Issue by edpittol** [lucatume/wp-browser#496]
**Is your feature request related to a problem? Please describe.**
I'm needing to create code to generate testing data. It is clearer to understand the dataset that is being tested.

**Describe the solution you'd like**
Create a connector between wp-browser and Codeception that make it working as an ORM module too.

https://codeception.com/docs/09-Data.html#ORM-modules

**Describe alternatives you've considered**
The idea to open this issue is discuss possibilities to integrate wp-browser add the possibility of generate a dataset similar as done with Laravel, Yii2 and Doctrine.

**Comment by lucatume** [comment]
@edpittol thanks for proposing the change. 

I've got questions, though, as you did not mention it in your description:

1. Did you try to use [WPDd direct-access db methods](https://wpbrowser.wptestkit.dev/modules/wpdb#havemanypostsindatabase) to generate the test fixtures? If so, what issues or limit are you running into? This is an option for functional and acceptance level of testing.
2. If you have this problem, again in functional and acceptance testing, did you try to use [WPLoader in `loadOnly: true` mode](https://wpbrowser.wptestkit.dev/modules/wploader#wploader-to-only-bootstrap-wordpress) and use [the `$I->factory()` method that comes with it](https://wpbrowser.wptestkit.dev/modules/wploader#factory)? What issues or limits are you running into?
3. In integration testing context, did you try to use the `static::factory()` method that comes with the `WPTestCase`? What issues or limits are you running into?

To further the discussion, could you provide an example of the test code you're trying to write?

**Comment by edpittol** [comment]
@lucatume Excelent questions. They made me reflect about the possibilities.

I use the wpdb direct access functions to generate data. But I didn't know about the `$I->factory()` it can be a solution combined with the loadOnly.

I will test this way. Thanks for the pertinents questions.

**Comment by lucatume** [comment]
@edpittol you're welcome.

If you have the time, I would like to know if, and how, you solved the problem.
No pressure, just out of curiosity.
