### ISSUE TITLE
[DOC BUG] WPLoader with loadOnly true also executes in transaction

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-browser#508]
**wp-browser version**
3.0.6

**Link**
https://wpbrowser.wptestkit.dev/modules/wploader#everything-happens-in-a-transaction

**Issue**
My understanding is that `WPLoader` with `loadOnly` true will execute the queries without wrapping them in a transaction. However, [WPTestCase](https://github.com/lucatume/wp-browser/blob/master/src/Codeception/TestCase/WPTestCase.php) does not take this parameter into account, wrapping all queries in a transaction.

If we want to write unit tests without transactions:

A) Should we use `\Codeception\Test\Unit` directly, instead of `WPTestCase`?
B) Or is this an unexpected behavior, and `WPTestCase` should not start/commit transactions if WPLoader's `loadOnly` is true?

Relevant methods:
- [\Codeception\TestCase\WPTestCase::commit_transaction](https://github.com/lucatume/wp-browser/blob/c8bc37b5837c99ace82b9c353069c2617462eefe/src/Codeception/TestCase/WPTestCase.php#L105)
- [\Codeception\TestCase\WPTestCase::start_transaction](https://github.com/lucatume/wp-browser/blob/c8bc37b5837c99ace82b9c353069c2617462eefe/src/Codeception/TestCase/WPTestCase.php#L394)

**Comment by lucatume** [comment]
The transaction wrapping comes from the `WPTestCase` class, if you use that as base test case, then it will use transactions.

To answer your question:

> Should we use \Codeception\Test\Unit directly, instead of WPTestCase?

Yes, or any other test case that is not using the `WPTestCase` class. The `loadOnly` parameter was added to load WordPress code in the context of Cest and Cept tests, where the `WPTestCase` will never be the parent test case.

> Or is this an unexpected behavior, and WPTestCase should not start/commit transactions if WPLoader's loadOnly is true?

It is not an unexpected behavior: the test case is made to work like that.
