### ISSUE TITLE
[BUG|Question] wp_set_auth_cookie pluggable is meaningless for test assertions.

### ISSUE THREAD

**Issue by calvinalkan** [lucatume/wp-browser#509]
Hi @lucatume ,

WP-browser overrides some pluggable functions like for example: 
`wp_set_auth_cookie()`. 

Inside `vendor/lucatume/wp-browser/src/includes/functions.php` this function is overwritten to the following:

```php
function wp_set_auth_cookie($user_id, $remember = false, $secure = '', $token = '')
    {
        $auth_cookie = null;
        $expire = null;
        $expiration = null;
        $user_id = null;
        $scheme = null;
        /** This action is documented in wp-inclues/pluggable.php */
        do_action('set_auth_cookie', $auth_cookie, $expire, $expiration, $user_id, $scheme);
        $logged_in_cookie = null;
        /** This action is documented in wp-inclues/pluggable.php */
        do_action('set_logged_in_cookie', $logged_in_cookie, $expire, $expiration, $user_id, 'logged_in');
    }

```

I completly understand why this is done to avoid the `setcookie`call in the original function, but why are even filter parameters set to `null` ?

I pulled my hair out the last hour trying to figure out why my calls to wp_set_auth_cookie() never returned the correct user id. What is the reason that we are not passing the original parameters here into the hook?

**Comment by lucatume** [comment]
@calvinalkan thanks for taking the time to open the issue and document it.

Your observation has merit: while there's a reason to avoid the `setcookie` call, there is not much reason into **not** passing the parameters to the action and filter that I can think of, or remember.
Neither WordPress Core, nor wp-browser will make use of those during their work, so it seems more of a heavy-handed approach than a deliberate one.

I will spin up a branch with this and test it out and update this one

**Comment by lucatume** [comment]
I've opened a branch that should address this and will see where it goes from there.

Thanks @calvinalkan for the report.
