### ISSUE TITLE
Can't install codeception/module-asserts because of ext-zip errors[SETUP ISSUE]

### ISSUE THREAD

**Issue by jerclarke** [lucatume/wp-browser#510]
**Environment**
OS: macOS Catalina 10.15.7
PHP version: 7.0.33 (through MAMP) (and ohters)
Installed Codeception version: 4.1.21
Installed wp-browser version: 3.0.7
WordPress version: 5.7
Local development environment: MAMP Pro
WordPress structure and management: default

**Did you use the `codecept init wpbrowser` command?**

Yes, I was following the ["Initializing WP Browser guide"](https://wpbrowser.wptestkit.dev/getting-started/configuration) when I got trapped trying to resolve dependency issues.

**Did you take a look at Codeception and wp-browser documentation?**

Yes I was reading it from back to front when I got stuck during `codecept init wpbrowser`

**Codeception configuration file**

I don't think I got this, because `codecept init wpbrowser` never finished.

**Suite configuration file**

Didn't get to the point of any actual testing. 

**Describe the issue you're encountering**

* I ran `codecept init wpbrowser`
* I filled out all the answers, and it seemed satisfied
* It started setting things up, creating test directories and config files
* I got some errors and started looking into them. 
* At the heart of the errors was that `codeception/module-asserts` wasn't installed
* It told me to install that. Doing so led to the output below, which to my unexpert eyes tells me that the `facebook/webdriver` package can't install because `ext-zip` is missing and I need to install "PHP's zip extension":

**Output**

```
jer@jmbp sample-plugin %  composer require codeception/module-asserts --dev
Using version ^1.3 for codeception/module-asserts
./composer.json has been updated
Running composer update codeception/module-asserts
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - codeception/module-webdriver[1.2.0, ..., 1.2.1] require php-webdriver/webdriver ^1.8.0 -> satisfiable by php-webdriver/webdriver[1.8.0, ..., 1.11.1].
    - codeception/module-webdriver[1.0.1, ..., 1.1.4] require php-webdriver/webdriver ^1.6.0 -> satisfiable by php-webdriver/webdriver[1.6.0, ..., 1.11.1].
    - codeception/module-webdriver 1.0.0 requires facebook/webdriver ^1.6.0 -> satisfiable by php-webdriver/webdriver[1.8.3, ..., 1.11.1], facebook/webdriver[1.6.0, 1.7.0, 1.7.1].
    - facebook/webdriver[1.6.0, ..., 1.7.1] require ext-zip * -> it is missing from your system. Install or enable PHP's zip extension.
    - php-webdriver/webdriver[1.6.0, ..., 1.11.1] require ext-zip * -> it is missing from your system. Install or enable PHP's zip extension.
    - Root composer.json requires codeception/module-webdriver ^1.0 -> satisfiable by codeception/module-webdriver[1.0.0, ..., 1.2.1].
```
**What I've tried in order to fix this**

* This led me down a rabbit hole trying to satisfy the demand for a zip extension 
* I managed to jump through many hoops to add it to MAMP with `pecl install zip`
* I then discovered that it was already there, or I think it was. I was getting errors in `php --version` that it had been enabled twice in the configuration. 
* Either way, `phpinfo()` clearly shows the zip extension as installed on my 7.0.33 copy from MAMP Pro, but I still get the same errors when running `composer require codeception/module-asserts --dev`
* I'm pretty sure that the 7.0.33 PHP from MAMP is what's on the command line, because `php --version` shows 7.0.33.
* I tried switching to PHP 7.3 in MAMP but this didn't work either. Same output as above when trying to install in composer, and same output in `phpinfo()` that the zip extension is already working
* I also tried installing PHP7.3 using brew, then installing the zip extension with `pecl install zip` but it said it was already installed. I don't know if I really managed to test this with that brew 7.3, I'm a bit in over my head trying to fix this. 

Sorry for all the details. I'm still in "it's my fault" mode but can't think how to fix it. `phpinfo()` says I have it, but composer says I don't. 

**To Reproduce**

I feel like "try to install WP Browser on Catalina with MAMP Pro" is my best attempt, but of course it could easily be something custom about my setup. 

**Screenshots**

Here's what happens when I try to install `codeception/module-asserts` with the PHP 7.3.9 version from MAMP Pro:

<img width="1443" alt="Screen Shot 2021-07-02 at 6 28 43 PM" src="https://user-images.githubusercontent.com/139995/124336369-6654a280-db63-11eb-8232-63c024aea1d1.png">

Here's the `phpinfo()` output for that PHP, which seems to show how libzip is loaded and considered enabled:

<img width="780" alt="Screen Shot 2021-07-02 at 6 29 51 PM" src="https://user-images.githubusercontent.com/139995/124336415-99973180-db63-11eb-8930-4d6e00b0ee53.png">
<img width="811" alt="Screen Shot 2021-07-02 at 6 30 09 PM" src="https://user-images.githubusercontent.com/139995/124336419-9bf98b80-db63-11eb-93b6-735a927f6fd5.png">

**Details about where in the WP Browser init sequence it failed**

I hope it's ok to post this here. I guess it could be a codeception bug, but I got stuck in the middle of your command, so I figured you might be the best one to help me, and also interested in how MAMP+WP-Browser users might be impacted. 

I actually got stuck and unable to re-run `codecept init wpbrowser` because of this, so maybe that is something you want to address. 

It did manage to create a `.env.testing` file based on my answers to the wizard, which blocks me from running the command again without deleting it. 

I deleted it and ran it again, so you can see where it dies:

<img width="732" alt="Screen Shot 2021-07-02 at 6 39 14 PM" src="https://user-images.githubusercontent.com/139995/124336797-15de4480-db65-11eb-9c6f-98aaaaf6cbe2.png">

That's pretty much exactly what I saw originally, and which led me to trying to solve it as described above. 

It really seems like this is just dependency hell rearing its ugly head, but I am very eager to fix it however I can.

Thanks for reading and for your work on this project! It really seems perfect for me (and anyone)!

**Comment by jerclarke** [comment]
Ok, taking a second swing at this, I started a fresh directory and tried only installing the `facebook/webdriver` package, to isolate the problem:

<img width="1116" alt="Screen Shot 2021-07-03 at 5 07 00 PM" src="https://user-images.githubusercontent.com/139995/124367937-8fd40380-dc21-11eb-8ce8-022c0257396d.png">

Some more [digging around ](https://github.com/composer/composer/issues/9377#issuecomment-719019204) led me to the `--ignore-platform-req` flag in composer, which I probably wouldn't want to use long term, but figured I'd try it to see what happens:

<img width="860" alt="Screen Shot 2021-07-03 at 5 07 40 PM" src="https://user-images.githubusercontent.com/139995/124367977-f3f6c780-dc21-11eb-9349-8d5f9ff2235c.png">

As is visible in the screenshot, I was then able to run `composer check-platform-reqs` and see what it had to say about `ext-zip` (I had run this before, but it didn't have any info because of course the facebook package wasn't actually installed yet). 

So in the `composer check-platform-reqs` output, we can see that the `ext-zip` is still considered missing. **But** at least it gives me a lead, as it's talking about PHP `7.3.11`, which is not the same as the currently active CLI version, which is `7.3.9`. 

So I suspect the problem is that I still haven't addressed the version of PHP that composer is finding on the CLI, and there must be some copy on my system that still doesn't have `ext-zip`.

**Comment by jerclarke** [comment]
Ok! Fixed it! The problem was that composer was using the "built in" macOS PHP version (`7.3.11`, which didn't have the zip extension installed) even though running `php -v` was returning `7.3.9` (the MAMP version, which **did** have the zip extension installed). 

So I guess the thing I need to keep in mind is that the two things can be separate, and that the MAMP versions, despite seeming to work, get ignored by Composer for one reason or another. 

In the end [this SO answer about fully installing `brew` PHP](https://stackoverflow.com/a/58300437/209859) solved it for me:

```brew update
brew install php@7.3
brew link php@7.3```

Then copy the `PATH` strings it recommends into my `.zshrc`. 

That default `brew` install has everything I need, so it seems like I'll be able to continue with installation now. 

Hope this post isn't annoying! Close as soon as you're sure there's nothing you want to address in it. 

The fact that the WP Browser installer just dies half way through, leaving the files in a mixed up state, is kind of bad. If it could check the dependencies first, and exit in a graceful way, that would be nicer. 

The other thing is this seemingly-unrelated message I now see about `facebook/webdriver` now that it's installed:

<img width="875" alt="Screen Shot 2021-07-03 at 5 38 04 PM" src="https://user-images.githubusercontent.com/139995/124368292-71700700-dc25-11eb-9e8a-079ea0eeb6af.png">

`Package facebook/webdriver is abandoned, you should avoid using it. Use php-webdriver/webdriver instead.`

It shows up every time I do `composer install` or similar.

Thanks for all your work on this!

**Comment by simonhammes** [comment]
> The other thing is this seemingly-unrelated message I now see about `facebook/webdriver` now that it's installed:
> 
> <img alt="Screen Shot 2021-07-03 at 5 38 04 PM" width="875" src="https://user-images.githubusercontent.com/139995/124368292-71700700-dc25-11eb-9e8a-079ea0eeb6af.png">
> 
> `Package facebook/webdriver is abandoned, you should avoid using it. Use php-webdriver/webdriver instead.`
> 
> It shows up every time I do `composer install` or similar.

By running `composer require facebook/webdriver --dev`, you explicitly told Composer to install this package.
If you remove it and run `composer update` afterwards, it should install the latest version of https://packagist.org/packages/php-webdriver/webdriver (the vendor namespace changed from `facebook` to `php-webdriver`).

**Comment by lucatume** [comment]
@jerclarke thanks for the updates, including the resolution. Others might have the same issue, so your feedback is appreciated and not out-of-place at all.

wp-browser, building on top of Codeception and, thus, on top of PHPUnit and a number of Symfony components, does come with baggage in terms of dependencies; there is little I can do to fix it.

wp-browser will clean after itself on a failed installation and the solution to the two-step process on Codeception version 4, the one where you need to install a second set of Composer dependencies to get assertions and all that, is required to keep the package compatible with older versions of Codeception (that are out there!). The issue is: an installation missing requirements is not really a failed installation, but just an incomplete one. I will, eventually come around and remove the compatibility with Codeception before version 4 from the next versions, but not now.

Thanks for the contributions and updates to both, happy testing!
