### ISSUE TITLE
Configuration.md various mismatches with current init experience [DOC BUG]

### ISSUE THREAD

**Issue by jerclarke** [lucatume/wp-browser#512]
**wp-browser version**
3.0.8 + website documentation

**Link**
https://github.com/lucatume/wp-browser/blob/master/docs/configuration.md

**Issue**

A few things were off. I was able to work around them, but in case you didn't know, figured I'd make a list.

I do so because the docs are amazing otherwise, and I can tell a lot of love was put into them, so I figure small improvements are still desired.

### Initial naming questions from docs don't happen in CLI

The main screenshots of the `codecept init wpbrowser` command didn't match what I saw in terminal, though I'm not sure if it's a bug in the docs or in the CLI, since the CLI worked well otherwise, I figured I'd treat this as a docs suggestion for now. 

Basically all these questions, which are both in the screenshots and in the FAQ, weren't asked of me:

```
How would you like the acceptance suite to be called?  
How would you like the functional suite to be called?  
How would you like the WordPress unit and integration suite to be called?  
How would you like to call the env configuration file?  
```

Instead sensible defaults were used, which was fine with me! 

Was this behavior changed in a previous version to just use defaults, or is there something wrong with the CLI behavior I'm getting. 

Either way it's no big deal to me, but would be good to have the two match to avoid confusion.

Note that the [If you entered a wrong value](https://wpbrowser.wptestkit.dev/getting-started/configuration#if-you-entered-a-wrong-value) question also has a link to "How would you like to call the env configuration file?", so that should be updated too if the env question is changed.

**CLI output I get (tried several runs):**

<img width="947" alt="Screen Shot 2021-07-05 at 4 26 33 PM" src="https://user-images.githubusercontent.com/139995/124519137-11589c80-ddae-11eb-99f6-898cc45e7994.png">

**Directories/files that are created (to show the default values I'm getting)**

<img width="208" alt="Screen Shot 2021-07-05 at 4 29 24 PM" src="https://user-images.githubusercontent.com/139995/124519195-35b47900-ddae-11eb-93cb-6bbe8a281227.png">

### Pre-Flight Check: Default `integration` suite is now `wpunit`

In the Pre-flight check section you give the commands to check each of the suites, including `codecept run integration`, but that gave me an error because I had a `wpunit` suite instead. 

That feels like a (very reasonable) change to the default suites that just hasn't been updated in the docs. 

### `codecept` command didn't work for me, suggest a fix in docs?

I'm not sure if the `init` command is supposed to do something to make `codecept` work out of the box, but for me I just got:

`zsh: command not found: codecept`

I searched around and found you telling people to add `/vendor/bin/` to their CLI config, and ended up fixing it with the following in my `~/.zshrc`:

`PATH="./vendor/bin:$PATH"`

Since this "Pre-flight Check" section is the first time people are invoking `codecept` it might be a good place to offer a suggestion in case it's not working. [This SO answer](https://stackoverflow.com/questions/26753674/phpunit-how-to-add-vendor-bin-into-path) solved it for me.

Thanks for considering this and for all your work! Sorry I'm a noisy newcomer. I love your new user experience! I wish the core WP PHPUnit docs were 1/10 as good as yours!

**Comment by lucatume** [comment]
@jerclarke thanks for opening an issue and providing such a wealth of information, attention, and accuracy. Much appreciated.

I made some changes to the initial setup over time, and have forgotten to update the documentation where required.

I will push an update to the documentation whenever I'm able to. Since you provided a screenshot of all the questions, I could use that to update the configuration section screenshots.

I will update on this post.
