### ISSUE TITLE
[QUESTION] wpdb error reporting

### ISSUE THREAD

**Issue by calvinalkan** [lucatume/wp-browser#514]
Hi @lucatume ,

This is not a Bug but rather a question about how wp-browser connects to the database.

Basically: 
Does wp-browser modify the mysqli error reporting in any way. I dug around but couldnt really find anything.

Use case:

Im testing that its not possible to insert a negative integer to a DB table with an unsigned integer column generated by a library of me.

In my bootstrap file I set mysqli_report to Report everything and to throw exceptions. But no matter what , it doesnt take effect.

When I insert a negative int using wpdb mysqli always converts it to zero which it only does if error reporting is turned off.

Any ideas?

**Comment by calvinalkan** [comment]
Yes its extending `WpTestCase`. I dont think thats related but I found out that by extending `WpTestCase`  ```php $wpdb->db_connect``` will be called twice during a test run. Once inside the bootstrap file and once inside the TestCase set up 

```php
public static function _setUpBeforeClass()
    {
        static::setupForSeparateProcessBeforeClass();

        global $wpdb;

        $wpdb->suppress_errors = false;
        $wpdb->show_errors = true;
        $wpdb->db_connect();
        ini_set('display_errors', 1);

        $c = self::get_called_class();
        if (!method_exists($c, 'wpSetUpBeforeClass')) {
            self::commit_transaction();
            return;
        }

        call_user_func(array($c, 'wpSetUpBeforeClass'), self::factory());

        self::commit_transaction();
    }

```

My test code is the following. ( These are separate files/classes but merged for brevity) 

```php 
// This happens in a bootstrap file to make sure its called before the dbh in wpdb connects with the database.
ini_set('display_errors',1);
error_reporting(E_ALL);
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
```

```php

// The code under test. This works 100% correct and will create a table 
//wp_books where price is an unsiged integer.
// The test should verify that no negative integer can be inserted for the price column.

$builder = $this->newTestBuilder('books');
$builder->create('books', function (Blueprint $table) {

                $table->id();
                $table->integer('price')->unsigned();

 });

 try {

       global $wpdb;

      $wpdb->query("INSERT INTO `wp_books` (`id`, `price`) VALUES (2, -100)");
      $this->fail('[TEST FAILED] Negative value inserted for unsigned integer.');

 }
catch (\Throwable $e) {

     $this->assertSame(
        "SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'price' at row 1",
          $e->getMessage()
      );

 }

```

Expected:
A `mysqli_exception` should be thrown. 
The table is setup correct but the test is a false negative. mysqli will clamp the value to 0 and insert the record ( msqli only does this if error_reporting is not turned on).

The following will fail properly, (running the query directly in sequel will also fail)

```php
// This will throw a PDO expection.
 $this->tester->haveInDatabase('wp_books', ['id' => 1, 'price' => -100]);
```

This will also fail. 

```
    $mysqli = new mysqli(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);

   $mysqli->query("INSERT INTO `wp_books` (`id`, `price`) VALUES (2, -100)");
```

The the reason has to be set either something is causing the error_reporting to not be applied or its because wpdb is still stuck in 2013 and using mysqli_real_connect instead of the OOP approach.

**Comment by calvinalkan** [comment]
Confirming that the following also will throw a mysqli_exception as expected:
This is how WordPress does it in wpdb
```php
 ini_set('display_errors', 1);
error_reporting(E_ALL);
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);

$mysqli = mysqli_init();
mysqli_real_connect( $mysqli, DB_HOST, DB_USER, DB_PASSWORD, DB_NAME, null, null , 0 );
$mysqli->query("SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_520_ci'");
$mysqli->query("INSERT INTO `wp_books` (`id`, `price`) VALUES (2, -100)");

```

**Comment by calvinalkan** [comment]
This will also fail ( NOTE: all of this code I posted was run inside WPTestCase )

```php
ini_set('display_errors', 1);
error_reporting(E_ALL);
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);

$mysqli = mysqli_init();
mysqli_real_connect( $mysqli, DB_HOST, DB_USER, DB_PASSWORD, DB_NAME, null, null , 0 );
$mysqli->query("SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_520_ci'");
          
global $wpdb;
$wpdb->dbh = $mysqli;
$wpdb->query("INSERT INTO `wp_books` (`id`, `price`) VALUES (2, -100)");

```

**Comment by calvinalkan** [comment]
I found the issue by myself. No matter what you doing this will always by constructing `$wpdb`

```php
/**
	 * A list of incompatible SQL modes.
	 *
	 * @since 3.9.0
	 * @var array
	 */
	protected $incompatible_modes = array(
		'NO_ZERO_DATE',
		'ONLY_FULL_GROUP_BY',
		'STRICT_TRANS_TABLES',
		'STRICT_ALL_TABLES',
		'TRADITIONAL',
		'ANSI',
	);

```

This will result in the sql mode being fetched and all modes in the array will be unset. Gotta love it.


```php

mysqli_query($this-dbh, SET SESSION sql_mode='NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION')
```

**Comment by lucatume** [comment]
Hi @calvinalkan,

thanks for the updates. I'm currently not able to look into this, but want to give reading this the time your research deserves.

**Comment by calvinalkan** [comment]
@lucatume To save you a bit of time. 

WordPress is incompatible with strict mode [(Track Ticket).](https://core.trac.wordpress.org/ticket/8857?fbclid=IwAR0pduQwn6y8cc73-e4ijiMIcIIWtWjZIbfUK6kU3i5OyIY-qDQ6pFLDj0I)

But during test we can use strict mode just fine. Its actually really messed up that any sql errors will be silently ignored by wpdb. 

I have a working proposal that I use in production right now. 

I created simple one method trait that you can pull into any test case. 

```php

trait WithDatabaseExceptions
    {

        protected function withDatabaseExceptions()
        {

            global $wpdb;

            /** @var mysqli $mysqli */
            $mysqli = $wpdb->dbh;

            error_reporting(E_ALL);
            mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
            $mysqli->query("SET SESSION sql_mode='TRADITIONAL'");


        }

    }

```

The amount of bugs that would have gone unnoticed is insane. 

A super simple example would be you trying to insert into a table but dont provide a value for a column that is not nullable. 
The query wont work `wpdb` raise any exceptions at all. 

With the new setup you get a `mysqli_exception` and way better debug info.

**Comment by lucatume** [comment]
@calvinalkan Thanks for sharing the solution.

I think this would be a nice addition to the `WPTestCase` class, maybe off by default (to avoid killing existing tests) and controlled by a configuration parameter of the `WPLoader` suite.

**Comment by calvinalkan** [comment]
I agree that this should somehow be merged. Dont you think it would be better tho on a Test by test basis instead of the suite level?

Do simplest way would just to set a protected property on the test case. However I think the most flexible and future proof way would be to use something like laravel does. You pull in traits which automatically get booted in `WpTestCase`.

What do you think?

**Comment by calvinalkan** [comment]
@lucatume What are your thoughts on this?

**Comment by lucatume** [comment]
I, personally, favor the use of Traits over inheritance in this context, so I agree with the Trait path here.

The trait should implement setup and teardown methods, i.e. the `@before` and `@after` annotations, to make sure to reset the `$wpdb` object to its previous state before and after each test (as the users might compose the trait into something that will need the default `$wpdb` setup in a debug method on-failure or on-error.

Since the `@before` and `@after` annotations support specifying the method to act before or after, the annotations should, probably, target the `setUp` and `teardDown` methods? That would require some thinking.

The reason I would like the trait to define methods and `@before` and `@after` annotations on those methods, is to make the user of the trait just a matter of a `use` statement.
