### ISSUE TITLE
[DOC REQUEST] Describe difference between plugins and activatePlugins for WP_Loader module

### ISSUE THREAD

**Issue by calvinalkan** [lucatume/wp-browser#515]
**Did you search the documentation first?**
Yes

**What do you think is missing from the documentation?**
I dont know what the difference is between the two config options "plugins" and "activatePlugins". Are both required? What do they do?

**Comment by calvinalkan** [comment]
@lucatume Do you have any input on this?

**Comment by lucatume** [comment]
Hi @calvinalkan, I lost the notification completely. 

The difference is:
* `activatePlugins` is a list of plugins the WPLoafer module will load and activate during the installation bootstrap that is done once before the tests, in the installation process that happens in isolation.
* `plugins` is a list of plugins the WPLoader module will load right before the tests, in the same PHP process that will run the tests. 

The reason is that you might want to test on the effect of a loaded plugin (e.g., custom tables created), but without actually loading it in your tests. 

Most of the times the two lists will be identical.

**Comment by calvinalkan** [comment]
Makes sense. I checked the `isolated-install.php` where most of this happens. 

Thank you.

**Comment by calvinalkan** [comment]
Actual, I have some more questions now then before. I run a global search of the entire codebase and it seems that
the only place where `activePlugins` is every used is here: called inside `WPLoader::installAndBootstrapInstallation`

```php
if (! $this->requiresIsolatedInstallation()) {
    tests_add_filter('muplugins_loaded', [$this, '_loadPlugins']);
    tests_add_filter('wp_install', [$this, '_activatePlugins'], 100);
    tests_add_filter(
        'wp_install',
        [$this, '_bootstrapActions'],
        101
    );
    tests_add_filter('plugins_loaded', [$this, '_switchTheme']);
}
```

If `isolatedInstall` is set to true (default) then `activatePlugins` does nothing for me. 

In `isolated-install.php` on line 32 the action plugins are defined like this 

```php 

if (!empty($configuration['activePlugins'])) {
	$activePlugins = $configuration['activePlugins'];
}
else {
	$activePlugins = [];
}

```

But `$configuration['activePlugins'])` is passed into the separate PHP process like this:

```php

if (!empty($GLOBALS['wp_tests_options']['active_plugins'])) {
		$uniqueActivePlugins = array_unique($GLOBALS['wp_tests_options']['active_plugins']);
		$environment['activePlugins'] = $uniqueActivePlugins;
		codecept_debug("Active plugins:\n\t- " . implode("\n\t- ", $uniqueActivePlugins));
	}

```

And the `$GLOBALS['wp_tests_options']['active_plugins']` is initialized like this inside `WpLoader::setActivePlugins.`

```php
  /**
     * Sets the currently active plugins.
     *
     * @return void
     */
    protected function setActivePlugins()
    {
        if (empty($this->config['plugins'])) {
            return;
        }

        if (! empty($GLOBALS['wp_tests_options']['active_plugins'])) {
            $GLOBALS['wp_tests_options']['active_plugins'] = array_merge(
                $GLOBALS['wp_tests_options']['active_plugins'],
                $this->config['plugins']
            );
        } else {
            $GLOBALS['wp_tests_options']['active_plugins'] = $this->config['plugins'];
        }
    }

```
 
So unless Im missing something completely here we can **summarize this as the following:**

**IsolatedInstall**

- `activatePlugins`has no effect at all.
- `plugins` will load all active plugins in both the test suite and in the isolated install process. 

**Same PHP process**

- Every plugin inside `activePlugins` will be included in the test and trigger the activation hook even if its not set inside `plugins`. This is because `activatePlugin()` will include the file anyway.
- The only effect of `plugins` seems be that they are loaded after `muplugins_loaded` but I dont see where that would change anything compared to just including them on activation. 

It seems like it would be a lot clearer to just have one option `plugins` that will include and activate the plugin no matter the value of `isolatedProcess` and then use another optional config value like `skipActivationHook`that will not trigger `activatePlugin()` for excluded values. 

I cant be the only one that finds this kinda confusing and Im sure not everybody has the time or motivation to jump into xDebug to figure out how it really works. 

Let me know what you think. Ill be happy to help if you were to accept changes for this. 

Sorry for the long message lol.

**Comment by lucatume** [comment]
> activatePlugins has no effect at all.

[In the isolated-install.php script](https://github.com/lucatume/wp-browser/blob/master/src/includes/isolated-install.php#L192) the value is used to activate the plugins, i.e. run their `activation_hook` after WordPress has been installed and bootstrap. It _might_ be that is amounting to nothing if the plugins you're activating are not doing anything relevant on activation. Many plugins will run logic on activation. Running that logic after the WordPress installation and **not** in the same PHP process as the tests allows plugins that, say, create custom tables on activation, to do so.

> plugins will load all active plugins in both the test suite and in the isolated install process
Sure, plugins code will need to be loaded during the installation to actually run the activation hook code and will be required for tests to run. Nothing strange here.

In the same PHP process scenario (which used to be the default and then became a legacy option) then the flow is one to create the least amount of damage (plugins **should not** be loaded and then activated and then run in the same PHP process).

> It seems like it would be a lot clearer to just have one option plugins that will include and activate the plugin no matter the value of isolatedProcess and then use another optional config value like skipActivationHookthat will not trigger activatePlugin() for excluded values.

I find this more confusing, personally. While I agree that the difference between `plugins` and `activatePlugins` might be confusing, it also leave the door open to very powerful set ups. Not to mention the order counts and there might be scenarios where the test involves activating A after B or vice versa.
I propose a middle ground where `activatePlugins` will default to the value of `plugins` if not specified: this would not break existing implementations and would not break existing particular set ups that are actually leveraging the difference and the order.

**Comment by calvinalkan** [comment]
Ok since the same-procces install is a legacy option I wont focus on that any further. 

But I still stand to my opinion that when using isolatedInstall = true the option activate_plugins has no effect at all.

Inside isolated-install.php:

```php

if (!empty($configuration['activePlugins'])) {
	$activePlugins = $configuration['activePlugins'];
}
else {
	$activePlugins = [];
}

```

**Comment by lucatume** [comment]
@calvinalkan I will check it, then. Thanks for bringing attention on this. If a simplification is possible, then I'm all for it.
