### ISSUE TITLE
Dependency on `mikemclin/laravel-wp-password` -> `hautelook/phpass` creating problems 

### ISSUE THREAD

**Issue by bordoni** [lucatume/wp-browser#523]
This repo has a dependency on `mikemclin/laravel-wp-password`  which depends on `hautelook/phpass` which seems to have been deleted.
https://github.com/hautelook/phpass

Only exists on Packagist.
https://packagist.org/packages/hautelook/phpass

I've created an issue with the original dependency to solve the problem:
https://github.com/mikemclin/laravel-wp-password/issues/13

I've created a fork of the original to solve the problem we were facing on The Events Calendar.
https://github.com/bordoni/phpass

See the PRs where this was applied:
https://github.com/the-events-calendar/tribe-common/pull/1652
https://github.com/the-events-calendar/the-events-calendar/pull/3639

**Comment by lucatume** [comment]
Thanks @bordoni,

I've used your mirror in my fix (#524) to immediately resolve it.


I will internalize the dependency next.

**Comment by dgwatkins** [comment]
This change forces you to use composer 2.x
https://packagist.org/packages/bordoni/phpass

Just FYI

**Comment by menno-ll** [comment]
Please also note that this change requires a project using wp-browser to define `"minimum-stability": "dev",` in their `composer.json` file.

**Comment by bordoni** [comment]
@dgwatkins the reason it forced version 2 of Composer was due to how Packagist has a 24h delay on the inclusion for V1 composer things. (Go figure)

I've also setup with version 0.3.0, so you should be able to do `"minimum-stability": "stable"`. And avoid `dev-main`
