### ISSUE TITLE
[SETUP ISSUE] config_file doesn't seem to work

### ISSUE THREAD

**Issue by nathanmal** [lucatume/wp-browser#532]
**Environment**
OS: OSX 13.4
PHP version: 7.4
Installed wp-browser version: 3.0
WordPress version: 5.0
Local development environment: homebrewed php/httpd/mariadb

Hi, i'm attempting to set up testing for a plugin that requires several custom constants to be loaded into the configuration file. I found this page describing what i'm doing and how to allow for this when bootstrapping https://theaveragedev.com/use-custom-configuration-files-in-wp-tests/

However, when I edit the /tests/wpunit.suite.yml file to add the config_file parameter, it still doesn't seem to load it as I'm getting PHP warnings that my constants are missing. In this case my 'custom-config.php' file lives next to the wp-config.php file in the root folder. Also there is one place where I'm using the AUTH_SALT constant and this is also missing. 

Am I missing something or are there additional steps required to load custom constants into Wordpress?Also does wp-browser load the salt constants or does it simply create it's own set when installing?

thanks!

```yaml
actor: WpunitTester
modules:
    enabled:
        - WPLoader
        - \Helper\Wpunit
    config:
        WPLoader:
            wpRootFolder: /Users/nathan/path/to/wordpress
            dbName: wordpress_test
            dbHost: localhost
            dbUser: root
            dbPassword: root
            wpDebug: true
            dbCharset: utf8mb4
            dbCollate: ''
            tablePrefix: wp_
            domain: wordpress.localhost
            adminEmail: admin@example.com
            phpBinary: php
            title: "Wordpress Test"
            config_file: custom-config.php
            plugins: ['myplugin/myplugin.php']
            activatePlugins: ['myplugin/myplugin.php']```

**Comment by johnbillion** [comment]
The parameter name is `configFile`, not `config_file`.

**Comment by lucatume** [comment]
Thanks (again) @johnbillion for reporting the issue and providing the information.

A note: the most up-to-date version of the documentation can be found at [https://wpbrowser.wptestkit.dev](https://wpbrowser.wptestkit.dev); the `WPLoader` module one, specifically, [here](https://wpbrowser.wptestkit.dev/modules/wploader#configuration).

As per the salt issue, I will look into the code a bit and provide you with a correct answer as I cannot reliably do that from memory.
