### ISSUE TITLE
Create a REST route on the fly before running a test

### ISSUE THREAD

**Issue by grazianodev** [lucatume/wp-browser#541]
Hello and thank you for your work. 

I am mostly using wp-browser in combination with Codeception's REST module (WPLoader is on `loadOnly` mode) to test my custom Wordpress REST api. Everything's working well, I only wish I could create a "fake" route for the purposes of a test, is that possible? 

I have tried registering the route in the `_before` method (Cest format) but that doesn't work (expectedly I guess, since Wordpress has already been loaded).

**Comment by lucatume** [comment]
Hi @grazianodev,

How you're going to create the test REST route will depend upon how you need to test it.
If I get it correctly, you should have a suite set up to use the `WPLoader` module (`loadOnly: true`), the `WPDb` one to set up and hydrate the database, the `WPBrowser` one as a requirement for the `REST` one to, finally, run the REST tests. Correct me if I'm wrong, please.

If this is the setup, then you need the test REST route to exist in the WordPress installation while running tests and in the same PHP thread that is receiving the request from the `REST` module.
Each test will involve 2 different PHP processes:
P1. the one spawned by the `codecept run ...` command; this will run `codecept > SomeTest > WPBrowser > REST > http://somesite.dev/wp-json/some-test-route`.
P2. the one spawned when the web-server that is serving the site at `http://somesite.dev` receives the request at `/wp-json/some-test-route`; this will run `WordPress index.php > wp-config.php > load plugins > process request > generate response`
P1 will, then receive the response and test it meets the expectations.

All this is to say the test REST route must exist on P2, not P1 (the `_before` method is called on P1).
To achieve this, you need to register the test REST route and endpoint as any other plugin would do, but only in the context of a test.

Enter [`WPFilesystem::haveMuPlugin` method](https://wpbrowser.wptestkit.dev/modules/wpfilesystem#havemuplugin); this method will create a mu-plugin in the WordPress installation at the start of the test, and remove it at the end. In that mu-plugin code define your test REST route and you should be ok.
Something like this:

```
public function tryToHitTestRoute(Tester $I){
    $code = <<< PLUGIN_CODE
add_action( 'rest_api_init', function () {
  register_rest_route( 'test', '/foo', [
    'methods' => 'GET',
    'callback' => function(){
        return 'Hello REST';
    },
  ) ];
} );
PLUGIN_CODE;

    $I->haveMuPlugin('test-route.php', $code);
    $I->sendGet('/test/foo');
    $I->seeResponseCodeIs(200);
    $I->seeResponseContains('Hello REST');
}
```

Let me know if this helps you, or if I got the setup completely wrong.

**Comment by grazianodev** [comment]
Hi Luca, 

thank you for your answer. My suite is set up exactly as you described, and your sample code works perfectly. 

Many thanks!
