### ISSUE TITLE
Use alternative to `iconv` if available

### ISSUE THREAD

**Issue by roborourke** [lucatume/wp-browser#542]
**Is your feature request related to a problem? Please describe.**

We are using Alpine Linux as the basis for our PHP Docker containers however the preloadable `iconv` library was removed in Alpine 3.13 and no longer works.

**Describe the solution you'd like**

The `slug` function uses `iconv`, but if `mb_string` alternatives are available it would ideally use those instead.

**Describe alternatives you've considered**

It is possible to install a fix for `iconv` on Alpine Linux but it's a community package and represents a potential security risk to production systems.

**Additional context**

- https://www.justinsilver.com/technology/linux/alpine-linux-php-iconv-fix/

**Comment by roborourke** [comment]
Obviously no worries if you want to require iconv, and I realise this is unnecessarily leading the solution so feel free to close.

**Comment by roborourke** [comment]
Seems there are other options too if `iconv` is unavailable or broken e.g. with the `intl` PHP module:

```php
transliterator_transliterate( 'Any-Latin; Latin-ASCII; [\u0080-\u7fff] remove', $subject )
```

**Comment by lucatume** [comment]
I've merged the PR for related to this and made a new release, thanks @roborourke for your contribution: much appreciated.

**Comment by roborourke** [comment]
Amazing cheers @lucatume!
