### ISSUE TITLE
[FEATURE REQUEST] remove laravel-wp-password dependency

### ISSUE THREAD

**Issue by calvinalkan** [lucatume/wp-browser#547]
It would be great if we could remove the dependency on laravel-wp-password. This package requires illuminate/support only to register a facade in laravel Apps. Illuminate/support is gigantic and then pulls in illuminate/contracts which pulls in.... 

I have looked at the package and it does not seem to do anything at all. Can we implement this ourselves? I can provide a PR. 

Unless im missing something here I dont see any reason to pull this in. Its quite painful to have all these general purpose facade classes and interfaces like request, cache etc pop up all the time in the IDE during development.

**Comment by lucatume** [comment]
Hi @calvinalkan, this is a good suggestion and one that goes in the direction of removing dependencies from the project.
If you could provide a PR, that would be great and welcome, otherwise, I will get to it when possible.

Sorry for the late reply.
