### ISSUE TITLE
[BUG] Incompatible with Codeception module-db 2.0

### ISSUE THREAD

**Issue by ryanshoover** [lucatume/wp-browser#549]
**Environment**
OS: Linux
PHP version: 7.4
Installed Codeception version: 4.1.22
Installed wp-browser version: 3.0.14
Local development environment: CircleCI version
WordPress structure and management: Default

**Can you perform the test manually?**
Skipping, not relevant

**Codeception configuration file**  
Skipping, not relevant

**Describe the bug**
Codeception Module DB released [version 2.0](https://github.com/Codeception/module-db/releases/tag/2.0.0) on 12/6. Since then, there's a compatibility issue between the WPDb::_initialize function and the Db::_initialize function. 

V2.0 [adds a return type declaration](https://github.com/Codeception/module-db/blob/2.0.0/src/Codeception/Module/Db.php#L481) of `:void` that [WPDb doesn't have](https://github.com/lucatume/wp-browser/blob/3.0.14/src/Codeception/Module/WPDb.php#L211). It triggers a fatal PHP error.

**Output**
```
Fatal error: Declaration of Codeception\Module\WPDb::_initialize(?tad\WPBrowser\Generators\Tables $table = NULL) must be compatible with Codeception\Module\Db::_initialize(): void in /home/circleci/.config/composer/vendor/lucatume/wp-browser/src/Codeception/Module/WPDb.php on line 211
```

**To Reproduce**
1. Update `codeception/module-db` to ^2.0
2. Run a test that requires WPDb.
3. You'll get the fatal PHP error.

**Expected behavior**
No fatal PHP error?

**Comment by lucatume** [comment]
Thanks @ryanshoover for reporting the issue.

I've fixed it by explicitly requiring version `^1.0` of the modules where suggested in [release 3.0.15](https://github.com/lucatume/wp-browser/releases/tag/3.0.15).
I would like wp-browser to track WordPress minimum requirements, and those include PHP 5.6.
