### ISSUE TITLE
Problems while installing http://codeception.com/for/wordpress

### ISSUE THREAD

**Issue by potentialcoder** [lucatume/wp-browser#55]
**composer require lucatume/wp-browser --dev**
Using version ^1.16 for lucatume/wp-browser
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

**Your requirements could not be resolved to an installable set of packages.**

  Problem 1
    - Installation request for lucatume/wp-browser ^1.16 -> satisfiable by lucatume/wp-browser[1.16.0].
    - Conclusion: remove codeception/codeception dev-master
    - Conclusion: don't install codeception/codeception dev-master
    - lucatume/wp-browser 1.16.0 requires lucatume/wp-browser-commons ^1.2.5 -> satisfiable by lucatume/wp-browser-commons[1.2.5, 1.2.6].
    - lucatume/wp-browser-commons 1.2.5 requires codeception/codeception ~2.1 -> satisfiable by codeception/codeception[2.1.x-dev, 2.2.x-dev].
    - lucatume/wp-browser-commons 1.2.6 requires codeception/codeception ~2.1 -> satisfiable by codeception/codeception[2.1.x-dev, 2.2.x-dev].
    - Can only install one of: codeception/codeception[2.1.x-dev, dev-master].
    - Can only install one of: codeception/codeception[2.2.x-dev, dev-master].
    - Installation request for codeception/codeception dev-master -> satisfiable by codeception/codeception[dev-master].

My composer.json

```
{

"require": {



},

"require-dev": {

	"codeception/codeception": "dev-master"
	
}


}
```

**Comment by lucatume** [comment]
wp-browser requires a stable version of codeception; `dev-master` is not.
wp-browser will also install codeception as it requires it, you can modify your `composer.json` file to this:

```json
{
    "require": {
    },
    "require-dev": {
	"lucatume/wp-browser": "^1.16"
    }
}
```

**Comment by potentialcoder** [comment]
Thanks, it helped. You may close this issue.

**Comment by lucatume** [comment]
Glad to hear it, have a great day.
