### ISSUE TITLE
[BUG] WPDb::_initialize() is not compatible with Db::_initialize() in codeception/module-db:2.0 

### ISSUE THREAD

**Issue by stefanfisk** [lucatume/wp-browser#550]
**Environment**
OS: Linux
PHP version: 7.4.26  
Installed Codeception version: 4.1.23
Installed wp-browser version: 3.0.15
WordPress version: 5.8.3
Local development environment: Docker
WordPress structure and management: other

**Can you perform the test manually?**
n/a

**Codeception configuration file**  
n/a

**Suite configuration file**
n/a

**Describe the bug**
codeception/module-db:2.0 uses strict types, which makes [this](https://github.com/lucatume/wp-browser/blob/389f7055e2f25618b955721fc27f63df777f620e/src/Codeception/Module/WPDb.php#L211) incompatible with [this](https://github.com/Codeception/module-db/blob/23f4fe67ecc1902982001839dd131397d605d681/src/Codeception/Module/Db.php#L481)

**Output**
```
PHP Fatal error:  Declaration of Codeception\Module\WPDb::_initialize(?tad\WPBrowser\Generators\Tables $table = NULL) must be compatible with Codeception\Module\Db::_initialize(): void in /srv/app/vendor/lucatume/wp-browser/src/Codeception/Module/WPDb.php on line 211
```

**To Reproduce**
- `composer require --dev codeception/module-db`
- Run any test suite which uses WPDb

**Expected behavior**
Expected is probably stretching it since you only suggest `codeception/module-db:^1.0 `, but what I would LIKE is for the tests to run just as before!

**Screenshots**
n/a

**Additional context**
I'd assume that this affects a bunch of other methods, but I didn't have time to investigate properly right now.

**Comment by simonhammes** [comment]
@lucatume Maybe it would make sense to add a `conflict` section to composer.json and declare that wp-browser is incompatible with specific versions of modules.

**Comment by lucatume** [comment]
Thanks @stefanfisk for the report, and @simonhammes for the suggestion: this is out with [version `3.0.17` of the package.](https://github.com/lucatume/wp-browser/releases/tag/3.0.17). 

If you're wondering why I skipped version `3.0.16`, then I'm wondering it too. My release tool failed me, or I failed it, and it was lost.

**Comment by abr4xas** [comment]
Just for the record:

This issue is still happening in 3.1.3

**Comment by lucatume** [comment]
> Just for the record:
> 
> This issue is still happening in 3.1.3

@abr4xas would you mind providing more information? Version `3.1.3` of wp-browser [states a conflict section to deal with that](https://github.com/lucatume/wp-browser/blob/master/composer.json#L84), so I am curious as to how that might still happen.

![CleanShot 2022-02-09 at 08 38 57](https://user-images.githubusercontent.com/2749650/153143866-c61523c9-cc90-4b91-a3bd-84ec16452091.png)

**Comment by abr4xas** [comment]
Hi @lucatume this is my output:


```bash
PHP Fatal error:  Declaration of Codeception\Module\WPDb::_initialize(?tad\WPBrowser\Generators\Tables $table = NULL)
 must be compatible with Codeception\Module\Db::_initialize(): void in app/site/wp-content/mu-plugins/aprende-lib/lib/aprende-modules/vendor/lucatume/wp-browser/src/Codeception/Module/WPDb.php on line 211

Fatal error: Declaration of Codeception\Module\WPDb::_initialize(?tad\WPBrowser\Generators\Tables $table = NULL) must be compatible with Codeception\Module\Db::_initialize(): void in app/site/wp-content/mu-plugins/aprende-lib/lib/aprende-modules/vendor/lucatume/wp-browser/src/Codeception/Module/WPDb.php on line 211
```


This is my composer.json file:


```json
{
    "require-dev": {
        "codeception/codeception": "^4.1",
        "codeception/module-asserts": "^1.0.0",
        "codeception/module-cli": "^2.0",
        "codeception/module-db": "^2.0",
        "codeception/module-filesystem": "^2.0",
        "codeception/module-phpbrowser": "^1.0.0",
        "codeception/module-webdriver": "^2.0",
        "codeception/util-universalframework": "^1.0",
        "lucatume/wp-browser": "^2.4"
    }
}
```

https://wpbrowser.wptestkit.dev/codeception-4-suport

**Comment by lucatume** [comment]
@abr4xas you've linked the documentation and this is the content of the `composer.json` file from the documentation:
```json
{
  "require-dev": {
    "lucatume/wp-browser": "^2.4",
    "codeception/module-asserts": "^1.0",
    "codeception/module-phpbrowser": "^1.0",
    "codeception/module-webdriver": "^1.0",
    "codeception/module-db": "^1.0",
    "codeception/module-filesystem": "^1.0",
    "codeception/module-cli": "^1.0",
    "codeception/util-universalframework": "^1.0"
  }
}
```
Emphasis on the `"codeception/module-db": "^1.0"` line; yours is `"codeception/module-db": "^2.0"`. I'm wondering how you could make the installation happen. From my understanding of the `conflict` section in the Composer configuration file, installing `codeception/module-db:^2.0` should not be allowed at all.
