### ISSUE TITLE
[FEATURE REQUEST] Remove bootstrapp code at the top of WPTestCase

### ISSUE THREAD

**Issue by calvinalkan** [lucatume/wp-browser#563]
I'm experiencing a lot of problems with static analysis tools that completely break when they encounter the [code](https://github.com/lucatume/wp-browser/blob/master/src/Codeception/TestCase/WPTestCase.php#L25) on top of the WPTestCase.php class. 

Are there any reasons for not having this code somewhere else? Ie: Inside the setup method or an autoloaded file, or a composer bootstrap script, etc?

Problems are most likely triggered by autoloading the class in some form which then runs the code above the code.

**Comment by calvinalkan** [comment]
@lucatume The issue is in 

define('PHPUNIT_COMPOSER_INSTALL', tad\WPBrowser\vendorDir('autoload.php'));

see https://github.com/symplify/symplify/issues/3938#issuecomment-1046045188

**Comment by lucatume** [comment]
Fixed in `3.1.4`: [![asciicast](https://asciinema.org/a/labmUJY4OnFMctiiOVmUlRN2J.svg)](https://asciinema.org/a/labmUJY4OnFMctiiOVmUlRN2J)
