### ISSUE TITLE
Error: 90980 segmentation fault

### ISSUE THREAD

**Issue by maugelves** [lucatume/wp-browser#57]
Hi Luca!
I've just installed the WP-Browser to try it and I'm having an issue when I'm trying to clean and populate the database.

The error I'm receiving:
`[1]    90980 segmentation fault  vendor/lucatume/wp-browser/wpcept run`

This is my composer.json:
`{
    "name": "maugelves/seiyuv2",
    "description": "Seiyu WordPress Theme V2.0",
    "type": "WordPress Theme",
    "require": {
        "codeception/codeception": "^2.2",
        "lucatume/wp-browser": "~1.11"
    },
    "license": "GPL",
    "authors": [
        {
            "name": "Mauricio Gelves",
            "email": "yo@maugelves.com"
        }
    ]
}`

The acceptance.suite.yml:
`
class_name: AcceptanceTester
modules:
    enabled:
      - WPWebDriver
      - WPDb
    config:
      WPWebDriver:
          browser: phantomjs
          port: 4444
          window_size: '1024x768'
          url: 'http://localhost/seiyuwp/'
          adminUsername: 'mgelves@gmail.com'
          adminPassword: 'mauricio'
          adminPath: '/wp-admin'
      WPDb:
          dsn: 'mysql:host=127.0.0.1;dbname=seiyudb'
          user: 'root'
          password: 'root'
          dump: 'tests/_data/dump.sql'
          populate: true
          cleanup: true
          reconnect: true
          url: 'http://localhost/seiyuwp'
          urlReplacement: false
          tablePrefix: 'lxpy10ags_'
`

**Comment by lucatume** [comment]
First question: how big is your DB dump? WPDb, in the same way Codeception own Db module works, cannot handle large dump files.

I'm working on a solution to switch over to `mysql` command but for the time being that's not supported.

**Comment by maugelves** [comment]
Ciao Luca!
It's a 5.4Mb SQL dump, and that's weird because I've been able to handle larger files with the Db module. But yeah, maybe it's because your module is not using `mysql`.
Anyway, thanks a lot for the work you've done and I'll be waiting for the new version.
Mauricio

**Comment by lucatume** [comment]
Then that should not be the issue. I've got similar scenarios and never had that.

Could you paste here the whole error report? Ideally with XDebug and running with `-vvv`

**Comment by lucatume** [comment]
Closing due to lacking activity.
