### ISSUE TITLE
[BUG] site stop working after install wp-browser

### ISSUE THREAD

**Issue by manh-trinhquoc** [lucatume/wp-browser#570]
**Environment**
OS: Windows
PHP version: 7.4 
Installed Codeception version:   4.1
Installed wp-browser version: 3.1  
WordPress version: 5.9
Local development environment: docker
WordPress structure and management:  Bedrock

**Describe the bug**
I use the Lumberjack [framework](https://lumberjack.rareloop.com/). After I install `wp-browser` by running `composer require --dev lucatume/wp-browser`. My website stop working and have error: 
![image](https://user-images.githubusercontent.com/34735335/161226039-1db9e2f2-d66e-40a2-86f7-12488a6b9a17.png)

**Comment by lucatume** [comment]
Hi @manh-trinhquoc,

I cannot offer support for a custom setup and installation if not provided more information.
If you could dig a bit further and find the cause of the bug, that would help me provide a solution.
