### ISSUE TITLE
[FEATURE REQUEST] Support passing environment arguments to WPCLI module

### ISSUE THREAD

**Issue by calvinalkan** [lucatume/wp-browser#576]
**Is your feature request related to a problem? Please describe.**
I can't test code that interacts with environment variables since its currently only possible to pass them in the suite config,
but not for individual calls.

**Describe the solution you'd like**

Id like to change the method signature of `WPCLI::cli()` to this:

```php

public function cli($userCommand = 'core version', array $env = [])
    {
        $return = $this->run($userCommand, $env);

        return $return[1];
    }

```

So you would be able to run tests like this:

```php

 $I->cli(['some-command', 'some-arg'], ['SHELL_VERBOSITY' => 1, 'ANOTHER_ENV_ARG' => 0]);

```

**Describe alternatives you've considered**
There are none I think, tests run in a child process. 

**Additional context**
This is the code I want to test:

```php
        switch ((int) getenv('SHELL_VERBOSITY')) {
            case -1:
                $verbosity = Verbosity::QUIET;
                $verbosity_level = 'quiet';

                break;
            case 1:
                $verbosity = Verbosity::VERBOSE;
                $verbosity_level = 'verbose';

                break;
            case 2:
                $verbosity = Verbosity::VERY_VERBOSE;
                $verbosity_level = 'verbose';

                break;
            case 3:
                $verbosity = Verbosity::DEBUG;
                $verbosity_level = 'debug';

                break;
        }

```

**Comment by calvinalkan** [comment]
This should not be too hard IMO, its also non-breaking.

**Comment by lucatume** [comment]
Again, thanks for the good idea and the example code supporting it.
I will try to get to this sooner, rather than later.
As always, PRs are welcome should you be so inclined and have time.
