### ISSUE TITLE
[PHPUnit_Framework_Exception] Use of undefined constant WP_TESTS_FORCE_KNOWN_BUGS - assumed 'WP_TESTS_FORCE_KNOWN_BUGS'

### ISSUE THREAD

**Issue by lougreenwood** [lucatume/wp-browser#58]
Hi,

I've just setup wpbrowser in an attempt to be able to access plugin methods in my unit test code.

I've created an example unit test using `wpcept generate:wpunit suite SomeClass` and it generates the following file:

```
<?php

class SomeClassTest extends \Codeception\TestCase\WPTestCase
{

    public function setUp()
    {
        // before
        parent::setUp();

        // your set up methods here
    }

    public function tearDown()
    {
        // your tear down methods here

        // then
        parent::tearDown();
    }

    // tests
    public function testMe()
    {
    }

}
```

The problem is that when I run the unit test suite, I get the undefined const error:

```
bin/wpcept run unit
Codeception PHP Testing Framework v2.2.5
Powered by PHPUnit 5.6.1 by Sebastian Bergmann and contributors.

Unit Tests (1) ---------------------------------------------
E SomeClassTest: Me (0.01s)
------------------------------------------------------------


Time: 834 ms, Memory: 8.00MB

There was 1 error:

---------
1) SomeClassTest: Me
 Test  tests/unit/SomeClassTest.php:testMe

  [PHPUnit_Framework_Exception] Use of undefined constant WP_TESTS_FORCE_KNOWN_BUGS - assumed 'WP_TESTS_FORCE_KNOWN_BUGS'

#1  /usr/share/nginx/html/htdocs/content/themes/my-theme/vendor/lucatume/wp-browser/wpcept:52

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

As an aside, my WP install is based upon Themosis (http://framework.themosis.com)

**Comment by lucatume** [comment]
that constant is defined in the the [bootstrap file](https://github.com/lucatume/wp-browser/blob/master/src/includes/bootstrap.php#L18); is that file being included?
My guess is you are extending the `\Codeception\TestCase\WPTestCase` (generated with the command) and using it in real unit tests.
That test case is meant to be used together with the `WPLoader` module that will load WordPress before the tests: is the `WPLoader` module configured and loaded in your `unit` suite?

**Comment by lougreenwood** [comment]
Re constant & bootstrap, I don't see any _bootstrap.php file being populated.

I noticed that when I run except bootstrap, I receive an error about Wordpress location not being where expected and the bootstrap then seems to fail, the same goes for wpcept build

wpcept bootstrap
```
bin/wpcept bootstrap
 Initializing Codeception in /usr/share/nginx/html/htdocs/content/themes/my-theme

File codeception.yml created       <- global configuration
tests/unit created                    <- unit tests
tests/unit.suite.yml written          <- unit tests suite configuration
tests/integration created             <- integration tests
tests/integration.suite.yml written   <- integration tests suite configuration
tests/functional created              <- functional tests
tests/functional.suite.yml written    <- functional tests suite configuration
tests/acceptance created              <- acceptance tests
tests/acceptance.suite.yml written    <- acceptance tests suite configuration
tests/_output was added to .gitignore
 ---
tests/_bootstrap.php written <- global bootstrap file
Building initial Tester classes
Building Actor classes for suites: acceptance, functional, integration, unit
 -> AcceptanceTesterActions.php generated successfully. 0 methods added
\AcceptanceTester includes modules: \Helper\Acceptance, WPBrowser


  [Codeception\Exception\ModuleConfigException]
  WordPress module is not configured!

  The path `/var/www/wordpress` is not pointing to a valid WordPress installation folder.


bootstrap [-ns|--namespace [NAMESPACE]] [-a|--actor [ACTOR]] [-e|--empty] [--] [<path>]
```

wpcept build
```
bin/wpcept build
Building Actor classes for suites: acceptance, functional, integration, unit
 -> AcceptanceTesterActions.php generated successfully. 0 methods added
\AcceptanceTester includes modules: \Helper\Acceptance, WPBrowser


  [Codeception\Exception\ModuleConfigException]
  WordPress module is not configured!

  The path `/var/www/wordpress` is not pointing to a valid WordPress installation folder.


build
```

Yes, I was trying to use `WPTestCase` in unit tests, however I was using the `WPBootstrapper` module to try and access methods provided by other plugins.

**Comment by lougreenwood** [comment]
To clarify, here's my current setup and what I'm trying to achieve.

- I have a local wordpress installation with a development db loaded.
- I have a theme with various methods which I need to perform integration tests against.
- Many methods make use of a separate plugin (http://pods.io) to read and write to the database.
- I need to be able to run my tests against my local setup (`WPLoader` seems incompatible here), have access to the plugin specified as well as all WP functions within my integration tests.

I first tried using the `WPBootstrapper`, but this didn't give me access to the plugin and it's functions (do I need to load plugins which are already enabled in my local WP setup?), so I just tried `WordPress`, this again doesn't give me access to the plugin functions, but I also couldn't call any WP functions either ( activate_plugin() returned `[Error] Call to undefined function activate_plugin()` ).

Any suggestions on where I'm going wrong? Thanks

**Comment by lucatume** [comment]
I have no experience with pods but being able to make integration tests with it seems a worthy achievement.
The module to use is `WPLoader` (`WordPress` is for functional testing and `WPBootstrapper` for some edge acceptance cases) and it comes with a degree of customization that allowed it, up to this point, to test anything; should this not be the case I'm more than willing to look into it and solve the issue.

I've put up [a demo repository](https://github.com/lucatume/pods-theme-test) where I'm running integreation tests using the `WPLoader` module on a theme relying on pods so that we can have and informed discussion.

**Comment by lougreenwood** [comment]
Excellent, thanks I'll take a look at this in the coming days.

I wonder if my issue calling any core WP functions relates to me using the Themosis framework (http://framework.themosis.com) changes the directory layout, installs WP into a sub dir and adds additional bootstrapping to the WP process.

For example, to get an integration test to run, I had to point my WPLoader root url at `htdocs/cms/` (a sub dir within theists that contains the wp installation), but I was then unable to actually all any WP functions, which suggests that it isn't properly initialised.

**Comment by lucatume** [comment]
Yes,

as you rightfully did the `wpRootFolder` param of `WPLoader` configuration needs to point to the WordPress core folder (the one containing `wp-load.php`) and custom installations will need to change that.
I've got no experience with Themosis but, looking at the framework [composer configuration file](https://github.com/themosis/themosis/blob/master/composer.json) I'd set up the `wpRootFolder` parameter to `/your/local/sites/site/htdocs/cms`; then, if the framework needs that, use the `configFile` parameter to load whatever bootstrap file is needed for the framework to work (see [the config guide](https://github.com/lucatume/wp-browser#wploader-configuration)).

**Comment by lougreenwood** [comment]
Cool, thanks, I'll take a look at this very shortly and hopefully will be able to get back to you with a working themosis/pods setup and details of the final config.

Cheers

**Comment by lucatume** [comment]
Closing due to lacking activity.
