### ISSUE TITLE
[DOC REQUEST] lucatume/codeception docker image

### ISSUE THREAD

**Issue by calvinalkan** [lucatume/wp-browser#581]
Is this [docker image](https://hub.docker.com/r/lucatume/codeception) deprecated/unmainted/not-recommended?

If not, where is the source?

I would like to check out the dockerfile that comes with it.

**Comment by szepeviktor** [comment]
@calvinalkan Maybe here? https://github.com/lucatume/dockerfiles/tree/master/containers/codeception
