### ISSUE TITLE
[DOC REQUEST] Missing instructions on generating the Integration test suite

### ISSUE THREAD

**Issue by w33zy** [lucatume/wp-browser#582]
**Did you search the documentation first?**
Yes. 

**What do you think is missing from the documentation?**
Integration tests are referred to in the `Levels of testing` section of the docs, however there is no steps for how to generate the integrations test suite in the `Tutorials` section of the docs.

**Comment by lucatume** [comment]
The project is built on top of Codeception, in various places in the documentation there are links to Codeception documentation to find out more.
Creating a suite is [documented in Codeception documentation.](https://codeception.com/docs/reference/Commands#GenerateSuite)

**Comment by w33zy** [comment]
Hey @lucatume 
Earlier today I was just checking up on this project and I realize v4 was released a few days ago. 
Congrats!
