### ISSUE TITLE
[BUG] WPTestCase classes break Codeceptions implied API

### ISSUE THREAD

**Issue by calvinalkan** [lucatume/wp-browser#583]
**Environment**
OS: Mac
PHP version: 7.4
Installed Codeception version: 4.2
Installed wp-browser version: 3.1.6
WordPress version: [e.g. 5.4]  
Local development environment: Docker
WordPress structure and management: default

**Describe the bug**
All Codeception test cases expose users to the possibility of using the _before() and _after() callbacks. 
Analog to PHPUnits setup and tearDown().
See here https://codeception.com/docs/05-UnitTests

These methods are called from inside the _tearDown() / _setUp() method of Codeceptions `Unit` class
https://github.com/Codeception/Codeception/blob/4.2.0/src/Codeception/Test/Unit.php#L57

`WPTestCase` overwrites these methods without calling `_before()` and `_after()`. 

**Expected behavior**
`WPTestCase` should call `_before()` and `_after()` call in its setup methods.

**Comment by lucatume** [comment]
Fixed in version `3.2.1`
