### ISSUE TITLE
[DOC REQUEST] bootstrapActions for woocommerce

### ISSUE THREAD

**Issue by Mte90** [lucatume/wp-browser#589]
As per PM:

Create a function in your `_bootstrap.php`:
```
function woo_disable_wizard() {
	\add_filter( 'woocommerce_prevent_automatic_wizard_redirect', '__return_true' );
}
```

In your `WPLoader`:
```
            bootstrapActions:
              - woo_disable_wizard
```

In this way woocommerce is activated without the wizard that can generate errors as is changing the output of the page with a redirect.

**Comment by lucatume** [comment]
The functionality [is already supported in version 3](https://github.com/lucatume/wp-browser/blob/v3/src/Codeception/Module/WPLoader.php#L776-L779); I think this could make its way into a "cookbook" or tutorial of sorts.

**Comment by lucatume** [comment]
This has been fixed in v4, closing.
