### ISSUE TITLE
Update dotenv to a more recent version

### ISSUE THREAD

**Issue by covovker** [lucatume/wp-browser#591]
**Is your feature request related to a problem? Please describe.**
It became a problem to use WpBrowser along with other wordpress plugins in my environment due to the fact that is has an outdated DotEnv library. Newer versions of DotEnv initialize with "createImmutable", while older ones with "create". The problem takes place when the plugin with an older DotEnv is loaded before the newer one, it crashes with "I don't know createImmutable method" error. 

**Describe the solution you'd like**
Update composer dependencies to include a recent version of Dotenv and use more up to date initialization call.

**Comment by lucatume** [comment]
Updated to version 5 in version 4 of the project.
