### ISSUE TITLE
[Enhancement] Use waitForJs in WPWebDriver loginAs method

### ISSUE THREAD

**Issue by lucatume** [lucatume/wp-browser#596]
From a comment on #65 by @calvinalkan, the `loginAs` method of the `WPWebDriver` module can be improved to use JS and work around WordPress attempt to focus on the login fields:

```php
$this->tester->waitForJS("return (document.activeElement === document.getElementById('user_login')) || (document.activeElement === document.getElementById('user_pass'))");


```

_Originally posted by @calvinalkan in https://github.com/lucatume/wp-browser/issues/65#issuecomment-1384640854_

**Comment by calvinalkan** [comment]
This works unreliably with the WordPress intermin login modal.

It cost me another two days. 

I found this deeply buried in Core:

`\add_filter( 'enable_login_autofocus', fn() => false );`

This is recommended.
