### ISSUE TITLE
[FEATURE REQUEST] Removal of nodiacritic

### ISSUE THREAD

**Issue by simaotwx** [lucatume/wp-browser#600]
**Is your feature request related to a problem? Please describe.**
The [nodiacritic](https://github.com/vria/nodiacritic) library is licensed under GPL-2.0 (see https://github.com/vria/nodiacritic/blob/master/LICENSE). This means it is incompatible when used in GPL-3.0 projects. Also, it looks like using it in a MIT licensed project is also not correct, but this project is licensed under MIT.

This causes following issue: https://github.com/publishpress/PublishPress-Planner/issues/1237 via https://github.com/publishpress/wp-browser which is a fork.

**Describe the solution you'd like**
The `remove_accents()` function has existed in WordPress since 1.2.1 (see https://developer.wordpress.org/reference/functions/remove_accents/#changelog). Hence, in my opinion, it is not necessary to include this polyfill anymore. Removing this library would solve the license problem.

**Describe alternatives you've considered**
The alternative would be for the author to relicense nodiacritic or to rewrite it with a new license.

**Additional context**
https://github.com/lucatume/wp-browser/blob/04996929c04b8ad7655b83aa5b196435fa5232b9/src/tad/WPBrowser/wp-polyfills.php#L52

**Comment by lucatume** [comment]
I'm updating the project to be compatible with Codeception 5 and PHP 8: that looks the right scenario to remove that dependency. 
I'm ideally open to removing it if, in the final version, it turns out to not provide more value or be easily replaced or internalized, I will look into that in the current work.

**Comment by simaotwx** [comment]
Thank you for your letting me know. I'm looking forward to it.

**Comment by lucatume** [comment]
Removed in version 4 of the project.
