### ISSUE TITLE
[DOC REQUEST] Handling CodeCoverage when running multiple test suites separately

### ISSUE THREAD

**Issue by justlevine** [lucatume/wp-browser#602]
**Did you search the documentation first?** yes

**What do you think is missing from the documentation?**
In the [Frequently Asked Questions](https://wpbrowser.wptestkit.dev/welcome/faq#can-i-run-all-my-tests-with-one-command), it's pretty clear that the ideal way to run Codeception is to `run each suite separately.`

However, I don't see any instruction on how to use this pattern when generating code coverage, since by default the `coverage.xml` file gets overwritten on each run.

**Do you have any examples of what you'd like to see added to the documentation?**
Any sort of instruction of generating codecoverage when running codeception separately for each test.

**Comment by lucatume** [comment]
The [Codeception documentation](https://codeception.com/docs/ParallelExecution#Step-3-Merge-Results) partially covers a similar problem in the context of needing to merge coverage reports and [there are libraries dedicated to how to merge PHPUnit coverage reports](https://github.com/Nimut/phpunit-merger), as an example.

Did you find a good solution you would like to be added to the documentation? 

I usually run each suite with the `--coverage-xml $suite.coverage.xml` option and then used a library like the one above to join them.

**Comment by justlevine** [comment]
Thanks @lucatume for the links!

> Did you find a good solution you would like to be added to the documentation?

Not a specific one that I feel particularly strongly outweighs the others. My suggestion is more about calling attention that since the recommendation is to run suites separately, you might need to join the results (with or without a few package recs or outlinks).

For users (including myself) who usually code/test in with a single library and suffice with a `vendor/bin/codecept run` on their CI, the impact on coverage reports doesn't immediately jump to mind. My hunch is that's even more true when we're talking WP devs for whom wp-browser is their first/only experience with codeception, and very well might even be their first experience with _any_ testing suite.

**Comment by BrianHenryIE** [comment]
In my `composer.json` I have:

```
  "require-dev": {
    "phpunit/phpcov": "*",
...
  "scripts": {
    "test-coverage": [
      "mkdir -p tests/_output/html",
      "codecept run unit --coverage unit.cov",
      "codecept run wpunit --coverage wpunit.cov",
      "phpcov merge --clover tests/_output/clover.xml --html tests/_output/html tests/_output",
      "open tests/_output/html/index.html"
    ],
```

And I run with: `XDEBUG_MODE=coverage composer test-coverage`

I carry on my work in another window and Firefox opens with the coverage report when it's finished.

Shameless plug: use your codecoverage report to get your tests to run faster: [BrianHenryIE/php-diff-test](https://github.com/BrianHenryIE/php-diff-test/)
