### ISSUE TITLE
[SETUP ISSUE]

### ISSUE THREAD

**Issue by Cb040719** [lucatume/wp-browser#604]
**Environment**
OS: [Windows]
PHP version: [8.1.12]
Installed Codeception version: [5.0.9]
Installed wp-browser version: [latest]
WordPress version: [6.1.1]
Local development environment: [xampp]

By running composer require --dev lucatume/wp-browser this is the output error:

 Problem 1
    - lucatume/wp-browser 1.11.0 requires lucatume/wp-browser-commons ~1.0.0 -> satisfiable by lucatume/wp-browser-commons[1.0.0, 1.0.1].
    - lucatume/wp-browser[1.12.0, ..., 1.14.2] require lucatume/wp-browser-commons ~1.0 -> satisfiable by lucatume/wp-browser-commons[1.0.0, ..., 1.2.10]. 
    - lucatume/wp-browser 1.1.0 requires codeception/codeception 2.0.*@dev -> found codeception/codeception[2.0.0, ..., 2.0.16] but it conflicts with your root composer.json require (^5.0).
    - lucatume/wp-browser[1.2.0, ..., 1.6.7] require badcow/lorem-ipsum dev-master -> found badcow/lorem-ipsum[dev-master] but it does not match your minimum-stability.
    - lucatume/wp-browser[1.6.8, ..., 1.10.11] require codeception/codeception ~2.0 -> found codeception/codeception[2.0.0, ..., 2.5.6] but it conflicts with your root composer.json require (^5.0).
    - lucatume/wp-browser[1.6.15, ..., 1.6.19] require codeception/codeception 2.1.1 -> found codeception/codeception[2.1.1] but it conflicts with your root composer.json require (^5.0).
    - lucatume/wp-browser 1.10.12 requires codeception/codeception ~2.1 -> found codeception/codeception[2.1.0, ..., 2.5.6] but it conflicts with your root composer.json require (^5.0).
    - lucatume/wp-browser-commons[1.0.0, ..., 1.2.10] require codeception/codeception ~2.1 -> found codeception/codeception[2.1.0, ..., 2.5.6] but it conflicts with your root composer.json require (^5.0).
    - lucatume/wp-browser[1.14.3, ..., 1.15.2] require symfony/process ~3.1 -> found symfony/process[v3.1.0, ..., v3.4.47] but the package is fixed to v6.0.19 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - lucatume/wp-browser[1.16.0, ..., 1.21.23] require symfony/process ~2.1 -> found symfony/process[v2.1.0, ..., v2.8.52] but the package is fixed to v6.0.19 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - lucatume/wp-browser[1.21.24, ..., 1.24.5, 2.2.0, ..., 2.2.7] require symfony/process >=2.7 <5.0 -> found symfony/process[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.44] but the package is fixed to v6.0.19 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - lucatume/wp-browser[2.0.0, ..., 2.1.6] require php ^7.0 -> your php version (8.1.12) does not satisfy that requirement.
    - lucatume/wp-browser[2.2.8, ..., 2.3.4] require codeception/codeception ^2.5 || ^3.0 -> found codeception/codeception[2.5.0, ..., 2.5.6, 3.0.0, ..., 3.1.3] but it conflicts with your root composer.json require (^5.0).
    - lucatume/wp-browser[2.2.21, ..., 2.2.24] require codeception/codeception ^2.5 -> found codeception/codeception[2.5.0, ..., 2.5.6] but it conflicts with your root composer.json require (^5.0).
    - lucatume/wp-browser[2.4.0, ..., 2.6.17, 3.0.0, ..., 3.1.7] require codeception/codeception ^2.5 || ^3.0 || ^4.0 -> found codeception/codeception[2.5.0, ..., 2.5.6, 3.0.0, ..., 3.1.3, 4.0.0, ..., 4.2.2] but it conflicts with your root composer.json require (^5.0).
    - lucatume/wp-browser 2.5.6 requires codeception/codeception ^3.0 -> found codeception/codeception[3.0.0, ..., 3.1.3] but it conflicts with your root composer.json require (^5.0).
    - Root composer.json requires lucatume/wp-browser * -> satisfiable by lucatume/wp-browser[1.1.0, ..., 1.24.5, 2.0.0, ..., 2.6.17, 3.0.0, ..., 3.1.7].

**Comment by lucatume** [comment]
Could you post your `composer.json` file? Do you require `codeception/codeception:^5.0` in it?

**Comment by Cb040719** [comment]
Here's the composer.json require-dev. At the moment yes, the file requires codeception/codeception:^5.0, but I tried to change this value with no success.

"require-dev": {
        "phuml/phuml": "^6.1",
        "codeception/codeception": "^5.0",
        "codeception/module-asserts": "*",
        "codeception/module-db": "^3.1",
        "phpunit/phpunit": "^9"
    }, 

The same issue happens also when I try to install the other required plugins, like codeception/module-filesystem and codeception/module-webdriver.

**Comment by lucatume** [comment]
Version 3 of wp-browser is not compatible with Codeception 5, I'm working on v4 that will be compatible with Codeception 5.
You can remove the `codeception/codeception` and `phpunit/phpunit` requirements from the `composer.json` file: it's already required by wp-browser.

**Comment by Cb040719** [comment]
Thanks a lot
