### ISSUE TITLE
Wordpress acceptance test always redirect to install.php

### ISSUE THREAD

**Issue by Flyaway87** [lucatume/wp-browser#61]
I don't know if this is the right place to ask this question, but I don't understand where the problem is located, I don't understand if I did something wrong with config files or something else.

I have a fresh installed wordpress site on my machine: http://localhost/wordpress/
I have access to both frontend and backend without any kind of problem.

I would like to run a very small acceptance test to see if I can login as administrator (I'm new to codeception and wp-browser, so I'm learning from scratch).

When I run the test, instead of opening the wp-login page, the test keeps me redirecting on the install.php page, so the wordpress site is erased every time.

This is my  acceptance.suite.yml file

`class_name: AcceptanceTester`
`modules:`
    `enabled:`
        `- \Helper\Acceptance`
        `- WPDb`
       ` - WPWebDriver`
    `config:`
        `WPDb:`
            `dsn: 'mysql:host=localhost;dbname=wordpress'`
            `user: root`
            `password: passwd`
            `dump: tests/_data/dump.sql`
            `populate: true`
            `cleanup: true`
            `url: 'http://localhost/wordpress'`
            `urlReplacement: true`
            `tablePrefix: wp_`
        `WPWebDriver:`
            `url: 'http://localhost/wordpress'`
            `browser: firefox`
            `adminUsername: admin`
            `adminPassword: admin`
            `adminPath: /wp-admin/`

And this is my cept file:

```
<?php 
$I = new AcceptanceTester($scenario);
$I->wantTo('perform actions and see result');

$I->amOnPage('/');
$I->loginAsAdmin();
?>
```
It has been days, but I literally can't figure out what I'm doing wrong...

**Comment by lucatume** [comment]
Hi, this is the right place to ask the question.

What I think is happening: you are telling the `WPDb` module it should populate the database before each test and the module is doing exactly that but using an empty SQL dump file.

The `WPDb` module will reset the database to a pristine state before each test; this is to avoid tests from influencing each other and create false positives or false negatives.  
Think of a first test method creating a post with and of a second method creating a post; if the second method tried to assert the database should contain 1 post it would fail as the database actually contains the post created from the first method too.  
The 3 parameters you have to look at here in `WPDb` configuration are:

* `dump` - this tells the `WPDb` module that, when asked to repopulate the database, it should use this SQL dump file
* `populate` - this tells the module that it should *populate* the database using the dump file **before running each test case** (the class)
* `cleanup` - this tells the module that is should *populate* the database using the dump file **before each test method**

The `WPDb` module is an extension of [Codeception `Db` module](http://codeception.com/docs/modules/Db "Db - Codeception - Documentation") so the same documentation applies.  

What I usually do when setting up my tests is go through the installation manually, activate the theme/plugins I need and then run some [wp-cli](http://wp-cli.org/ "Command line interface for WordPress - WP-CLI") scripts:

```shell
wp site empty --yes
wp theme activate my-theme
wp plugin activate one two three my-plugin
wp db export wp-content/plugins/my-plugin/tests/_data/dump.sql
```

where the commands should point/specifgy themes/plugins you need and the real location of that `tests/_data/dump.sql` file.

**Comment by Flyaway87** [comment]
Obviously I missed all the dump.sql part... Now it works perfectly! 
Many thanks for all the tips, that's really appreciated :)

**Comment by lucatume** [comment]
You are welcome, closing as solved.
