### ISSUE TITLE
[BUG] File wp-db.php is deprecated since version 6.1.0

### ISSUE THREAD

**Issue by webzunft** [lucatume/wp-browser#610]
**Environment**
OS: Mac
PHP version: 7.4.33
Installed Codeception version: 3.1.8
Installed wp-browser version: 3.1.8
WordPress version: 6.2
Local development environment: MAMP
WordPress structure and management: ?

I see the following notice when running `vendor/bin/codecept run wpunit`

```
Deprecated: File wp-db.php is <strong>deprecated</strong> since version 6.1.0! Use wp-includes/class-wpdb.php instead.
in /wp-includes/functions.php on line 5603
```

**To Reproduce**

I had a local issue when setting wp-browser up for the very first time and added `codecept_debug("Isolated installation script output: \n\n" . ob_get_clean());` after `ob_start()` in `bootstrap.php` line 139. This helped me resolve my issue. As a side effect, it also showed the warning I report here.

**Expected behavior**

Use `class-wpdb.php` in

https://github.com/lucatume/wp-browser/blob/master/src/includes/same-scope-install.php#L20

and

https://github.com/lucatume/wp-browser/blob/master/src/includes/isolated-install.php#L79

**Comment by lucatume** [comment]
Thannks @webzunft for the report, I've fixed and released this in [version 3.1.9](https://github.com/lucatume/wp-browser/releases/tag/3.1.9)
