### ISSUE TITLE
WPWebDriver doesn't support custom header config [DOC BUG]

### ISSUE THREAD

**Issue by RobjS** [lucatume/wp-browser#615]
**wp-browser version**
Latest (3.1.9 at time of writing)

**Link**
https://github.com/lucatume/wp-browser/blob/38e15758d2960d31ce6347bff843574f147d2630/docs/tutorials/automatically-change-db-in-tests.md#L4, https://wpbrowser.wptestkit.dev/tutorials/automatically-change-db-in-tests

**Issue**
The documentation describes using the `header` config to set custom HTTP headers for both `WPBrowser` and `WPWebDriver` modules. However, my local testing suggests this doesn't work with the `WPWebDriver` module, and the documentation for the Codeception `WebDriver` module `WPWebDriver` extends makes no mention of using `header` config: https://codeception.com/docs/modules/WebDriver#Configuration

**Comment by lucatume** [comment]
Hi @RobjS, thanks for taking the time to report an issue. You're correct: that documentation could use an update; I will look into that when I get back into the office. As to solving the problem when using `WPWebDriver`, you can set a cookie as indicated in a [question on Codeception proper](https://github.com/Codeception/Codeception/issues/2935#issuecomment-202367318), and check that on the site configuration.

**Comment by lucatume** [comment]
I had removed the mention of headers from the WebDriver module configuration and forgot to close the issue.
