### ISSUE TITLE
[BUG] `activatePlugin()` fails on WordPress 6.3 beta 2

### ISSUE THREAD

**Issue by n7studios** [lucatume/wp-browser#619]
**Environment**
OS: Linux 
PHP version: 7.4, 8.0, 8.1, 8.2  
Installed Codeception version: 4.2.2  
Installed wp-browser version: 3.1.9
WordPress version: 6.3 beta 2
Local development environment: N/A
WordPress structure and management: default

**Describe the bug**
`activatePlugin()` fails with the following error in WordPress 6.3 beta 2:
![Screenshot 2023-07-03 at 14 53 47](https://github.com/lucatume/wp-browser/assets/1462305/0542776d-86aa-4725-8446-e47b07837c8b)

This is because WordPress 6.3 beta 2 has introduced `<label class="label-covers-full-cell">`, replacing `<label class="screen-reader-text">`

6.2:
![Screenshot 2023-07-03 at 14 53 58](https://github.com/lucatume/wp-browser/assets/1462305/5f48959f-1623-4a16-8260-4a7724e0f29b)

6.3:
![Screenshot 2023-07-03 at 14 54 24](https://github.com/lucatume/wp-browser/assets/1462305/da9d8ab3-7a56-4d1b-9502-40ab3668dd8f)
![Screenshot 2023-07-03 at 15 01 51](https://github.com/lucatume/wp-browser/assets/1462305/c1da2491-018c-4a3c-9b69-a10176074080)

When `activatePlugin()` attempts to perform its `checkOption()`, the label intercepts the click.

As it's a beta release, no expectation that this be fixed here at this stage (maybe WordPress will change their markup again) - just making you aware ahead of a 6.3 release.

**Output**

**To Reproduce**
- Create a test, including a call to `activatePlugin()`
- Run the test

**Comment by n7studios** [comment]
Looks like this is no longer needed, as the label no longer intercepts the `checkOption()` call in WordPress 6.3 RC1, ensuring `activatePlugin()` works correctly 🎉

**Comment by lucatume** [comment]
Thanks @n7studios for the confirmation.

I have to admit I was trying to reproduce this, failing and having a couple of "what?!" moments.
