### ISSUE TITLE
grabWordPressAuthCookie pattern in HTTPS

### ISSUE THREAD

**Issue by Luc45** [lucatume/wp-browser#624]
https://github.com/lucatume/wp-browser/blob/d591a12891305b29ff0e1e08e2a173e6f915abf4/src/Codeception/Module/WPBrowserMethods.php#L141

If running under HTTPS, this cookie pattern is  `wordpress_sec_`

See `wp-includes/default-constants.php:268`

**Comment by Luc45** [comment]
ChatGPT

```php
protected function grabWordPressAuthCookie($pattern = null)
{
    if (!method_exists($this, 'grabCookiesWithPattern')) {
        return null;
    }

    // If custom pattern is provided, try it first
    if ($pattern) {
        $cookies = $this->grabCookiesWithPattern($pattern);
        if (!empty($cookies)) {
            return array_pop($cookies);
        }
    }

    // If no custom pattern or no cookie found, try the first default pattern
    $cookies = $this->grabCookiesWithPattern('/^wordpress_[a-z0-9]{32}$/');
    if (!empty($cookies)) {
        return array_pop($cookies);
    }

    // If still no cookie found, try the second default pattern
    $cookies = $this->grabCookiesWithPattern('/^wordpress_sec_[a-z0-9]{32}$/');
    return empty($cookies) ? null : array_pop($cookies);
}
```

**Comment by lucatume** [comment]
@Luc45 do you have some insight to share about this? Found something that would require fixing?

**Comment by lucatume** [comment]
Closing as stale.

**Comment by Luc45** [comment]
> @Luc45 do you have some insight to share about this? Found something that would require fixing?

Sorry, I've missed this. I don't remember what was happening at the time, but haven't encountered the need for it anymore. Agree with closing, thanks.
