### ISSUE TITLE
User configuration seems to be discarded when running bootstrap in batch mode

### ISSUE THREAD

**Issue by michelezamuner** [lucatume/wp-browser#63]
I tried running `wpcept bootstrap --wpRootFolder=my/custom/folder` but got the error:

```
[Codeception\Exception\ModuleConfigException]                                            
WordPress module is not configured!                                                      
                                                                                           
The path `/var/www/wordpress` is not pointing to a valid WordPress installation folder. 
```

Digging into the code:

https://github.com/lucatume/wp-browser/blob/master/src/Codeception/Command/WPBootstrap.php#L100

it looks like `$userConfig` is initialized only during the interactive bootstrap, and not during the batch one. Thus, when getting to:

https://github.com/lucatume/wp-browser/blob/master/src/Codeception/Command/WPBootstrap.php#L227

the user configuration is always an empty array, no matter what command line argument I'm passing.

**Comment by lucatume** [comment]
Thanks for reporting the issue, the commit above should fix it.
