### ISSUE TITLE
[DOC REQUEST] v4 migration guide

### ISSUE THREAD

**Issue by lucatume** [lucatume/wp-browser#630]
From [this comment](https://github.com/lucatume/wp-browser/issues/571#issuecomment-1713808538).

Note for self to write the v4 migration guide.

**Comment by charlesdeb** [comment]
Yes, please! I am trying to upgrade to v4 (and codeception 5) as there are some useful features in v4, but I am coming up with a bunch of errors. It was pretty simple for me to remove the non longer used commands from my codeception.yml file, but now I am hitting some errors in the MySQL modules in wpbrowser saying I am providing an invalid database name (although it is totally fine and was working in v3). Maybe it's related to you now using SQLite updates? Either way some kind of migration guide would definitely be handy...

**Comment by BrianHenryIE** [comment]
When upgrading from v3 to v4 and running tests in PhpStorm, the report no longer works properly:

> Test framework quit unexpectedly
>
> WARNING: 'reporters' option is not supported! Custom reporters must be reimplemented as extensions.

<img width="1110" alt="Screenshot 2023-12-05 at 1 49 39 PM" src="https://github.com/lucatume/wp-browser/assets/4720401/245082b2-2d56-45d4-b370-4dec670cc433">

The solution is easy: open Settings, PHP, Test Frameworks, Codeception

<img width="1071" alt="Screenshot 2023-12-05 at 1 52 43 PM" src="https://github.com/lucatume/wp-browser/assets/4720401/f55ea051-42da-4273-b350-36cd20579829">

And click the refresh button.

<img width="673" alt="Screenshot 2023-12-05 at 1 53 34 PM" src="https://github.com/lucatume/wp-browser/assets/4720401/7b93f364-d8c7-45dc-9afa-490e8ef5fdb5">

**Comment by lucatume** [comment]
Handled in [the documentation](https://wpbrowser.wptestkit.dev/migration/)
