### ISSUE TITLE
activatePlugin and deactivatePlugin require manual scrolling so they don't stumble upon the admin bar

### ISSUE THREAD

**Issue by dimitrismitsis** [lucatume/wp-browser#64]
Hi there :)

Please take a look at the screenshot. In this example, I'm trying to activate WPML Media.

This happens often because of the WP Admin bar and it's absolute positioning.

The solution for that would be to manually scroll there, inside the helper function.

![tm_dashboard_media_file_handlingcest trytotest fail](https://cloud.githubusercontent.com/assets/15674753/22564586/bc8e58de-e98d-11e6-8fe5-2dda8b97481e.png)

**Comment by dimitrismitsis** [comment]
I would like to make the pull request for that I'm not able to push the branch.
Either way, it might be easier if you handle it yourself in case you agree with this :)

**Comment by lucatume** [comment]
Thanks for opening the issue, I've just seen the issue.
I will open a PR myself and ping you to see if we got to the same code.
