### ISSUE TITLE
[BUG] Git Hub Pages are Down? 

### ISSUE THREAD

**Issue by justin-brightfire** [lucatume/wp-browser#651]
GitHub pages with documentation are down. Navigating to site results in 404 error. Looks as if some updates were being made, so maybe this is still a W.I.P. but prior documentation is no longer accessible on the Pages atm.

**Comment by lucatume** [comment]
The custom domain keeps being removed from the settings.
I've restored it and it should be back up and running.
In the meanwhile, you can access [the uglier link.](https://lucatume.github.io/wp-browser/)
