### ISSUE TITLE
[BUG] v4 doesn't like database names with periods in them

### ISSUE THREAD

**Issue by charlesdeb** [lucatume/wp-browser#667]
**Environment**
OS: Linux
PHP version: 8.0.30
Installed Codeception version: 5.0.12
Installed wp-browser version: 4.0.10
WordPress version: 6.3
Local development environment: PHP built-in server
WordPress structure and management: default

**Can you perform the test manually?**
Yes

**Codeception configuration file**  
N/A
**Suite configuration file**
N/A

**Describe the bug**

When running `vendor/bin/codecept init wpbrowser` I saw the error:

`Failed to initialize the WordPress installation: invalid database name: mydatabase.dev`

But when I renamed the database to `mydatabase-dev` in MySQL (and in `wp-config.php`) then the intialisation process worked properly. I had saw the error issue after upgrading from WPBrowser 3.x to 4.x, but didn't realise it was the database name that was at fault (it had worked perfectly in the previous version) and was trying to reinstall WPBrowser from scratch.

It would appear that some part of the codeception 5/wpbrowser 4 ecosystem doesn't like database names with periods in them.

**Output**
If applicable paste here the output of the command that's causing the issue:

```
$ vendor/bin/codecept init wpbrowser

In SiteProject.php line 55:
                                                                                          
  Failed to initialize the WordPress installation: invalid database name: mydatabase.dev
                                                                                          

In MysqlDatabase.php line 34:
                                         
  Invalid database name: mydatabase.dev
                                         

init [--path PATH] [--namespace [NAMESPACE]] [--] <template>


**To Reproduce**

As above

**Expected behavior**
I expected to be guided through the install process

**Comment by lucatume** [comment]
Thanks @charlesdeb for taking the time to open an issue.

Currently, period is not a supported character in the database validation, and that is what is causing the issue.

As you've already mentioned, you can immediately work-around the issue by not using the period character.

I will work on this issue next when I'm done with other work related to the project.
