### ISSUE TITLE
WordPress module doesn't load WordPress code

### ISSUE THREAD

**Issue by grulex** [lucatume/wp-browser#68]
I have enabled and configured `WordPress` and `WPDb` modules. However, the following test fails and says that `is_admin()` is undefined. Same with any other WordPress function. I'm sure `WPDb` is configured correctly. And there isn't much to configure for the `WordPress` module.

`class MyTest extends \Codeception\Test\Unit {`
`public function testMe() {`
`$this->assertFalse(is_admin());`
`}`
`}`

By the way, the test works when I use `WPLoader` module instead of those two.

If this is not a bug and everything works as expected, please consider writing a better high-level summary of what each module, including `WordPress`, is supposed to do. It's a bit confusing at the moment.

**Comment by lucatume** [comment]
Hi,

the `WordPress` and `WPDb` modules are meant to be used in functional testing; due to WordPress limitations those modules do not expose WordPress functions like `is_admin()`; to run the kind of assertion you are trying to run create an integration test (in the code below I'm assuming the integration test suite is called `integration`):

```shell
wpcept generate:wpunit integration My
```

and put your assertions there.

**Comment by grulex** [comment]
Thanks for your quick reply. That example was obviously not a real test. I just wanted to show that WordPress functions are not available when only `WordPress` module is used. This seems to go against what you're saying in your description: "it will load WordPress code in the same variable scope as the tests". This is what confused me in the first place.

And I still don't quite understand what the **purpose** of the `WordPress` module is. Why would someone use it instead of `WPBrowser` or `WPWebDriver`? Is it faster perhaps?

**Comment by lucatume** [comment]
The point you make is a correct one; I'm correcting the wording for the `WordPress` module description, thanks.

The `WPBrowser` or `WPWebDriver` modules will engage the full WordPress stack, server engine included. The `WordPress` module will instead hit the WordPress routing components directly (tipically the `index.php` file) thus making it faster.
The module is as close as I could get to a functional module keeping WordPress global dependency and use into account; but it can get better.
If you look at modules like the Laravel one provided by [Codeception](http://codeception.com/ "Codeception - BDD-style PHP testing.") you will see they provide direct access to the application code but that works for long-running capable applications: WordPress was never made to handle more than one request so the `WordPress` module is as close as I could get to it.

**Comment by grulex** [comment]
Perfect, this explains everything. Thanks!
