### ISSUE TITLE
[FEATURE REQUEST] Integrate with ACF

### ISSUE THREAD

**Issue by esteban-serfe** [lucatume/wp-browser#713]
**Describe the solution you'd like**
I'd like to be able to have a `havePostsInDatabase` to support Advanced Custom Fields plugin for extra data.

**Comment by lucatume** [comment]
Thanks @esteban-serfe for taking the time to request the feature.

Could you provide an example of the kind of API you would like to be able to use in the tests?
What is your current solution? Are you using `meta_input` to set the values?
