### ISSUE TITLE
[SETUP ISSUE] `composer require --dev lucatume/wp-browser` fails due to tdd-helpers 404 

### ISSUE THREAD

**Issue by montchr** [lucatume/wp-browser#742]
**Version 3.5**  
If you're opening an issue to report a breakage caused by version `3.5`; please read the [migration guide first](https://wpbrowser.wptestkit.dev/migration) first!

**Environment**
OS: Linux (NixOS)
PHP version: 8.2
Installed Codeception version: n/a
Installed wp-browser version: n/a
WordPress version: n/a
Local development environment: n/a
WordPress structure and management: n/a

**Did you use the `codecept init wpbrowser` command?**

No -- cannot install.

**Did you take a look at Codeception and wp-browser documentation?**

Yes, I copied the installation command from the docs:

```
composer require --dev lucatume/wp-browser
```

**Codeception configuration file**
n/a

**Suite configuration file**
n/a

**Describe the issue you're encountering**

The installation command fails.

**Output**

```console
./composer.json has been updated
Running composer update lucatume/wp-browser
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Package operations: 4 installs, 0 updates, 2 removals
  - Downloading lucatume/tdd-helpers (2.4.5)
 0/1 [>---------------------------]   0%    Failed to download lucatume/tdd-helpers from dist: The "https://api.github.com/repos/lucatume/tdd-helpers/zipball/68bd5e2d389011232d6b8f4045724ad54fb5ac57" file could not be downloaded (HTTP/2 404 ):
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/repos/contents#download-a-repository-archive-zip","status":"404"}
    Now trying to download from source
  - Syncing lucatume/tdd-helpers (2.4.5) into cache
 1/1 [============================] 100%
In Git.php line 473:

  Failed to execute git clone --mirror -- 'https://ghp...SPh:x-oauth-basic@github.com/lucatume/tdd-helpers.git' '/home/cdom/.local/state/composer/cache/vcs/https---
  github.com-lucatume-tdd-helpers.git/'

  Cloning into bare repository '/home/cdom/.local/state/composer/cache/vcs/https---github.com-lucatume-tdd-helpers.git'...
  remote: Repository not found.
  fatal: repository 'https://github.com/lucatume/tdd-helpers.git/' not found


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
```

**To Reproduce**

```
composer require --dev lucatume/wp-browser
```

**Screenshots**
n/a

**Additional context**

<https://github.com/lucatume/tdd-helpers> does not exist

**Comment by lucatume** [comment]
HI @montchr,

thanks for taking the time to report the issue.

The `tdd-helpers` library was [abandoned](https://packagist.org/packages/lucatume/tdd-helpers) some time ago.

Version 3.5 and 4.0 of this project will not require it, so I'm assuming you're using, in your project, a package that requires it.

Could you check? Are you **upgrading** a project from an older version of wp-browser? If so, which one?
