### ISSUE TITLE
Just a suggestion for the WPDb module

### ISSUE THREAD

**Issue by zengheng3** [lucatume/wp-browser#75]
When I used `dontHavePostInDatabase`
function to delete a customized post, 
it deleted only the post itself, but not the postmeta.
However in the function 'havePostInDatabase',
I can create posts with postmeta, so I think it's not quite logical.
If you could just add the function of `dontHavePostMetaInDatabase` in `dontHavePostInDatabase`,
that would be better.

**Comment by lucatume** [comment]
This is an excellent idea and on oversight on my side: thanks for reporting this.
Will refer this issue in a next version.
