### ISSUE TITLE
Class 'WP_UnitTestCase' not found

### ISSUE THREAD

**Issue by davout1806** [lucatume/wp-browser#8]
Hi,

I created a simple unit test. When I try to run it I get Class 'WP_UnitTestCase' not found in my php_error.log I was able to create and run a simple acceptance test. I'm sure I'm doing something stupid. 

Command to execute: 
vendor/bin/wpcept run unit

My unit.suite.yml
```
class_name: UnitTester
modules:
    enabled: [Asserts, UnitHelper]
```

My test class
```
<?php
use Simplexity\Cloud\Cdn\ContainerDirector;

class ContainerDirectorTest extends \WP_UnitTestCase
{
    public function setUp()
    {
        // before
        parent::setUp();

        // your set up methods here
    }

    public function tearDown()
    {
        // your tear down methods here

        // then
        parent::tearDown();
    }

    // tests
    public function testMe()
    {
        $dir = new ContainerDirector(2);
        $this->assertEquals('mkjtest', $dir->getContainer());
    }

}
```

My composer.json
```
{
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "wordpress",
        "type": "webroot",
        "version": "4.1",
        "dist": {
          "type": "zip",
          "url": "https://github.com/WordPress/WordPress/archive/4.1.zip"
        },
        "require" : {
          "fancyguy/webroot-installer": "1.0.0"
        }
      }
    }
  ],
  "autoload": {
    "psr-4": {
      "Simplexity\\": "wp-content/plugins/Simplexity"
    }
  },
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require": {
    "php": ">=5.3.0",
    "wordpress": "4.1",
    "fancyguy/webroot-installer": "1.0.0",
    "rackspace/php-opencloud": "~1.12"
  },
  "require-dev": {
    "codeception/codeception": "2.0.10",
    "lucatume/wp-browser": "master@dev"
  },
  "extra": {
    "webroot-dir": "wp",
    "webroot-package": "wordpress"
  }
}

```
Any ideas would be greatly appreciated.  
Thanks.

**Comment by lucatume** [comment]
hi, at first sight the problem seems to be that WPLoader module is not included. Also, looking at the readme, you will see that WPLoader is meant to be used in service (or functional) tests and not unit tests: the DB connection would be missing.

**Comment by davout1806** [comment]
Thanks for the reply. However, I don't follow what you are saying. Are you saying I should include the WPLoader even though it's not meant for unit tests?

Well in any case, it did get me to include WPLoader in my unite.suite.yml and now my test runs. Hopefully this won't be a problem in the future.

Thanks again.
