### ISSUE TITLE
Best way to share tests in repo?

### ISSUE THREAD

**Issue by moraleida** [lucatume/wp-browser#86]
Hi there, thanks for your work on this.

I'm curious if you have a strategy in place as to how to keep the tests in a repo but allow each local to set its environment variables (db name, user, etc).

So far I'm ignoring all `codeception.yml`, `tests/*.yml` and `tests/*.sql` and it looks ok, composer and init run seemingly fine. Just wanted to know if you foresee any issues with this approach or have a better one to suggest.

**Comment by lucatume** [comment]
Hi there, thanks to you for using this.

I share with the teams I work with all files but for the local configuration files; those are, usually:
* `codeception.yml`
* `*.suite.yml`
* the `tests/_output` folder
* the `vendor` folder
* other system related boilerplate files (e.g. Idea config files, Sublime Text config files and so on)

The tests I leave in the repository with the code, in the `tests` folder usually and in its simplicity that's the strategy I've seen applied the most.  
A build system of sort will take care of purging non-production files from a plugin/theme and ship the bare necessities (so tests are out).

The ratio is that the repos should always have a `*.dist.yml` file to set a common configurations for all and allow anyone to overwrite with local settings. The `dist` version of each configuration file is read **before** the local version and I usually set up the `dist` files to match the CI environment.  
This very repository adopts the same system.

When it comes to common environments I do not have personally, and have not seen, a common theme; for cross-compatibility Vagrant Boxes and Docker are the best solution; I use the latter.

Hope this helps.

**Comment by moraleida** [comment]
This helps a lot. Thank you!
