### ISSUE TITLE
Command `init` not defined.

### ISSUE THREAD

**Issue by shmulim** [lucatume/wp-browser#91]
I followed the steps here (http://codeception.com/for/wordpress) and I have successfully installed Codeception. But when I enter `codecept init wpbrowser` into the terminal to get started with Codeception for Wordpress, I get the error: `Command init not defined`. How can I correct this?

**Comment by lucatume** [comment]
Could you look into the `composer.lock` file what version of `wp-browser` and `codeception` was pulled?

**Comment by ajgagnon** [comment]
I'm having this issue as well:

"codeception/codeception" : "2.3.5",
"lucatume/wp-browser": "1.21.16",

**Comment by lucatume** [comment]
I've just tried the following sequence and could successfully initialise `wp-browser`:
```bash
mkdir project
cd project
composer init
# after answering Composer questions
composer require --dev lucatume/wp-browser
vendor/bin/codecept init wpbrowser
```

Things that come to my mind:
1. Codeception was installed globally (e.g. using `composer global require codeception/codeception` and is not up to date
2. what happens when using `codecept init Acceptance`? See [Codeception guide](http://codeception.com/docs/08-Customization#Installation-Templates)

**Comment by ajgagnon** [comment]
Ah #1 was exactly it. Codeception was installed globally. Uninstalled the global version and it's working great! Thanks so much for your help.

**Comment by lucatume** [comment]
Perfect then, thanks for taking the time to reply and confirm.
I'm closing the issue and taking a mental note.

Happy coding. And testing.

**Comment by Jon007** [comment]
oh wow...  the sequence of commands above works...

please update the documentation at: http://codeception.com/for/wordpress
the documentation suggest starting with:
codecept init wpbrowser
which returns simply 
codecept: command not found

After trying various options, the only thing that worked was to delete everything and start again with the command sequence above.

**Comment by unRARed** [comment]
`vendor/bin/codecept init wpbrowser` worked for me on a Ubuntu-based Vagrant setup.
