### ISSUE TITLE
Error redefining WP_LANG_DIR

### ISSUE THREAD

**Issue by ydlr** [lucatume/wp-browser#94]
When tests are run for all test suites at once, I sometimes get the error that WP_LANG_DIR is already defined.  This seems to be fixed by wrapping [this line](https://github.com/lucatume/wp-browser/blob/440bac6db10507bf07b30ca22c97cebabd030474/src/includes/bootstrap.php#L19) in an if statement that checks if constant is already defined, but I'm not sure if there are any side effects to doing that.

**Comment by lucatume** [comment]
Do not run all the tests at once: WordPress reliance on globals and constants will kill the suite or, worse, alter the test results; run the suites one by one:

```bash
codecept run acceptance && codecept run functional && ...
```
If it's not the `WP_L`

Thanks
