### ISSUE TITLE
Test suite wasn't completely generated when using an option

### ISSUE THREAD

**Issue by zengheng3** [lucatume/wp-browser#95]
I am using [robo](https://github.com/consolidation/Robo/) to execute the commands of codeception. To simplify the process, I used the silent mode and wanted to modify the configuration files after the generation of these files. But when I run 
    `codecept init wpbrowser -q`  
or `codecept init wpbrowser -n`
Only the unit test suite and wpunit test suite were generated, but not the functional and acceptance test suites. Then I tried   
`codecept bootstrap -q`  
and`codecept bootstrap -n`
 These 2 commands generate the test suites correctly,this means the problem is in WP-browser.
My WP-browser version is 1.21.10. Please help me.

**Comment by lucatume** [comment]
Seems like the silent/quiet options are not working as intended. Flagging as a bug.

**Comment by zengheng3** [comment]
I tried your new version but the quiet mode still doesn't work, could you fix this ?

**Comment by lucatume** [comment]
There is little to go by in your message: could you provide the output in terms of file structure? PHP notices? Did you try the quiet mode outside of a script context and running `codecept init wpbrowser -q`?

**Comment by zengheng3** [comment]
![image](https://user-images.githubusercontent.com/7296917/28710235-8d132280-7383-11e7-8dab-b5003cce33ef.png)
Just like this, -n option works well.

**Comment by lucatume** [comment]
Thanks for keeping on with this; could you try:

```bash
composer require lucatume/wpbrowser:dev-master
```

and tell me if that solves the issue?

**Comment by zengheng3** [comment]
Yes, this latest version fix the problem ! Thank you for the quick hotfix !

**Comment by lucatume** [comment]
You are most welcome for your patience!
And keep reporting any issue/bug you find: it's much appreciated.
